### ISSUE TITLE
No response on Transifex for join request

### ISSUE THREAD

**Issue by binotaliu** [readthedocs/sphinx_rtd_theme#1013]
### Problem

I have already sent a join request for `Chinese (Taiwan)` team 3 months ago, haven't got any response:

![3 months, 1 week ago: BinotaLIU requested to join the Chinese (Taiwan) language in the team sphinx-rtd-theme team.](https://user-images.githubusercontent.com/67255597/95849630-4106d680-0d3f-11eb-8376-500aec2891e7.png)

### Reproducible Project

N/A

#### Error Logs/Results

No Response

#### Expected Results

Someone should approve my request (or at least reject it).

### Environment Info

- Python Version: N/A
- Sphinx Version: N/A
- RTD Theme Version: N/A

**Comment by stsewd** [comment]
I think @agjohnson has access to transifex

**Comment by binotaliu** [comment]
ping @agjohnson

**Comment by geohadab** [comment]
I would like to join the team for arabic language

**Comment by agjohnson** [comment]
I've accepted all outstanding requests for team joins that no one had accepted yet. I'm not the gatekeeper to translations however, but to ensure we're missing these requests in the future, I've made sure that the rest of the team has access to our projects on Transifex.
