### ISSUE TITLE
Add configuration option to control scrolling of navigation menu

### ISSUE THREAD

**Issue by rootkea** [readthedocs/sphinx_rtd_theme#1015]
Hello!

* Read the Docs project URL: https://docs.readthedocs.io/en/stable/index.html

If we try to scroll just the table of contents to see the rest of items in index (left hand side), it scrolls beautifully without doing anything to the current page (right hand side). The page stays in the same position while we scroll the index. This is desirable.

But if we decide to scroll the page content (right hand side), it starts to scroll index (left hand side) too which is not desirable at all. User just wanted to read the rest of the page so she scrolled the content but wanted index to remain in its position.  

Here's a screencast to make it more clear:
![Peek 2020-10-19 19-08](https://user-images.githubusercontent.com/2694559/96459329-892b6a80-1211-11eb-97d3-3986533f2e6b.gif)

Thanks!

**Comment by stsewd** [comment]
Thanks, I have moved this issue to the theme repo.

**Comment by agjohnson** [comment]
This is an intended feature of the theme, not a bug. We might accept a theme configuration option to optionally disable this behavior however.

**Comment by Blendify** [comment]
This is already an option with https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-sticky_navigation
