### ISSUE TITLE
Arabic translation 

### ISSUE THREAD

**Issue by geohadab** [readthedocs/sphinx_rtd_theme#1028]
I have translated the strings to Arabic 
[sphinx_rtd_theme_Ar.txt](https://github.com/readthedocs/sphinx_rtd_theme/files/5743403/sphinx_rtd_theme_Ar.txt)

**Comment by stsewd** [comment]
@geohadab thanks for this, we manage the transaltions using transifex, please check https://sphinx-rtd-theme.readthedocs.io/en/stable/contributing.html#translations

**Comment by geohadab** [comment]
I already requested to arabic translation in the website ... But i could not join the team and the language is not added.

**Comment by stsewd** [comment]
@geohadab sorry about that, please subscribe to https://github.com/readthedocs/sphinx_rtd_theme/issues/1013
