### ISSUE TITLE
setup.py build: error: [Errno 2] No such file or directory: 'node_modules/.bin/webpack'

### ISSUE THREAD

**Issue by mgorny** [readthedocs/sphinx_rtd_theme#1033]
### Problem

The pypi tarball for 0.5.1 does not build.

```
$ tar -xf sphinx_rtd_theme-0.5.1.tar.gz
$ cd sphinx_rtd_theme-0.5.1/
$ python setup.py build
running build
running build_py

up to date in 189ms

found 0 vulnerabilities
error: [Errno 2] No such file or directory: 'node_modules/.bin/webpack'
```

If I were to guess, it's missing some file that would make npm actually install something. Even then, having `setup.py` download anything really sucks. And I think I've already suggested including prebuilt webpack in pypi releases.

### Environment Info

- Python Version: 3.9.1
- Sphinx Version: 3.4.1
- RTD Theme Version: 0.5.1

**Comment by stsewd** [comment]
You need to run npm first, see https://github.com/readthedocs/sphinx_rtd_theme/issues/1014

**Comment by stsewd** [comment]
BTW, the assets are there, you don't need to run npm, just need skip that https://github.com/readthedocs/sphinx_rtd_theme/issues/1014#issuecomment-754282374
