### ISSUE TITLE
No image link previews.

### ISSUE THREAD

**Issue by layne-sadler** [readthedocs/sphinx_rtd_theme#1042]
Thank you for the lovely theme.

### Problem
I'd like to be able to provide a url to an image in the configuration of the theme that will serve as the image link preview. If no url is provided by the user, then perhaps it could default to the Sphinx/ ReadTheDocs logo?

The following html tag is seemingly responsible for this.
```html
<head><meta name="og:image" content="https://.png" /></head>
```

### Reproducible Project
Project = https://aiqc.readthedocs.io/en/latest/ (includes requirements file)
Source = https://github.com/aiqc/aiqc/tree/main/docs 

- Python Version: `3.8.7`
- Sphinx Version: `Sphinx 3.4.3`
- RTD Theme Version: `sphinx-rtd-theme 0.5.0`

--- 

![image](https://user-images.githubusercontent.com/76759666/106278989-b5d82080-6209-11eb-9661-2f794e66ab5b.png)

On LinkedIn:
![image](https://user-images.githubusercontent.com/76759666/106277982-e9b24680-6207-11eb-803b-f96add80aeff.png)

On Twitter:
![image](https://user-images.githubusercontent.com/76759666/106279349-47e02900-620a-11eb-92fe-3317b14c8b1a.png)

**Comment by Daltz333** [comment]
Please [sphinxext-opengraph](https://github.com/wpilibsuite/sphinxext-opengraph)

**Comment by layne-sadler** [comment]
@Daltz333 thanks man! works great.

![image](https://user-images.githubusercontent.com/76759666/106370087-f5475f80-6324-11eb-8f5e-efffdc08db84.png)
