### ISSUE TITLE
Nav links toggle format with each click

### ISSUE THREAD

**Issue by pamolloy** [readthedocs/sphinx_rtd_theme#1044]
### Problem

Navigation links toggle format with every click.

### Reproducible Project

Navigate to any instance and click on any link in `wy-nav-side`. It will move to the corresponding header, make the link bold and the background darker. Then click on the link again and it will remove the bold and background formatting. It toggles with every click.

#### Expected Results

The format doesn't toggle with each click.

**Comment by pamolloy** [comment]
I noticed this when trying to extend this theme within our project without forking the theme. For some reason when I modified `wy-nav-side` to float it broke the Javascript attached to the links. The first time I click on a link generated from our project it moves the page to the link. Only on the second and each following click does it move the page to the corresponding header. I'm certainly not a web programmer, but it seems like this should be a lot simpler.

**Comment by stsewd** [comment]
Attaching a screenshot about the problem. Clicking on "LIBCLOUD_PROVIDERS" will toggle between bold and no-bold https://django-storages.readthedocs.io/en/latest/backends/apache_libcloud.html#libcloud-providers

![Screenshot_2021-02-03 Apache Libcloud — django-storages 1 11 1 documentation](https://user-images.githubusercontent.com/4975310/106818116-da872a80-6645-11eb-8aa5-b1c3ac1f73c3.png)
![Screenshot_2021-02-03 Apache Libcloud — django-storages 1 11 1 documentation(1)](https://user-images.githubusercontent.com/4975310/106818123-dd821b00-6645-11eb-802a-cae806a7d3a1.png)

**Comment by stsewd** [comment]
Looks like we already have this reported at https://github.com/readthedocs/sphinx_rtd_theme/issues/306
