### ISSUE TITLE
Feature: Dynamic PDF Rendering

### ISSUE THREAD

**Issue by Mentors4EDU** [readthedocs/sphinx_rtd_theme#1046]
### Problem

Some images that are too big aren't resized or too many whitespaces are added in the PDF between subheadings or figures. Also HTML and buttons don't render well in PDFs.

### Reproducible Project

![Whitespaces](https://raw.githubusercontent.com/Mentors4EDU/Images/master/Screenshot%20from%202021-02-07%2022-06-55.png)
![Images](https://raw.githubusercontent.com/Mentors4EDU/Images/master/Screenshot%20from%202021-02-07%2022-07-16.png)
![Error](https://raw.githubusercontent.com/Mentors4EDU/Images/master/Screenshot%20from%202021-02-07%2022-07-51.png)

#### Expected Results

I would like the PDF generation feature to be a bit more responsive. Again, this is just a feature request. rtd is really well developed, but this is just one of my biggest pet peeves. It would help many developers who want to publish their documentation PDFs from their rtd theme. Just a personal suggestion, but if this is a feature request you are willing to look into, I would love to subscribe to it.

**Comment by stsewd** [comment]
@Mentors4EDU do you know how other themes handle this? or some examples with other themes where this looks better?

**Comment by Mentors4EDU** [comment]
I am actually not quite sure of how other themes handle the PDF generation

**Comment by stsewd** [comment]
Also, just for clarification, you mean pdf generation from the live site? You can also build a pdf directly from sphinx https://docs.readthedocs.io/_/downloads/en/stable/pdf/

**Comment by Mentors4EDU** [comment]
PDF generation for docs sites using this theme has these sort of problems. It does seem buggy. An example is, https://lonero.readthedocs.io/_/downloads/en/latest/pdf/ and I know other developers also likely has similar problems.

**Comment by stsewd** [comment]
Ok, thanks for the link, now I see what you mean

**Comment by Blendify** [comment]
The styling for pdfs is handled by sphinx, not the theme so file a bug with sphinx directly.
I reported this a while ago https://github.com/sphinx-doc/sphinx/issues/8253 and it should be fixed in sphinx version 4.0.0
