### ISSUE TITLE
Support jupyter book theme options

### ISSUE THREAD

**Issue by joelostblom** [readthedocs/sphinx_rtd_theme#1054]
### Problem

The [sphinx book theme](https://github.com/executablebooks/sphinx-book-theme) defines some additional theme options that seem to currently not be supported by the rtd_theme. I tried building a book with this theme and got the following output:

```
WARNING: unsupported theme option 'search_bar_text' given
WARNING: unsupported theme option 'launch_buttons' given
WARNING: unsupported theme option 'path_to_docs' given
WARNING: unsupported theme option 'repository_url' given
WARNING: unsupported theme option 'repository_branch' given
WARNING: unsupported theme option 'google_analytics_id' given
WARNING: unsupported theme option 'extra_navbar' given
WARNING: unsupported theme option 'extra_footer' given
WARNING: unsupported theme option 'home_page_in_toc' given
WARNING: unsupported theme option 'use_repository_button' given
WARNING: unsupported theme option 'use_edit_page_button' given
WARNING: unsupported theme option 'use_issues_button' given
```

Most aspects of the theme still works, and the only visible issue is that the ToC in the left side bar does not show up for all entries and when navigating to them manually they are rendered with the default book theme in stead of rtd. The [jupyter books docs folder can be used for testing](https://github.com/executablebooks/jupyter-book/tree/master/docs).

### Environment Info

- Python Version: 3.8.6
- Sphinx Version: 3.5.0
- RTD Theme Version: 0.5.1

**Comment by stsewd** [comment]
Some options have other names google_analytics_id is analytics_id for example, you can check all options here

https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html

**Comment by Blendify** [comment]
You can do this to change the theme options when using different themes:

```
if html_theme == "sphinx_rtd_theme":
    html_theme_options = {
        # included in the title
        "display_version": False,
        "collapse_navigation": True,
        "navigation_depth": -1,
    }

    extensions.append('sphinx_rtd_theme')
```
