### ISSUE TITLE
Adding links to index.rst

### ISSUE THREAD

**Issue by KeyvanNajarian** [readthedocs/sphinx_rtd_theme#1058]
### Problem

I am really new to this. I generated documentation using the theme 'sphinx.ext.autodoc'. Can Modules from 'Module index' be added on the Home page separately? It does not work by just adding * :ref:` module.module ` in the index.rst. But I do not know what else is needed.

Give details on your issue.

### Reproducible Project

Please give a link to a public reproducible project or provide an example of the Restructured Text that gives an issue.

```rst
Place RST code here (if any).
```

#### Error Logs/Results

Place any images or error logs that might be able to help solve the issue here.

#### Expected Results

Please describe how this should work properly.

### Environment Info

- Python Version:
- Sphinx Version:
- RTD Theme Version:

**Comment by Blendify** [comment]
This is a question specific to sphinx and not this theme, please ask your question on [stackoverflow](https://stackoverflow.com/questions/tagged/python-sphinx ) or some other support system from https://www.sphinx-doc.org/en/master/
