### ISSUE TITLE
arbitrary add_css_file attributes are not supported

### ISSUE THREAD

**Issue by gmarull** [readthedocs/sphinx_rtd_theme#1100]
### Problem

It is sometimes necessary to add a CSS file with attributes such as `media` (for print, dark mode, etc.). As of today, this is not possible when using `sphinx_rtd_theme` because attributes seem to be ignored (excepting `title`): https://github.com/readthedocs/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/layout.html#L27

### Reproducible Project

Create a custom CSS file and add it to your project like this:

```python
app.add_css_file("css/my_customization.css", media="print")
```

In the example above, `media` attribute is ignored on the rendered pages.

#### Error Logs/Results

N/A

#### Expected Results

All attributes given to CSS files should be taken into account.

### Environment Info

- Python Version: 3.8.5
- Sphinx Version: 3.5.3
- RTD Theme Version: 0.5.1

**Comment by humitos** [comment]
Done in #1519
