### ISSUE TITLE
toctree caption paragraphs miss the "caption" class

### ISSUE THREAD

**Issue by ocharles** [readthedocs/sphinx_rtd_theme#1111]
### Problem

`toctree`s with captions are currently displayed as a raw `<p>` tag (in HTML output), without the `caption` class.

### Reproducible Project

https://rel8.readthedocs.io/en/latest/

Note the captions on each `toctree` in the sidebar are too big, and lack the correct colour:

![image](https://user-images.githubusercontent.com/20878/113484303-79da6980-949f-11eb-9911-3dad499a4a8e.png)

This is as-of https://github.com/circuithub/rel8/tree/6a3913b2b625724fbd67554b3cc1e3eb428f45de/docs

#### Expected Results

The sidebar looks more like the sidebar in the documentation for this theme:

![image](https://user-images.githubusercontent.com/20878/113484311-8ced3980-949f-11eb-9f5f-daa9b17ff57d.png)

**Comment by ocharles** [comment]
I note that the `p` elements also don't have `caption` in the default theme either, so maybe this is a Sphinx bug?

**Comment by Blendify** [comment]
From initial tests I think this is due to docutils 0.17 being installed. I am transferring the issue to the main rtd repository, docutils 0.17 should not be installed, sphinx has issues with it and I don't think it will be supported until sphinx 4.0.

**Comment by Daltz333** [comment]
Corresponding Sphinx issue https://github.com/sphinx-doc/sphinx/issues/9001

**Comment by ocharles** [comment]
Thanks folks, I'll pin docutils. Thanks!

**Comment by ocharles** [comment]
Ok, adding that pin has solved the problem. Thanks again!
