### ISSUE TITLE
Using Custom Pygments Styles

### ISSUE THREAD

**Issue by 8thHalfHour** [readthedocs/sphinx_rtd_theme#1121]
### Problem

There is a lot of conflicting into formation as to how to add custom pygments styles in the issues here and on other sites, many of which seem to work for some people and not for others. I would like to see a recommended method of adding custom pygment styles to the RTD theme added to the official documentation so it is very easy to understand and implement.

### Reproducible Project

N/A

#### Error Logs/Results

N/A

#### Expected Results

There should be at least one detailed, easily consumable description of how to add custom pygments styles to the Sphinx RTD theme included in the official documentation.

### Environment Info

- Python Version: v3.9.3
- Sphinx Version: v3.5.3
- RTD Theme Version: v0.5.2

**Comment by Blendify** [comment]
Setting the `pygments_style` is the official method. See sphinx documentation: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-pygments_style

**Comment by 8thHalfHour** [comment]
Yes, I understand that that is the way to select pygments styles from the RTD theme itself. I’m asking how to add — and where to add — custom themes not in the RTD theme. This is a question that has been asked about a thousand times on the Interwebs, and so far, there has been no official recommendation. Unless you are saying that your official recommendation is that no one use their own pygments styles?

**Comment by Blendify** [comment]
Sorry for misunderstanding your original question. From a quick google search, I found this: https://pygments.org/docs/styles/#creating-own-styles

If you have issues I would recommend reaching out to Sphinx itself rather than here in the sphinx-rtd-theme as creating a pygments style is independent of theme, the theme uses whatever is given to it.
