### ISSUE TITLE
Is it Possible to Remove Colon in Field List?

### ISSUE THREAD

**Issue by robloo** [readthedocs/sphinx_rtd_theme#1126]
### Problem

Sometimes it is useful to display an image as a field instead of text as shown below. While this may appear slightly strange, it's a design decision. However, there is always a Colon even when an image is used instead of text. There needs to be a way to disable the colon (:) for cases such as this.

![image](https://user-images.githubusercontent.com/17993847/114315405-defc1380-9acc-11eb-9aa2-2b3d7b30897f.png)

### Reproducible Project

Please give a link to a public reproducible project or provide an example of the Restructured Text that gives an issue.

```rst
:|e710|:
  **New Transaction:** Creates a new transaction for the selected account and opens the :ref:`transaction_editor`.
:|e118|:
  **Import:** Open the transaction import overlay.
```

#### Error Logs/Results

N/A

#### Expected Results

There should be a configuration to remove the colon. In fact I would argue that adding a colon to even text should not be the default behavior. The default should display the text exactly how it is written in the source file.

### Environment Info

- Python Version:
- Sphinx Version:
- RTD Theme Version: 0.5.2

**Comment by Blendify** [comment]
You can add custom css for this:
```
dl.field-list > dt:after {
  display: none;
}
```

To make this only affect select field list use a container directive:

https://docutils.sourceforge.io/docs/ref/rst/directives.html#container

```
.. container:: custom

   :|image|: Lorem Ipsum
   :|image|: Lorem Ipsum
   :|image|: Lorem Ipsum
```

In the case above the custom CSS would become:

```
.custom > dl.field-list > dt:after {
  display: none;
}
```

See the documentation below on how to add custom css to sphinx:

https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

**Comment by Blendify** [comment]
Let me know if everything works for you, ill close this issue in a few days.
