### ISSUE TITLE
Subsitution support in Figure Directive

### ISSUE THREAD

**Issue by robloo** [readthedocs/sphinx_rtd_theme#1127]
### Problem

Images are defined with subsitutions so they can be used in multiple places.

```rst
.. |file_1| image:: /images/file-1-light.jpg
  :alt: File View
```

However, it is impossible to then use this substitution in a figure like so:

```rst
 .. figure:: |file_1| 
    :align: center

    File view
```

I would expect this is a very common use case and can't understand why it isn't supported. Work-arounds encapsulating the image and figure in a table is the only current solution.

#### Error Logs/Results

Place any images or error logs that might be able to help solve the issue here.

Error is below
```
WARNING: image file not readable: |file_1|
```

#### Expected Results

Should be able to read an image substitution within a figure.

### Environment Info

- Python Version:
- Sphinx Version:
- RTD Theme Version:

**Comment by Blendify** [comment]
This is not an issue specific to the theme but a limitation of sphinx/docutils. I would suggest doing a feature request for sphinx/docutils.

It might be possible for this to be made to work but I am not sure, you will have to talk to people who know more about  sphinx/docutils.

```
.. |file_1|  /images/file-1-light.jpg

.. figure:: |file_1| 
   :align: center

   File view
```

The sphinx repository to create a feature request is here: https://github.com/sphinx-doc/sphinx
