### ISSUE TITLE
Lists are broken

### ISSUE THREAD

**Issue by Andrey1994** [readthedocs/sphinx_rtd_theme#1134]
### Problem

Bullet lists are broken when docs created on the readthedocs server, when I run it locally everything looks fine. 

### Reproducible Project

Can not reproduce locally, here is an example how it looks in production https://brainflow.readthedocs.io/en/master/SupportedBoards.html#playback-file-board 

https://github.com/brainflow-dev/brainflow 

```rst
To choose this board in BoardShim constructor please specify:

- board_id: -3
- other_info field of BrainFlowInputParams structure should contain board_id of device used to create playback file
- file field of BrainFlowInputParams structure

Supported platforms:

- Windows >= 8.1
- Linux
- MacOS
```

#### Error Logs/Results

![image](https://user-images.githubusercontent.com/8217521/115290076-e1f5a480-a15b-11eb-8719-a78811fd5e1a.png)

#### Expected Results

![image](https://user-images.githubusercontent.com/8217521/115290251-005ba000-a15c-11eb-99b1-0d47097cb55e.png)

### Environment Info

Production deployment, here is requirements.txt https://github.com/brainflow-dev/brainflow/blob/master/docs/requirements.txt

**Comment by Andrey1994** [comment]
I fixed it using older versions: https://github.com/brainflow-dev/brainflow/pull/273/files

**Comment by JamesRandom** [comment]
It is a problem with docutils==0.17, see #1115

**Comment by Andrey1994** [comment]
I tried newest sphinx_rtd_theme which specifies docutils < 0.17 and it didnt work for me. I also tried many different combinations of old versions and only this one worked for me.

```
docutils<0.17
sphinx_rtd_theme==0.4.3
```
