### ISSUE TITLE
[FR] Option for Code Highlighting Style

### ISSUE THREAD

**Issue by suitre77** [readthedocs/sphinx_rtd_theme#1143]
Hi,

it would be nice to have an option for changing the code highlighting. Eg., if highlight.js is used, there are plenty of different styles:

https://highlightjs.org/static/demo/

KR

**Comment by Blendify** [comment]
This is possible by changing the [`pygments_style`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-pygments_style).
