### ISSUE TITLE
Bullet list is missing bullets

### ISSUE THREAD

**Issue by bdemchak** [readthedocs/sphinx_rtd_theme#1145]
### Problem

I have a very small document that demonstrates my problem. It's just an index.rst file that contains some text, some bullets, more text and more bullets. The text of the bullets is being rendered, but the bullets themselves are not. 

### Reproducible Project

https://github.com/cytoscape/py4cytoscape/tree/0.0.9-doctest

(See the docs directory)

I have stripped everything out of the project and config except what's needed to show the problem. I get bullets just fine when using other themes: classic, alabaster, nature. 

This theme seemed to generate bullets about a year ago, but they seem to have gone missing sometime along the way.

```rst
Place RST code here (if any).
```

#### Error Logs/Results

The rendered incorrect version is here: https://py4cytoscape.readthedocs.io/en/0.0.9-doctest/

The text is:

Overview of py4cytoscape

3

py4cytoscape is a Python package that communicates with Cytoscape via its REST API, providing access to a set over 250 functions that enable control of Cytoscape from within standalone and Notebook Python programming environments. It provides nearly identical functionality to RCy3, an R package in Bioconductor available to R programmers.

py4cytoscape provides:

    functions that can be leveraged from Python code to implement network biology-oriented workflows;

    access to user-written Cytoscape Apps that implement Cytoscape Automation protocols;

    logging and debugging facilities that enable rapid development, maintenance, and auditing of Python-based workflow;

    two-way conversion between the igraph and NetworkX graph packages, which enables interoperability with popular packages available in public repositories (e.g., PyPI); and

    the ability to painlessly work with large data sets generated within Python or available on public repositories (e.g., STRING and NDEx);

    execute Python code on the Cytoscape workstation or in Jupyter Notebooks on local or remote servers.

With py4cytoscape, you can leverage Cytoscape to:

    load and store networks in standard and nonstandard data formats;

    visualize molecular interaction networks and biological pathways;

    integrate these networks with annotations, gene expression profiles and other state data;

    analyze, profile, and cluster these networks based on integrated data, using new and existing algorithms.

#### Expected Results

The rendered correct version is here: https://py4cytoscape.readthedocs.io/en/0.0.3/

The text I expect is:

Overview of py4cytoscape

3

py4cytoscape is a Python package that communicates with Cytoscape via its REST API, providing access to a set over 250 functions that enable control of Cytoscape from within standalone and Notebook Python programming environments. It provides nearly identical functionality to RCy3, an R package in Bioconductor available to R programmers.

py4cytoscape provides:

*    functions that can be leveraged from Python code to implement network biology-oriented workflows;

*    access to user-written Cytoscape Apps that implement Cytoscape Automation protocols;

*    logging and debugging facilities that enable rapid development, maintenance, and auditing of Python-based workflow;

*    two-way conversion between the igraph and NetworkX graph packages, which enables interoperability with popular packages available in public repositories (e.g., PyPI); and

*    the ability to painlessly work with large data sets generated within Python or available on public repositories (e.g., STRING and NDEx);

*    execute Python code on the Cytoscape workstation or in Jupyter Notebooks on local or remote servers.

With py4cytoscape, you can leverage Cytoscape to:

*    load and store networks in standard and nonstandard data formats;

*    visualize molecular interaction networks and biological pathways;

*    integrate these networks with annotations, gene expression profiles and other state data;

*    analyze, profile, and cluster these networks based on integrated data, using new and existing algorithms.

### Environment Info

- Python Version: 3
- Sphinx Version:
- RTD Theme Version:

I am running the RTD version on readthedocs.org with "CPython3" and "Sphinx HTML" set.

**Comment by intelkevinputnam** [comment]
The cause of this problem is a change in Sphinx 4+ where "sections" are no longer <div class="section" ....> but simply <section ...>. This breaks the CSS that read the docs uses to display the bullets. A quick fix is to add custom css:

.rst-content section ul li {
    list-style:disc;
    margin-left:24px
}

**Comment by intelkevinputnam** [comment]
Devs have found the issue and fix is on the way: https://github.com/readthedocs/sphinx_rtd_theme/issues/1115#issuecomment-814937111

**Comment by bdemchak** [comment]
Thanks to both of you!!! Thanks, thanks, thanks, thanks! We love sphynx_rtd_theme, and are glad to be able to continue with it.

**Comment by bdemchak** [comment]
@intelkevinputnam ... thanks for the suggestion. I *did* add custom CSS as suggested, but did not notice any bullets on the result. I'd really appreciate your taking a quick look and making a suggestion ... thanks!

https://github.com/cytoscape/py4cytoscape/blob/0.0.9-doctest/doc/_static/css/bullets.css

Could I be missing something dumb and simple?? 

Thanks!

**Comment by intelkevinputnam** [comment]
@bdemchak you need to do one more thing in your conf.py:

html_css_files = ['bullets.css']

And just put bullets.css in _static - no need for css sub directory.

**Comment by intelkevinputnam** [comment]
@bdemchak Yes. The next release of the theme should fix it.

**Comment by bdemchak** [comment]
Uh oh ... looks like there's more to this. Not only are bullets being dropped, but other list indicators (e.g., roman numerals) are getting lost, too. The suggested workaround is great for bullets. Do you know of a workaround for roman numerals?

For example:

I. Palettes for color mapping generators
II. Schemes for discrete and numerical mapping generators
III. Functions for automatically mapping discrete values to colors, opacities, sizes, heights, widths and shapes

Is coming out as:

Palettes for color mapping generators
Schemes for discrete and numerical mapping generators
Functions for automatically mapping discrete values to colors, opacities, sizes, heights, widths and shapes

Sorry I didn't notice this sooner ...

**Comment by intelkevinputnam** [comment]
@bdemchak The best way to fix the problem is to downgrade to a version of sphinx (3.5.4 I think) that doesn't have this problem.

for example:
```
pip3 install sphinx==3.5.4 
```
should do it.

**Comment by bdemchak** [comment]
@intelkevinputnam Well, that certainly helped ... I got the intended behavior for both bullets and numeric lists. And, this cleared up a line spacing issue between bullets, too. Thanks for this!

For other readers, I added "sphinx==3.5.4" to the beginning of my requirements.txt file.

**Comment by McSinyx** [comment]
At the time of typing, the theme has been fixed, though one still needs to force `sphinx_rtd_theme >= 1` for RTD to build correctly.
