### ISSUE TITLE
Expand icon (plus sign "+") does not display on expandable submenu items, only top level menu.

### ISSUE THREAD

**Issue by FrightRisk** [readthedocs/sphinx_rtd_theme#1147]
On the main menu in the left sidebar, anything I hover over that is expandable shows a "+". I can click on it to expand it. But on the submenu that opens, none of the expandable items show a "+". I can click on them and then they open and show a "-". I can open and close that item and the icons remain. But as soon as I click on another menu item, it goes away. How can I get expand indicators when hovering in submenus? Even better, how can I have them always show, not just when hovered over? First picture shows no + before "Documents" even though I am hovering over it (the snip tool doesn't show the cursor in captured images)

![image](https://user-images.githubusercontent.com/37218136/118754551-52fcaa80-b835-11eb-8db7-c48fb689d475.png)

And below you can see once I click on it, it shows the icon

![image](https://user-images.githubusercontent.com/37218136/118754199-8985f580-b834-11eb-8848-b3b57108687c.png)

### Reproducible Project

Please give a link to a public reproducible project or provide an example of the Restructured Text that gives an issue.

```
//main index:

.. toctree::
   :hidden:
   :maxdepth: 4

   get-started/index
   reference/index
   about/index

//references subsection index:

Hardware
-----------------------

.. toctree::
    :maxdepth: 2

    hardware/index

Documents
---------------

.. toctree::
    :maxdepth: 2

    documents/index

//the final hardware index file

***************
Hardware
***************

.. toctree::
    :maxdepth: 1
    
    microcontroller-boards
    motor-boards
```

#### Expected Results

I would expect the + to always show up when hovering over expandable menu items no matter where in the tree. I would also like to have them always display instead of having to hover over them

### Environment Info

- Python Version: 3.8.3
- Sphinx Version: 3.3.1
- RTD Theme Version: I don't know how to find it. It is about a year old.

**Comment by stsewd** [comment]
> RTD Theme Version: I don't know how to find it. It is about a year old.

You can find the version with

```
python -c "import sphinx_rtd_theme; print(sphinx_rtd_theme.__version__)"
```

Make sure you are using the latest version (0.5.2)

**Comment by FrightRisk** [comment]
Thank you. I am using 0.5.0. When I installed I typed, do I just do this again?

`$ pip install sphinx sphinx_rtd_theme sphinxcontrib-spelling`

And on Github, there is a workflow I see run here: https://github.com/DCC-EX/dcc-ex.github.io/actions/runs/843621132/workflow

It has this inside it, so I'm guessing every time I push to my sphinx branch it reinstalls all the latest versions and does a make? So I don't have to do anything on the github web side?:

`run: brew install sphinx-doc        
&& brew install enchant        
&& pip3 install sphinx-rtd-theme        
&& pip3 install sphinx-sitemap        
&& pip3 install sphinxcontrib-spelling
`

**Comment by stsewd** [comment]
you should be using the latest version now, yeah

**Comment by stsewd** [comment]
is the problem still present?

**Comment by FrightRisk** [comment]
I can't seem to update the theme on my local machine. Do I need something other than "pip install sphinx-rtd-theme"? It just prints dozens of lines about things that already "meet requirements"

**Comment by stsewd** [comment]
> I can't seem to update the theme on my local machine. Do I need something other than "pip install sphinx-rtd-theme"? It just prints dozens of lines about things that already "meet requirements"

you can force it by uninstalling the theme `pip uninstall sphinx-rtd-theme` and then installing it again, I think there is a reinstall command too.

**Comment by FrightRisk** [comment]
I was able to update it by forcing a version, "pip install sphinx-rtd-theme==0.5.2" . But when I run your command, it now shows 0.5.1. But if I try to update again, it shows 0.5.2. Very confusing:

![image](https://user-images.githubusercontent.com/37218136/119033173-ec81a480-b97a-11eb-900a-fe55adda94c6.png)

**Comment by FrightRisk** [comment]
If anyone can help, you can see this at https://dcc-ex.com. I have seen other sites that say they use RTD (noted at the bottom of the main page) and their submenu + and - work properly.

**Comment by Blendify** [comment]
Try setting these theme options:

```
html_theme_options = {
    # Toc options
    'collapse_navigation': False,
    'navigation_depth': -1,
}
```

This has the downside of increasing your projects build time see the docs: https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html#confval-collapse_navigation

**Comment by FrightRisk** [comment]
You are the man! That did it! The compile time for my web page isn't horribly longer. And thank you for pointing me to the documentation section to learn more about the other options. Should I close the issue now?

**Comment by Blendify** [comment]
Glad to help
