### ISSUE TITLE
code-block console backslash does not render command correctly

### ISSUE THREAD

**Issue by pdxjohnny** [readthedocs/sphinx_rtd_theme#1150]
### Problem

Console formatting of a `code-block` directive with backslashes does not continue formating the next line when the previous line is the invocation of a console command and the current line continues that command

### Reproducible Project

Please give a link to a public reproducible project or provide an example of the Restructured Text that gives an issue.

- https://intel.github.io/dffml/master/examples/icecream_sales.html#prediction
- https://raw.githubusercontent.com/intel/dffml/master/docs/examples/icecream_sales.rst

```rst

.. code-block:: console

    $ dffml train \
        -model tfdnnr \
        -model-epochs 300 \
        -model-steps 20 \
        -model-hidden 9 18 9 \
        -model-features population:int:1 temperature:float:1 \
        -model-predict sales:int:1 \
        -model-directory tempdir \
        -sources f=csv \
        -source-filename preprocessed.csv \
        -log debug

```

#### Error Logs/Results

![image](https://user-images.githubusercontent.com/5950433/119582446-62ba4880-bd79-11eb-8d07-923794b9c6ff.png)

#### Expected Results

Lines after `\` in a command that is displayed to be run still get formatted as the first line with a prompt (`$ `) does.

### Environment Info

- Python Version: 3.7.10
- Sphinx Version: 4.0.2
- RTD Theme Version: 0.5.2

**Comment by jessetan** [comment]
This is not unique to this theme, I can produce this in PDF output using Sphinx 3.4.3 and 4.0.2

**Comment by pdxjohnny** [comment]
Thank you! I hadn't had time to dig deeper when I filled, thanks for doing that.
