### ISSUE TITLE
Double-clicking on a class name in HTML docs also selects the class keyword

### ISSUE THREAD

**Issue by dlech** [readthedocs/sphinx_rtd_theme#1154]
### Problem

Double-clicking on a class name also selects the `class` keyword.

### Reproducible Project

This can be seen on sphinx_rtd_theme's own docs.

1. Go to: https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/api.html
2. Double-click on `test_py_module` to select that word.
3. See that `class test_py_module` is selected instead.

![image](https://user-images.githubusercontent.com/963645/119854306-952d8800-bed6-11eb-8d96-ec46ca63e562.png)

#### Expected Results

Only `test_py_module` should be selected.

### Analysis

It appears that this happens because there is no whitespace between the HTML containing `class` and the HTML element containing `test_py_module`

**Comment by Blendify** [comment]
This patch did not solve the issue for me, tested on Brave (Chrome based).

This issue would be better resolved by reporting the issue to sphinx, a space should be added by default.
