### ISSUE TITLE
Unable to refer a cross reference link inside the table

### ISSUE THREAD

**Issue by shureshh-reddy** [readthedocs/sphinx_rtd_theme#1156]
## This is Sphinx Table issue related to cross reference of links

Access [sphinx-rtd] website

| Feature                    | RTD  | THEME | RTD-THEME | 
|----------------------|-------------|------------|------------|
| Transit-Gateway available  | [sphinx-rtd] | [sphinx-theme] | [sphinx-rtd-theme] |

[sphinx-rtd]: <https://sphinx-rtd-theme.readthedocs.io/en/latest/index.html>
[sphinx-theme]: <https://sphinx-rtd-theme.readthedocs.io/en/latest/index.html>
[sphinx-rtd-theme]: <https://sphinx-rtd-theme.readthedocs.io/en/latest/index.html>

The content is written in my markdown file. The above referred links are working outside of the table but not inside. Do i need to configure any settings in conf.py or need to install any package? I tried using recommonmark==0.7.1 and myst-parser==0.14.0 but no luck.

**Comment by stsewd** [comment]
Hi, this looks like an issue with the myst-parser, not with the rtd theme, or does it work when using a different theme?

**Comment by s-vanam** [comment]
This is across parsers , I tried using both recommonmark and myst-parser and still have this issue.

I also see this issue with the default Sphinx theme too

**Comment by stsewd** [comment]
> This is across parsers , I tried using both recommonmark and myst-parser and still have this issue.
> 
> I also see this issue with the default Sphinx theme too

Thanks fort the additional information! @shureshh-reddy I think you should report this problem to the sphinx repo.
