### ISSUE TITLE
Toctree nesting is not accurate

### ISSUE THREAD

**Issue by humitos** [readthedocs/sphinx_rtd_theme#1158]
### Problem

Toctree nesting show sub-titles under the wrong title.

### Reproducible Project

In https://sphinx-hoverxref.readthedocs.io/en/latest/configuration.html you can see the following HTML structure:

* h1: Configuration
  * h2: General Settings
  * h2: Tooltipster
    * dl: hoverxref_role_types
    * dl: hoverxref_default_type
    * ...
  * h2: MicroModal.js
    * dl: hoverxref_modal_hover_delay
    * dl: hoverxref_modal_default_title
    * ...

#### Error Logs/Results

However, the left toctree shows a different one where all the `dl` are shown under `h2: MicroModal.js`. See the following screenshot:

![Screenshot_2021-06-07_16-46-26](https://user-images.githubusercontent.com/244656/121039359-4d014600-c7b1-11eb-8f58-a9eddc29168c.png)

#### Expected Results

Create the toctree on the left bar following the same structure of the HTML.

### Environment Info

- Python Version: 3.7
- Sphinx Version: 3.4.3
- RTD Theme Version: 0.5.2
- RTD Build: https://readthedocs.org/projects/sphinx-hoverxref/builds/13946691/

**Comment by Blendify** [comment]
I am not sure this is a bug in the theme looks more like an issue with sphinx because the generated HTML is wrong:

**Comment by humitos** [comment]
OK. I'll find a time later and report it there. Thanks!

**Comment by humitos** [comment]
I'm not able to reproduce this issue anymore.
