### ISSUE TITLE
Sidebar stuck to first nav page upon loading homepage

### ISSUE THREAD

**Issue by aiqc** [readthedocs/sphinx_rtd_theme#1163]
### Problem
When I load my homepage, it automatically jumps to the first header in the sidebar, which skips over my logo and search bar. I want to prevent that on the homepage. Tried setting `'sticky_navigation': False`.

Maybe this issue is related? https://github.com/readthedocs/sphinx_rtd_theme/issues/748 

---------- Current behavior ---------- 
![image](https://user-images.githubusercontent.com/74990642/121903422-49604880-ccf6-11eb-8d18-41c2391543ac.png)

<br/>

---------- Desired behavior ---------- 
![image](https://user-images.githubusercontent.com/74990642/121903484-5d0baf00-ccf6-11eb-87fa-a7ab9207e293.png)

<br/>
<br/>

### Reproducible Project
https://github.com/aiqc/AIQC/tree/main/docs
^ this is the build for https://aiqc.readthedocs.io

**index.rst**
```rst
.. toctree::
  :maxdepth: 2
  :caption: About
  :hidden:

  self
  mission
  community
  links
```

**conf.py**
```python
# some relevant html options
html_theme = "sphinx_rtd_theme"
html_logo = 'images/aiqc_logo_wide_white_docs_300px.svg'
html_theme_options = {
	'logo_only': True
	, 'display_version': False
	, 'sticky_navigation': False   #<~~~~~~~~~~~~~~~~~~~~~~ is this supposed to unstick it?
	, 'collapse_navigation': False
}
```
<br/>
<br/>

#### Error Logs/Results
JS Console Warning:
`This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.`

<br/>
<br/>

#### Expected Results

I'd like the DOM load of the homepage not to jump to the current page being viewed in the nav

### Environment Info

- Python Version: 3.8.7
- Sphinx Version: 3.4.3
- RTD Theme Version: 0.5.0

<br/>
<br/>

# Thank you

**Comment by Blendify** [comment]
The issue comes from referencing "self" in the toctree. Here are a couple solutions:

* Do not include self in the toctree
* Make "Overview" its own page so you have `index.rst` and `overview.rst`

**Comment by aiqc** [comment]
I removed self from toctree and did not replace it with anything. thank you
