### ISSUE TITLE
Bullet list does not match official readthedocs styling

### ISSUE THREAD

**Issue by joshgoebel** [readthedocs/sphinx_rtd_theme#1165]
### Problem

TOC nested bullet list looks ugly on `readthedocs.org` (no bullets, it's all collapsed to a single level)

<img width="496" alt="Screen Shot 2021-06-15 at 8 10 57 PM" src="https://user-images.githubusercontent.com/6473/122138976-e9f95a00-ce15-11eb-82ff-2624dd0eda1f.png">

### Reproducible Project

- https://github.com/highlightjs/highlight.js/tree/main/docs
- https://github.com/highlightjs/highlight.js/blob/main/README.md

#### Error Logs/Results

Doesn't seem relevant.

#### Expected Results

I expect that the theme should match the website.  That `readthedocs.org` should look like this, like it does when built locally:

<img width="459" alt="Screen Shot 2021-06-15 at 8 11 25 PM" src="https://user-images.githubusercontent.com/6473/122138969-e49c0f80-ce15-11eb-9d9b-84d514af8191.png">

### Environment Info

- Python Version: Python 3.9.5
- Sphinx Version: 3.4.0
- RTD Theme Version: 0.5.2
- myst-parser                   0.15.0

**Comment by joshgoebel** [comment]
It seems the CSS is just weird/broken on the main `readthedocs.org` site, but if this theme is trying to be canonical then I would expect it to match, no?

**Comment by stsewd** [comment]
Hi, where are you hosting your docs? This looks like a problem with the sphinx/theme version. Make sure to pin your deps in https://github.com/highlightjs/highlight.js/blob/main/docs/requirements.txt

**Comment by joshgoebel** [comment]
Oh sorry, https://highlightjs.readthedocs.io/en/latest/readme.html.

I'm under the impression `readthedocs.org` applies it's own theming (for consistency)... is this the canonical package they used or just a "meant to look like it to the best degree possible" clone?

I wouldn't expect a minor version difference to break like this.

**Comment by joshgoebel** [comment]
Ok, pinning the version to 0.5.2 fixes this, but why is readthedocs using 0.4.3 by default???
