### ISSUE TITLE
dd/dt styling does not match `readthedocs.org` CSS

### ISSUE THREAD

**Issue by joshgoebel** [readthedocs/sphinx_rtd_theme#1166]
Locally:

<img width="576" alt="Screen Shot 2021-06-15 at 9 35 20 PM" src="https://user-images.githubusercontent.com/6473/122144589-ccca8880-ce21-11eb-8648-04ab1775d080.png">

Read the docs:

See the nice blue background, etc.

<img width="545" alt="Screen Shot 2021-06-15 at 9 35 43 PM" src="https://user-images.githubusercontent.com/6473/122144587-cb995b80-ce21-11eb-9bc2-156e184e49b6.png">

- sphinx-rtd-theme              0.5.2
- https://highlightjs.readthedocs.io/en/latest/plugin-api.html

**Comment by joshgoebel** [comment]
Ok, pinning the version to 0.5.2 fixes this, but why is readthedocs using 0.4.3 by default???

**Comment by stsewd** [comment]
> Ok, pinning the version to 0.5.2 fixes this, but why is readthedocs using 0.4.3 by default???

That's to maintain backwards compatibility with old projects, new projects will use the latest version by default.

**Comment by joshgoebel** [comment]
Ah, that makes sense... just wish it was surfaced visually somewhere in the Read The Docs UI...
