### ISSUE TITLE
Missing font on mathjax output

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#1189]
On tests from sphinx 1.8 to Sphinx 4.1, the paragraph link text is showing placeholder font.

Test set up: firefox 88 on arch linux, html5 output.

Sphinx 1.8:

![image](https://user-images.githubusercontent.com/1140183/128766966-79cf8bec-629d-40d7-998f-dda10901c98c.png)

Sphinx 4.1:

![image](https://user-images.githubusercontent.com/1140183/128767008-cfd5891a-0a49-40b3-baca-ab432bb98b31.png)

This doesn't look to be an issue with the previous release:

![image](https://user-images.githubusercontent.com/1140183/128771026-493d5a8c-89dc-4aa0-b0cf-aad55ee70677.png)

**Comment by agjohnson** [comment]
Probably not a missing font necessarily. It looks like the actual text of the link changes between sphinx_rtd_theme 0.5.2 and what is in master.

**Comment by Blendify** [comment]
I found the issue and creating a PR: #1191
