### ISSUE TITLE
Parameter list in autodoc output has extra padding

### ISSUE THREAD

**Issue by thomascobb** [readthedocs/sphinx_rtd_theme#1196]
### Problem

A multiline docstring with a parameter list in the middle has extra padding on the parameter list. This is because both `.rst-content dl` and `.rst-content .section ul` have 24px padding, giving 48px padding in the middle of a docstring output.

### Reproducible Project

Repo: https://github.com/thomascobb/sphinx-rtd-them-padding-demo
Output: https://thomascobb.github.io/sphinx-rtd-them-padding-demo/

#### Error Logs/Results
```python
# mycode.py

def add_numbers(a: int, b: int = 0) -> int:
    """Add two numbers together

    :param a: The first number
    :param b: The second number

    It's a very useful function
    """
    return a + b
```
Produces:
![Screenshot 2021-08-11 at 09-55-05 API — Python documentation](https://user-images.githubusercontent.com/7705060/129000261-37baa92f-15c2-47a3-85fc-f0593e1e3738.png)

#### Expected Results

Suppress either the `.rst-content dl` or `.rst-content .section ul` `margin-bottom`. The following does this, but may not be the best solution:

```CSS
/* override field-list (Parameters list) to have no padding after */
dl.field-list {
    margin-bottom: 0;
}
```
### Environment Info

- Python Version: 3.7
- Sphinx Version: 4.1.2
- RTD Theme Version: 0.5.2

**Comment by benjaoming** [comment]
Great to have a Python example with types as well, going to add that in the demo, thanks :+1:
