### ISSUE TITLE
Optionally show more levels in left sidebar

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/sphinx_rtd_theme#1203]
Similar thing to what the PyData Sphinx Theme can do:

https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html#configure-the-navigation-depth-and-collapsing-of-the-sidebar

![Collapsible levels on navigation bar](https://pydata-sphinx-theme.readthedocs.io/en/latest/_images/demo-expandable-navigation.gif)

(Inspired by https://github.com/pydata/pydata-sphinx-theme/issues/340)

At the moment this can be done _on the current section_, but it forces me to open it to discover if there are more nested subsections.

**Comment by humitos** [comment]
> At the moment this can be done _on the current section_

I understand this is behavior is the following:

![Peek 2024-08-12 18-05](https://github.com/user-attachments/assets/6790fdab-7874-49f6-b330-53c745b2e3dc)


and what you are suggesting here is that we could implement the same behavior over _all the sections_ displayed in the navigation bar, right?

**Comment by humitos** [comment]
I was able to generate the navigation bar as you want by adding the following changes:

```python
html_theme_options = {
    'navigation_depth': 5,
    'collapse_navigation': False,
    'includehidden': True,
    'titles_only': False,
}
```

![Peek 2024-08-12 18-13](https://github.com/user-attachments/assets/7100288c-1603-498d-b4d7-7b9e2138aecd)


@astrojuanlu can you please try those configs and let me know?

**Comment by humitos** [comment]
By the way, the link from PyData theme is dead, this is the new one: https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/navigation.html

**Comment by humitos** [comment]
Also, I just found this example https://cloudcustodian.io/docs/index.html that uses our theme and it has the behavior you want. It could be a good one to check out the settings.

**Comment by astrojuanlu** [comment]
Thanks a lot, this looks like it!
