### ISSUE TITLE
Question mark instead of apostrophe

### ISSUE THREAD

**Issue by PrimozGodec** [readthedocs/sphinx_rtd_theme#1209]
### Problem

We are switching from Alabaster to Sphinx_rtd_theme. We noticed that all apostrophes in the documentation are now question marks (see the image below). 
I am not sure if it is an issue for this repository but I guess it has something to do with the theme since it was not the case with Alabaster before. Changes and config are available here https://github.com/biolab/orange3-text/pull/695. Documentation was build with `make htmlhelp` command. Any advice on what to check/how debug is welcome.

![Screenshot 2021-08-18 at 16 36 11](https://user-images.githubusercontent.com/6421558/129918711-2385b2b2-098f-431c-bfb7-eb59d706c1ed.png)

### Reproducible Project

https://github.com/biolab/orange3-text/pull/695

#### Error Logs/Results

No error in the log. It is a building log:

```
sphinx-build -b htmlhelp -d _build/doctrees   . _build/htmlhelp
Running Sphinx v4.0.2
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [htmlhelp]: targets for 0 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
no targets are out of date.
build succeeded.

You can now run HTML Help Workshop with the .htp file in _build/htmlhelp.

Build finished; now you can run HTML Help Workshop with the .hhp project file in _build/htmlhelp.
```
#### Expected Results

Apostrophes should be parsed as apostrophes. 

### Environment Info

- Python Version: 3.8
- Sphinx Version: 4.1.2
- RTD Theme Version: 0.5.2

**Comment by agjohnson** [comment]
This looks like a missing font codepoint. The character is not basic apostrophe, but is instead some other unicode apostrophe. You can try replacing with a basic apostrophe. The font used here has fairly good unicode support, but it's not surprising that there is not a codepoint here, there are a lot of apostrophe permutations.

**Comment by PrimozGodec** [comment]
@agjohnson thank you for your response. I checked the apostrophe and it is a basic apostrophe with the code 0x27. 

I am not sure if it is really a font issue since when I open the compiled HTML there is already � (replacement) character compiled in the code. So the change seemed to happen in the compilation of the documentation.

**Comment by PrimozGodec** [comment]
Thank you for your concrete reply. I found out that we have no longer need to use htmlhelp builder so I just moved html builder. Everything is working correctly with html builder. I am guessing that it has something to do with htmlhelp smart quoting.
