### ISSUE TITLE
poor-man's bold in monospace

### ISSUE THREAD

**Issue by pkra** [readthedocs/sphinx_rtd_theme#121]
The `highlighting` class specifies `"Incosolata","Consolata","Monaco",monospace` as font-family.

However, `Monaco` does not have a bold variant, so poor-man's bold is used which makes the spacing not mono-spaced.

See also https://github.com/mathjax/MathJax-docs/issues/32#issuecomment-42584790

**Comment by ihnorton** [comment]
FWIW, on macOS 10.12 (tested both Chrome 63 and Firefox 57), the comma in the Andale font looks unfortunately like a slightly-stout period:

![image](https://user-images.githubusercontent.com/327706/34220420-9cfcb6e0-e582-11e7-9668-a24ef01bba18.png)

(from: https://xtensor.readthedocs.io/en/latest/numpy.html)
