### ISSUE TITLE
sphinx-rtd-theme 0.5.2 has requirement docutils<0.17, but you have docutils 0.17.1.

### ISSUE THREAD

**Issue by mborsetti** [readthedocs/sphinx_rtd_theme#1211]
Please support current package releases and/or remove overly restrictive requirements!

**Comment by Blendify** [comment]
Docutils 0.17 gives different HTML than previous versions resulting in an inconsistency,
to prevent this we only support versions that have been validated to be compatible.

`docutils<0.17` support has already been added and will be released in 1.0.0,
you can try this version now, see: https://pypi.org/project/sphinx-rtd-theme/1.0.0rc1/
