### ISSUE TITLE
HTML formatting issues after updating sphinx

### ISSUE THREAD

**Issue by dp0s** [readthedocs/sphinx_rtd_theme#1214]
### Problem

I'm hosting the documentation for my python project on readthedocs, there are 2 formatting problems in the following section:

https://dpowers.readthedocs.io/en/latest/reference/power.html#Dpowers.KeyboardAdaptor.key

1st problem: The right margin is not respected (in this section of the documentation only).
2nd problem:  (for all sections) The font color of class and method names/arguments is entirely blue, although it should be black (with blue background). Other documentations on readthedocs look fine in my browser. --- similar to #1212

They occured after updating sphinx version to 4.1.2 from 3.4.3 - I can reproduce this locally on my computer.

### Reproducible Project

The source folder for the documentation is here:
https://github.com/dp0s/Dpowers/tree/master/docs

#### Error Logs/Results

Local build on my computer with sphinx 4.1.2

![Screenshot at 2021-08-19 22-58-35](https://user-images.githubusercontent.com/61638967/130143125-9d4fc75f-a2d5-48e8-b67e-3385500a887b.png)

#### Expected Results

Local build on my computer with sphinx 3.4.3

![Screenshot at 2021-08-19 22-32-24](https://user-images.githubusercontent.com/61638967/130140178-6d8aea8e-b6c6-4894-a5e9-37ce196648b1.png)

### Environment Info

- Python Version: 3.7
- Sphinx Version: 4.1.2 / 3.4.3
- RTD Theme Version: 0.5.2

### Note
I recently introduced the sphinx hoverxref extension, which is still in beta mode. So I rebuilt the docs for an old version of my repository (v0.1.2) without hoverxref extension and the problem is the same.

**Comment by dp0s** [comment]
Just noticed that the 2nd problem was already reported today in #1212.  So it should probably be discussed there.

That leaves the 1st problem concerning the right margin, which seems to be a bug.

**Comment by dp0s** [comment]
For completeness: I tested building the documentation using the python_docs_theme  instead, still in sphinx 4.1.2.  There is no margin problem.  So it seems specific to sphinx_rtd_theme in combination with the sphinx version.

**Comment by stsewd** [comment]
Can you test if these problems go away with the version from master? You can also try our pre-release form pypi https://pypi.org/project/sphinx-rtd-theme/1.0.0rc1/

**Comment by dp0s** [comment]
Thanks for the suggestion, I tried 1.0.0rc1 with sphinx 4.1.2. locally:

![Screenshot at 2021-08-20 16-35-14](https://user-images.githubusercontent.com/61638967/130294405-7bf518ca-31fe-4dea-8643-24f90a2a659b.png)

As you can see the color problem is fixed :)  the right margin problem is still there.


I narrowed down the margin problem and found that 

`.. autodata:: Dpowers.KeyboardAdaptor.key` 

is displayed properly (i.e. the right margin is respected).

The problem occurs only for the `key` property's documentation when using 

`.. autoclass:: Dpowers.KeyboardAdaptor`

**Comment by dp0s** [comment]
Regarding the margin problem, I narrowed it down. It is an issue of how the autoclass directive handles the documentation of property objects with long code examples. For demonstration, I added the following example in my project:

```
class MyTestClass:
    
    
    @property
    def a_property_with_long_code_example(self):
        """
        This is a property with long code example::
        
            print("Some kind of long line to exceed the right margin ---------------------------------------------------------------------------------------------------")
        """
        pass

    
    def a_function_with_long_code_example(self):
        """
        This is a function with long code example::

            print("Some kind of long line to exceed the right margin ---------------------------------------------------------------------------------------------------")
        """
        pass
```


Now if I build the documentation of the following lines:
```
.. autoclass:: Dpowers.MyTestClass

.. autodata:: Dpowers.MyTestClass.a_property_with_long_code_example
```

the result is:
![Screenshot at 2021-08-21 00-06-32](https://user-images.githubusercontent.com/61638967/130298198-673e4cc8-c44a-4c68-a35d-c1c0cc800bb8.png)
