### ISSUE TITLE
pygments_style is ignored

### ISSUE THREAD

**Issue by tbekolay** [readthedocs/sphinx_rtd_theme#122]
I've unfortunately had to self-host my docs as building them is very expensive. I'm using the `sphinx_rtd_theme` locally, which is excellent, thanks so much for open sourcing it! I tried changing `pygments_style` in my `conf.py` and nothing changed.

I figured out a local workaround; `layout_old.html` contains the line

``` html
<link rel="stylesheet" href="{{ pathto('_static/pygments.css', 1) }}" type="text/css" />
```

I added this line to `layout.html` in my `site-packages` (at line 39) and `pygments_style` works again. I'm curious if this is desired behavior?

**Comment by baltasvejas** [comment]
I used your suggested workaround and I happy with it :)
Thanks.
