### ISSUE TITLE
Strange spacing when highlighting search results

### ISSUE THREAD

**Issue by coot** [readthedocs/sphinx_rtd_theme#1223]
## Details

* Read the Docs project URL: https://cabal.readthedocs.io/en/latest/setup-commands.html?highlight=flag#cmdoption-runhaskell-Setup.hs-configure-f

The above link `-f flag name or -f -flagname` with `flag` highlighted, but when there's no highlighting it shows `-f flagname or -f flagname`.

The original issue https://github.com/haskell/cabal/issues/7475

**Comment by nienn** [comment]
This has been fixed in version **1.0** (currently **1.0.0rc1**/**latest**) with the PR #860.
