### ISSUE TITLE
Does RTD support html_logo in conf.py to be specified as a URL?

### ISSUE THREAD

**Issue by cmcantalupo** [readthedocs/sphinx_rtd_theme#1226]
## Details

* Read the Docs project URL:
https://geopm.github.io/geopmdpy/

## Expected Result

* I made this change:
https://github.com/geopm/geopm/pull/1834/files

I expected to be able to use the sphinx 4.0 feature to specify html_logo as a URL.

## Actual Result

but the output index.html file has this content:
```
<img src="_static/https://geopm.github.io/images/geopm-logo-clear.png" class="logo" alt="Logo"/>
```

**Comment by cmcantalupo** [comment]
Thanks @stsewd!

**Comment by Blendify** [comment]
Hi, this feature should now be supported with version 1.0.0 of the theme.

**Comment by cmcantalupo** [comment]
Great.  Thanks @Blendify!  I will try it out soon.

**Comment by cmcantalupo** [comment]
I have verified that with version 1.0.0 of the RTD theme I am getting the correct output:

https://geopm.github.io/geopmdpy/

That web page was created based on the updated PR here:

https://github.com/geopm/geopm/pull/1834

which specifies html_logo as a URL.
