### ISSUE TITLE
Custom css config issue

### ISSUE THREAD

**Issue by sistia01** [readthedocs/sphinx_rtd_theme#1227]
Hello! 

I have created a website using the sphinx readthedocs theme but I am having some issues with the deployment of the website (particularly with the color of the background and font). On my local drive (via VSCode) I see that the font and background colors were changed (theme_edits.css file). When I do make html in the index.html file I see the same thing (screenshot) but when I build the website via readthedocs the colors of the background (which I want changed to black) and the font of the sidebar headings and links to websites (changed to green) remain as their default version (grey and blue, respectively). I was wondering I you had any advice on how I can fix this issue?

<img width="1294" alt="Screen Shot 2021-09-07 at 3 50 04 PM" src="https://user-images.githubusercontent.com/59894711/132402599-75e03193-a5cf-46e4-9648-567a976b34c2.png">

<img width="1122" alt="Screen Shot 2021-09-07 at 3 50 39 PM" src="https://user-images.githubusercontent.com/59894711/132402665-fe504eee-61d6-4d17-a54c-31520f34b4d7.png">

**Comment by sistia01** [comment]
The link to my repo: https://github.com/sistia01/Giotto-Sphinx-Website

Thanks for your help!

**Comment by nienn** [comment]
Hi @sistia01,
Do you have a link to your repo built website?

**Comment by sistia01** [comment]
Hi, 

Yes: https://giottoteam-giotto-sphinx-website.readthedocs-hosted.com/en/latest/

**Comment by nienn** [comment]
I might be missing something here, maybe @agjohnson can help more.

As far as I can tell, you don't have the right setup in your `conf.py`.
The `html_css_files` should be pointing at your custom css file, on `css/theme_edits.css`. Instead is set as

```
html_css_files = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"]
```

_Related documentation: https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html_

**Comment by sistia01** [comment]
Hi, 

I just updated the conf.py file it to see if maybe that is the issue but it looks like I am still having the same issue.

**Comment by stsewd** [comment]
@sistia01 looks like your static path is wrong https://github.com/sistia01/Giotto-Sphinx-Website/blob/64d219c95b8b8820650dd46df328b78ffa66f5e2/source/conf.py#L62

It should be outside the `_build` directory, and you shouldn't commit that directory in your repo, as it contains all the generated files of running `sphinx-build`

**Comment by sistia01** [comment]
Hi, 

I've updated the _static path but now the letters on the navigation bar have all turned green (except for the Changelog link)? Any idea why that would have happened? 

It isn't like that on my VSCode preview (screenshot)

![Screen Shot 2021-09-08 at 2 05 47 PM](https://user-images.githubusercontent.com/59894711/132561577-7b986819-0b3f-4cdb-a2a0-e6b3ca799541.png)

**Comment by nienn** [comment]
I'm not sure what you mean by navigation bar. The screenshot you posted only shows the `.wy-menu-vertical p.caption` as green, which is set so on your `theme_edits.css`.

Anyway, this now seems to be a problem related to the custom css selectors scope.
The original issue with the custom css not being setup correctly seems to be fixed.
May I close this issue?
