### ISSUE TITLE
Help with internal links not working 

### ISSUE THREAD

**Issue by sistia01** [readthedocs/sphinx_rtd_theme#1228]
Hello! 

Is it possible to link a word within a sentence to a section below?

For example: 

For more information please see `Additional Information <AddedInformation>`_

Additional Information 
------------------------

etc. 

I have tried to do this within my documentation through a few different methods (outlined here: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/CheatSheet.html) but have not been able to get the "jump" to work. The words show up as highlighted (and look as if you could click on them) but they do not jump to the headers to which they are "tied" 

See: https://github.com/sistia01/Giotto-Sphinx-Website/blob/main/source/gettingstarted.rst

**Comment by nienn** [comment]
Hi @sistia01. There appear to be several errors in your code. Your links aren't formatted correctly and, for this link [:ref:`Errors and FAQs Section <faqs>`](https://github.com/sistia01/Giotto-Sphinx-Website/blame/main/source/gettingstarted.rst#L48) for example, I can't find any corresponding section label. 

In **[typo3 CheatSheet](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/CheatSheet.htmll#cross-references)**, under the section _Cross references_ you can read:
> A section with the label intersphinx must exist! It is placed before the header

You can also check for more information here: _[www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#internal-links](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#internal-links)_

**Comment by nienn** [comment]
Hi @sistia01 it's been some time so I'm assuming you were able to fix this problem. Feel free to reopen the issue otherwise.

**Comment by sistia01** [comment]
Hi @nienn, I apologize for the late response -- I was caught up with other projects and missed this reply. 

I haven't been able to solve the issue. The fan's section that you mentioned above is another rst file in my repo (errorsfaqsandtips.rst). 

The way that I understand it (correct my if I am wrong) is that in order to reference a section on the same rst file: 

See `section <sectiontoreference>`_ for more information. 


.. sectiontoreference:

Section Title 
-----------

Writing ...
