### ISSUE TITLE
Scrolling unexpectedly slow

### ISSUE THREAD

**Issue by Blendify** [readthedocs/sphinx_rtd_theme#1238]
### Problem

Scrolling becomes unpredictably slow when scrolling to the bottom of the page then back up.
I am unsure if this is a bug in Chrome or an issue without scrolling JS not working correctly with newer versions of chrome.

### Reproducible Project

https://docs.blender.org/manual/en/latest/advanced/command_line/render.html

https://developer.blender.org/diffusion/BM/browse/trunk/blender_docs/manual/advanced/command_line/render.rst

#### Error Logs/Results

- None

#### Expected Results

Scrolling should be at the same speed throughout the webpage.

### Environment Info

- Python Version: 3.9
- Sphinx Version: 4.1.1
- RTD Theme Version: 1.0.0
- Chrome Version:  94.0.4606.61
- OS: Ubunut 21.04

**Comment by Blendify** [comment]
While debugging, I found that the issue goes away when removing  `position: fixed` from `.wy-nav-side`

**Comment by astrojuanlu** [comment]
Can't reproduce :/ (Chromium, latest Linux Mint)

**Comment by nienn** [comment]
I can reproduce it in Chrome. It happens when the function `onScroll` from `theme.js` is triggered by having both the content and the `.wy-side-scroll` scroll.

This function was last altered 6 years ago so I'm not sure yet why this started happening now. Also in Firefox works fine.

Bellow you can see the problem when the function is trying to set the scroll on the sidebar from the `onScroll` event:

![Slow Scroll](https://user-images.githubusercontent.com/4049894/135415201-30ae1734-c424-4690-9a35-294f426e3a21.gif)

**Comment by pzhlkj6612** [comment]
Hi there!

> This seems to be a new **Chrome** problem but can't find other references to it.

Yes, it is. Please see [1252415 - Catastrophic issue on chrome 94 with scrollbars - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1252415).

On Ubuntu 20.04.2, I've downloaded Chromium dev 95.0.4638.17 and 96.0.4651.0 (found on https://chromium.cypress.io/linux/ ) and tried to visit https://docs.readthedocs.io/en/stable/tutorial/ (revision: [f0da2a47](https://github.com/readthedocs/readthedocs.org/tree/f0da2a478705c794ce046d67a3eededf5595fd33)) . On version 95, the scrolling speed is slow; on version 96, the speed is normal.

As `skobes@chromium.org` said in [comment 15](https://bugs.chromium.org/p/chromium/issues/detail?id=1252415#c15):

> The fix for this issue (crrev.com/923451) has been merged to the Chrome 94 release branch. Users will get the fix with the next stable channel refresh.

I *guess* this issue will be solved in Chrome 94 within a few days.

**Comment by nienn** [comment]
Hi @pzhlkj6612 thank you for referencing the Chromium issue and fix 👍 This helps a lot!
Hopefully it will get fixed in few days.

**Comment by madjxatw** [comment]
I suddenly encountered this issue several days ago (after upgrading MS Edge), thanks for clarifying it is a Chrome issue.

**Comment by Blendify** [comment]
Thank you @pzhlkj6612 for pointing to the Chrome bug report. I figured it was such a bug but like Ana I couldn't find reference to it.

Due to this not being a bug in the theme, this issue can be closed.

**Comment by pzhlkj6612** [comment]
Hi everyone, now I'm using Windows 10 Pro 2004 (10.0.19041.867). Since I updated Microsoft Edge from 94.0.992.31 to 94.0.992.38 and Google Chrome from 94.0.4606.61 (mentioned by OP) to 94.0.4606.71, I can scroll the page normally.

**Comment by madjxatw** [comment]
MS Edge version 95.0.1020.9 beta on Linux still has the issue.

**Comment by pzhlkj6612** [comment]
> MS Edge version 95.0.1020.9 beta on Linux still has the issue.

MS Edge [beta 95.0.1020.9](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-beta-channel#version-95010209-september-28) was released on September 28, while [stable 94.0.992.38](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-94099238-october-1) (fixed) was released on October 1. I *guess* the fix has not been applied to the beta channel at that time.

**Comment by madjxatw** [comment]
> > MS Edge version 95.0.1020.9 beta on Linux still has the issue.
> 
> MS Edge [beta 95.0.1020.9](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-beta-channel#version-95010209-september-28) was released on September 28, while [stable 94.0.992.38](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#version-94099238-october-1) (fixed) was released on October 1. I _guess_ the fix has not been applied to the beta channel at that time.

Got it, thanks for sharing this info!
