### ISSUE TITLE
No stylesheet after upgrading to 1.0.0

### ISSUE THREAD

**Issue by jstockwin** [readthedocs/sphinx_rtd_theme#1240]
### Problem

Upgrading to version 1.0.0 means the main stylesheet is no longer included.

### Reproducible Project

We have the following config:
```
html_theme = "sphinx_rtd_theme"

html_favicon = "favicon.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_context = {
    "css_files": [
        "_static/theme_overrides.css",  # override wide tables in RTD theme
    ],
}
```

when we generate our project using version 0.5.2, I get the following (correct) stylesheet section in the HTML:
```
<link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
<link rel="stylesheet" href="_static/pygments.css" type="text/css" />
<link rel="stylesheet" href="_static/theme_overrides.css" type="text/css" />  
 
<link rel="shortcut icon" href="_static/favicon.ico"/>
```
however after upgrading to version 1.0.0 (and making no other changes), the output is:
```
<link rel="stylesheet" href="_static/theme_overrides.css" type="text/css" />
<link rel="shortcut icon" href="_static/favicon.ico"/>
```
i.e. the main `theme.css` is missing, as is `pygments.css`. The documentation is almost completely unstyled.

I guess it could be due to the explicit `html_content` declaration?

#### Error Logs/Results

N/A

#### Expected Results

The documentation should be styled still.

### Environment Info

- Python Version: 3.8.10
- Sphinx Version: 4.2.0
- RTD Theme Version: 0.5.2/1.0.0

**Comment by krivenko** [comment]
I can confirm this issue.

I use a similar `html_context` option in a couple of project, and upgrading `sphinx_rtd_theme` from 0.5.2 to 1.0.0 resulted in missing stylesheets:

https://github.com/krivenko/libcommute/commit/37df6b145ca93e439d080fedf39199e6677bc899#diff-a11faa5810ac713931e63304028150455c6e34d4aef559c6ab0b6c7219153ffaL11-R8

**Comment by stsewd** [comment]
You should be using https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_css_files instead.

**Comment by jstockwin** [comment]
Thanks for the reply @stsewd. I can confirm that switching to `html_css_files` works, so will close this issue.

In my case, that's changing
```
html_context = {
    "css_files": [
        "_static/theme_overrides.css",  # override wide tables in RTD theme
    ],
}
```

to
```
html_css_files = ["_static/theme_overrides.css"]  # override wide tables in RTD theme
```
