### ISSUE TITLE
Latest versions seem to be incompatible with max width changes

### ISSUE THREAD

**Issue by EmmaRenauld** [readthedocs/sphinx_rtd_theme#1250]
### Problem

My read-the-docs, which worked fine and still works when builded directly from github, now has a broken layout when building locally on my new environment. I now have:
- python 3.9
- sphinx_rtd_theme 1.0.0
- docutils 0.17
- sphinx 4.0 (I also tried 4.1)
(i.e. all are supported dependencies)

The page builds but the layout is broken. I found that if I remove the additional my_style.css from the conf.py page, where I was modifying the page width (`.wy-nav-content {    max-width: 100%;}`), such as suggested on many forums, it works again. Which means that I need a new solution to change the max width. 

Thanks!!

### Reproducible Project

https://scil-documentation.readthedocs.io/

#### Error Logs/Results

![image](https://user-images.githubusercontent.com/4967417/139876824-2ed83ad0-f2cd-478a-9036-23f17e0ecdf3.png)

**Comment by nienn** [comment]
The link you posted for the reproducible project has the `my_style.css` file with the `.wy-nav-content { max-width: 100% }` styles applied to the page and seems to work fine.

Is it only locally that you are experiencing the broken layout? Could that be a cache problem?

**Comment by EmmaRenauld** [comment]
It was indeed only locally broken, and you fix did the trick. I'm not sure why it was working online. Thanks!
