### ISSUE TITLE
Customizing theme for enterprise use

### ISSUE THREAD

**Issue by kapooramit** [readthedocs/sphinx_rtd_theme#1264]
Hi @snide

I am editing the theme to create a custom theme for my organization to match my organization's requirements so that we can use it to create API docs for our customers. I have two questions: 

1. Can I add my organization and/or my name in the existing License file at the top without touching rest of it including and following your name and rest of the text statement?
2. Can I change the footer Copyright statement as well to go with our organization branding guidelines?

I think the answer to both is yes but I cannot take a chance so I am asking. Thank you for the awesome theme!

-Amit

**Comment by snide** [comment]
Yes. Merry Christmas!

**Comment by kapooramit** [comment]
Wow! Thank you so much for confirming and responding so quickly! Merry Christmas and a Happy New Year to you too! :-)

**Comment by kapooramit** [comment]
@snide : One question that I could think of that might come my way soon - can I rename the theme as well along with the two changes I mentioned above?
