### ISSUE TITLE
While setting up extension mytheme: extension 'mytheme' has no setup() function; is it really a Sphinx extension module?

### ISSUE THREAD

**Issue by kapooramit** [readthedocs/sphinx_rtd_theme#1272]
I have customized the theme, renamed it, and installed it. Now when I run 'make html'  , I get the following error:
````
 Generating Sphinx Documentation
Running Sphinx v4.3.1
loading translations [en]... done
loading pickled environment... done
WARNING: while setting up extension mytheme: extension 'mytheme' has no setup() function; is it really a Sphinx extension module?

Theme error:
no theme named 'mytheme' found (missing theme.conf?)
````
What am I missing? Maybe someone can share what all places do I need to change/replace the sphinx_rtd_theme string?

**Comment by agjohnson** [comment]
This doesn't look to be an issue with our theme, it seems more related to your customizations. The fact that Sphinx is not finding your theme is likely the underlying issue. Core team only supports our own theme, and doesn't seem to be much community guidance here. Consider opening an issue on Stackoverflow if you are still having trouble.
