### ISSUE TITLE
The toctree displayed for index on the left and on the index.html

### ISSUE THREAD

**Issue by kayhayen** [readthedocs/sphinx_rtd_theme#1276]
### Problem

The toctree on the index page is in the menu as it should, but also in the page where I don't want it.

### Reproducible Project

I am using the RTD theme self hosted on http://nuitka.net created by code hosted at https://github.com/Nuitka/Nuitka-website and the problem can be seen in the index.html which gets a rather large amount of content from the toctree directive.

#### Error Logs/Results

The resulting toctree is large, such that merely hiding it, is not enough. The root document is 120k where a similar document that is not index.html is only 20k in comparison, because the menu can be small for unrelated documents. Google tells me on mobile it therefore is 2.6s to render despite its relatively harmless content (text outside of log) otherwise.

#### Expected Results

I tried to hide the toctree, but then they do not display in the menu as well. There seems to be no way to have it in the menu, but not locally.

### Environment Info

I am working with Pipenv documented versions, Python 3.9, Sphinx v4.3.2, and rtd 1.0.0

Please advise, maybe I have to change something in the templating. I only saw `{{body}}` there. So I fear, it's something Sphinx does and the theme has no control over it. I would be willing to overload templates if that helps.

**Comment by nienn** [comment]
Hi @kayhayen, in your [conf.py](https://github.com/Nuitka/Nuitka-website/blob/33df40edadf06d909de8d6567c5cf772b74d9c0c/doc/conf.py#L146) file you have the option `includehidden` set to `false`. Please try setting it to `true` and see if that solves the problem.

**Comment by kayhayen** [comment]
It only added the one hidden entry to the menu bar. But I think I get where you are pointing to. I should make them all hidden, and instead of hidden for the pages I do not want in the menu bar, I should use `:orphan:` meta data for those. I will try that, and that's likely to work then, since the only hidden one is not part of the document body.

**Comment by kayhayen** [comment]
Yes, that works indeed. The documentation of both Sphinx and RTD doesn't explain this well, but I got it now. Thanks for your reaction @nienn

**Comment by nienn** [comment]
👍  Great! Glad that worked. Please let me know if you need more help.
