### ISSUE TITLE
Drop Sphinx compatibility to < 6

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#1282]
~Sphinx 5.0~ Sphinx 6 is dropping jQuery support, which we have historically piggybacked off of. Removing jQuery support here (and in RTD) is totally valid and a good goal as well, we're not doing anything with jQuery that we couldn't do by hand. But to start, we should squeak out a release that pins our Sphinx < 5 so we don't risk a theme version that doesn't have jQuery underneath.

We can discuss a few options for removing jQuery, including porting code and async loading of jQuery when it doesn't exist through webpack (we use this feature in our new site templates).

Related #1253

**Comment by astrojuanlu** [comment]
> But to start, we should squeak out a release that pins our Sphinx < 5 so we don't risk a theme version that doesn't have jQuery underneath.

Indeed!

**Comment by felixoi** [comment]
As Sphinx 5.0 is released, do I read this correct that currently rtd_theme is not compatible with it?
