### ISSUE TITLE
Abandon `master` branch and make `main` default

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/sphinx_rtd_theme#1308]
There are known instances of projects that install directly from the master branch, rather than a PyPi package.

We can make the move to the new conventional `main` branch count by also dropping support of directly installing from `master` branch (or any other branch for that matter).

## Benefits

1. Assets should not be maintained and built directly in the repo
2. Breaking changes for backwards Sphinx compatibility are coming and we do not know how this might affect very old deployments that rely on `master`.

## Practical Proposal

* Keep `master` but stop updating it
* Freeze `master` after the 1.1.x release and set new default branch to `main`
* Retarget any open PRs after 1.1.x release.
* Start building non-tracked assets upon release, but do not change the build method for now (a reproducible one!). Write it down, preferably as a GitHub Action or similar.

## Fallout / collateral

* It's possible to install from the "default" branch and this will not work, find a way to make it break by design. https://github.com/readthedocs/sphinx_rtd_theme/issues/1221#issuecomment-961522211

Fixes #1085 #1221 #379

Related: #1086

**Comment by agjohnson** [comment]
Might be better to move this issue to https://github.com/readthedocs/sphinx_rtd_theme/issues/1221

**Comment by agjohnson** [comment]
Let's continue discussion on #1221. The largest change from #1221 is how we handle installations directly pointing to our repository. We probably don't want to make the jump to `main` prematurely, if retaining `master` provides a way to effectively archive builds for users that are currently pip installing directly from our repo.

**Comment by benjaoming** [comment]
> We probably don't want to make the jump to main prematurely, if retaining master provides a way to effectively archive builds for users that are currently pip installing directly from our repo.

@agjohnson that was certainly not the intention, hence the word "abandon", not "delete"

**Comment by agjohnson** [comment]
Yeah, understood, I wasn't describing deleting either as well.
