### ISSUE TITLE
Release 1.1 with upper bounds on dependencies

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#1309]
The goal is to get 1.1 out that doesn't break when Sphinx 6 or docutils are released. The existing 1.1 milestone has a lot of extra bugs/bug fixes, which would be best off in a 1.2 release.

**Comment by agjohnson** [comment]
I've repaired a number of issues building at CI. #1316 has working CI builds.

**Comment by benjaoming** [comment]
I don't quite understand this issue, can you elaborate @agjohnson ? :pray:

**Comment by agjohnson** [comment]
Pinged in chat. The note here is that we might delay a release if we continue going through the 1.1 milestone bugfixes. We'll want to do some testing on latest Sphinx and docutils, and ensure those pins do not introduce any display changes, build errors, or otherwise break the dependency chain for users.

**Comment by benjaoming** [comment]
By pinning, do you mean introducing upper bounds `<` on more of the transient dependencies, i.e. not `==`?

**Comment by agjohnson** [comment]
The current specifier for Sphinx is https://github.com/readthedocs/sphinx_rtd_theme/blob/master/setup.cfg#L35, so really wide open. We'll want to tune that down to at least avoid bringing in Sphinx 6 and docutils versions we can't support.

**Comment by benjaoming** [comment]
Ah okay, then I get you, I understanding "pinning" as `==`

**Comment by agjohnson** [comment]
Ah I see, yeah we use that term fairly loosely I suppose

**Comment by benjaoming** [comment]
_Not sure if correct language_

**Comment by benjaoming** [comment]
@agjohnson these are our current direct dependencies:

https://github.com/readthedocs/sphinx_rtd_theme/blob/e741681526e37bf8069c8864bbee9a5d754bc991/setup.cfg#L34-L37

small note: we'll bump docutils to 0.18 and maybe also to 0.19

Should we investigate transitive dependencies and potential of putting upper bounds of some of those or can this issue be considered solved?

**Comment by agjohnson** [comment]
We'll use this issue to track an actual release going out. We can reassign this issue while you're away, but the actual work behind the release is indeed looking close.

**Comment by agjohnson** [comment]
> these are our current direct dependencies:

@benjaoming To clarify, those are the current dependencies specified in `master`. Release `0.5.2` still has `docutils<0.17`, and no upper bounds on `Sphinx`:

https://github.com/readthedocs/sphinx_rtd_theme/blob/0.5.2/setup.py#L117-L120

Release 1.1 should aim for finally representing our current reality, which is that `Sphinx<6.0` and `docutils<0.18` are supported, but these fixes are just all unreleased currently.

The next release can focus more on fixing issues with docutils 0.18 and 0.19, etc. There will be work to fix the display bugs with docutils 0.18 footnotes/citations.

For that, I think the following issues are on the wrong milestone and should be `1.2` or `2.0`:

- https://github.com/readthedocs/sphinx_rtd_theme/issues/1302
- https://github.com/readthedocs/sphinx_rtd_theme/issues/1323
- https://github.com/readthedocs/sphinx_rtd_theme/pull/1336
- https://github.com/readthedocs/sphinx_rtd_theme/pull/1304

**Comment by agjohnson** [comment]
> these are our current direct dependencies:

@benjaoming To clarify, those are the current dependencies specified in `master`. Release `1.0.0` has no upper bounds on `Sphinx`:

https://github.com/readthedocs/sphinx_rtd_theme/blob/1.0.0/setup.py#L120-L123

The aim of 1.1 release was to get out a fairly minor release that just pins dependencies so that we have more protection from Sphinx and docutils releases.

The next release, 1.2 or 2.0, can focus more on fixing issues with docutils 0.18 and 0.19, etc. We have more work to do to resolve display bugs with docutils 0.18 footnotes/citations.

For that, I think the following issues are on the wrong milestone and should be `1.2`:

- https://github.com/readthedocs/sphinx_rtd_theme/issues/1302
- https://github.com/readthedocs/sphinx_rtd_theme/issues/1323
- https://github.com/readthedocs/sphinx_rtd_theme/pull/1336
- https://github.com/readthedocs/sphinx_rtd_theme/pull/1304

**Comment by benjaoming** [comment]
There are a lot of people asking for docutils 0.18 and I would feel okay that the footnotes have a visual regression for docutils 0.18 that can be fixed during QA of 1.1b1 (I'll add the first set of styling ASAP).

**Comment by benjaoming** [comment]
Bumping the docutils 0.18 to the 1.2 milestone regardless, the 1.1 release can ship and be QA'd without it.

**Comment by agjohnson** [comment]
I do agree on adding a docutils 0.18 and 0.19 fixes, but this does seem like a good point to split out two separate, smaller releases.

Historically, we've been bad about creeping scope on theme releases and this has delayed fixes from going out for users. One of the conclusions we came to was that we should cut _smaller_ releases _more frequently_. This does require being mindful of the true amount of work attached to each milestone, but users benefit from faster fixes, and we benefit from lower potential for breakage on each release.

**Comment by benjaoming** [comment]
I agree, I was treating the 1.2 milestone as a milestone that wasn't actually in the roadmap. But now it is so it makes it easier to avoid the 1.1 scope creep. Also, it might be useful for some projects to choose between 1.1 (`docutils<0.18`) and 1.2 (`docutils<0.19`).

**Comment by ericholscher** [comment]
A pre-release of 1.1.0 is out!

**Comment by benjaoming** [comment]
Will close this once we see that https://github.com/readthedocs/readthedocs.org/pull/9701 works

**Comment by benjaoming** [comment]
The new release is announced and works for the first builds tested.
