### ISSUE TITLE
docutils 0.18 support issues

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/sphinx_rtd_theme#1322]
Handling these issues separately from the fix committed in #1304 

> In Fedora, I manually relaxed the docutils version requirement and built the package as RPM against the version 0.18.1 & Sphinx 5.0.2.
> Please note, we patch our package (especially fonts), so my findings may not be a complete list.
> I compared the rendered package documentation to the one build on docutils 0.17 and Sphinx 4.5.0 and found those issues:
> 
> 1) Field list is rendered with two colons instead of one:
> ![image](https://user-images.githubusercontent.com/33810531/179508910-1abdf4ab-2f33-42fd-9fc4-fec1d27b7b65.png)
> 
> 2) Footnotes and citations not visually rendered, functionality (references) without changes:
> ![image](https://user-images.githubusercontent.com/33810531/179509123-a7c9ccf6-605e-4b57-9d54-b8bd177d2c86.png)

_Originally posted by @befeleme in https://github.com/readthedocs/sphinx_rtd_theme/issues/1302#issuecomment-1187254358_

**Comment by agjohnson** [comment]
I've raised issues with the visual impact of the suggested PR and I'm happy to jump in and get a proper fix in place for next release.

**Comment by benjaoming** [comment]
I found more similar work in https://github.com/readthedocs/blog/pull/188 so I'm happy to continue looking at improving the fix :+1:

**Comment by agjohnson** [comment]
I've put up the fix I was looking for, which is using the same CSS grid pattern that we've been using for the HTML5 writer already. There's one more issue I'd like to resolve, it's a new one with too many backrefs. PR is at #1381
