### ISSUE TITLE
Theme build fails

### ISSUE THREAD

**Issue by pseusys** [readthedocs/sphinx_rtd_theme#1341]
### Problem

I've cloned the theme and it's not building (`npm install` fails).  
I think this might be result of legacy `wyrm` package, depending on old versions of `bourbon` and `bourbon-neat`.

#### Error Logs/Results

I don't think logs are very informative in this case.
[debug.log](https://github.com/readthedocs/sphinx_rtd_theme/files/9557520/2022-09-13T13_03_24_766Z-debug-0.log)

### Environment Info

- Python Version: python2 and python3

**Comment by pseusys** [comment]
Thanks for your reply!
I've also found [this](https://github.com/Lightning-AI/lightning_sphinx_theme) repo, containing SASS styles (for another theme) that can be built with latest npm package versions.

**Comment by benjaoming** [comment]
Yes, the issues of legacy in this repo are - as you pointed out - related to the use of wyrm. We intend to follow a roadmap to get in a better position to make calls on that: https://sphinx-rtd-theme.readthedocs.io/en/stable/development.html#roadmap

LMK if the above works for you and if you have any inputs for how you prefer to work with Docker, they are most welcomed in #1337

**Comment by benjaoming** [comment]
Closing this, as the build does work in Docker. Don't think there's much that can be fixed or upgraded in the JS stack.

The error in debug.log does make a bit of sense and isn't actually related to JS.. seems like libsass isn't compiling correctly.
