### ISSUE TITLE
Offset of "Search docs" placeholder

### ISSUE THREAD

**Issue by Lukas1811** [readthedocs/sphinx_rtd_theme#1342]
### Problem

The placeholder text in the search bar is a little bit of (about 1px), I think this comes from the use of the 80% font size rule.
When you change the padding-top of the input field to 7 instead of 6 it should be centered again.

### Reproducible Project

It's in every sphinx documentation using the theme.

#### Error Logs/Results

None

#### Expected Results

I expect to not beeing triggered XD

I know it's a little petty but, greetings from my OCD

**Comment by humitos** [comment]
I'm not sure to understand this issue. Are you talking about this input? If that's the case, can you expand on this isssue?

![Screenshot_2024-08-12_17-21-33](https://github.com/user-attachments/assets/d347a941-c3c5-462e-bb9a-bb620242594a)


Feel free to re-open if it's still valid 🙏🏼
