### ISSUE TITLE
Update release process

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/sphinx_rtd_theme#1362]
Proposal to:

1) Update the release process to always release from `master`
2) Add a section "verification" of steps that can be done to verify a local package
3) Dockerize the entire release process to have containerized and "reproducible" environments -- this means to address some of the proposed requirements in #1337 to also include the release preparation

**Comment by benjaoming** [comment]
Also, this issue is entirely because I made a couple of mistakes in the pre-release process for 1.1.0 and I can hash out steps to ensure that doesn't happen again :innocent:

**Comment by humitos** [comment]
We have this process documented at https://sphinx-rtd-theme.readthedocs.io/en/stable/contributing.html#releasing-the-theme
