### ISSUE TITLE
1.1.0 caused ugly looking internal references

### ISSUE THREAD

**Issue by dolfinus** [readthedocs/sphinx_rtd_theme#1368]
### Problem

I have a page with 2 tables - list of classes on the page, and list of methods in each class.

1.0.0 produced tables which looks fine:
![изображение](https://user-images.githubusercontent.com/4661021/199957134-9eaba88f-c1ec-4dd2-84df-e9baae6f1caf.png)
![изображение](https://user-images.githubusercontent.com/4661021/199957183-b67581c3-9144-4db1-850d-007ad929daa6.png)

But after upgrading to 1.1.0 internal links to classes and methods started to overflow:
![изображение](https://user-images.githubusercontent.com/4661021/199957343-caa7a941-03f6-4829-b78b-0c2b9dfe9d96.png)
![изображение](https://user-images.githubusercontent.com/4661021/199957397-8e4aaf1c-4cd0-4798-86e6-9392dc7b8856.png)

This is caused by #1193, after disabling CSS rule `overflow-wrap: anywhere` table appearance is normal again.

Same issue is observed in other projects, like https://github.com/PlasmaPy/PlasmaPy/issues/1784. To restore previous behavior, users either lock there version to `<1.1.0`, or uses some hacks like https://github.com/PlasmaPy/PlasmaPy/pull/1785.

### Reproducible Project

Sorry, my repo is not public.

Documentation is generated using `autosummary` and `autoclass` plugins.

```rst
.. currentmodule:: onetl.connection.db_connection.teradata

.. autosummary::

    Teradata
    Teradata.ReadOptions
    Teradata.WriteOptions
    Teradata.JDBCOptions

.. autoclass:: Teradata
    :members: check, sql, fetch, execute, close
```

Generated `href`s and other attributes for `<a>` tags are quite long:
```html
<tr class="row-odd">
  <td>
    <p><a class="reference internal" href="#onetl.connection.db_connection.teradata.Teradata"
        title="onetl.connection.db_connection.teradata.Teradata"><code
          class="xref py py-obj docutils literal notranslate"><span class="pre">Teradata</span></code></a></p>
  </td>
  <td>
    <p>Class for Teradata JDBC connection.</p>
  </td>
</tr>
```

```html
<tr class="row-even">
  <td>
    <p><a class="reference internal" href="#onetl.connection.db_connection.teradata.Teradata.execute"
        title="onetl.connection.db_connection.teradata.Teradata.execute"><code
          class="xref py py-obj docutils literal notranslate"><span
            class="pre">execute</span></code></a>(statement[,&nbsp;options])</p>
  </td>
  <td>
    <p><strong>Immediately</strong> execute DDL, DML or procedure/function <strong>on Spark driver</strong>.</p>
  </td>
</tr>
```

But `<a>` tag body contains only short class name and method signature, not the full name, so it should not cause overflow.

#### Error Logs/Results

None

#### Expected Results

Change from #1193 should be applied to only `<a>` tag, but not nested `<code>` and `<span>` tags.

### Environment Info

- Python Version: 3.7.8
- Sphinx Version: 5.3.0
- RTD Theme Version: 1.1.0

**Comment by dolfinus** [comment]
This should fix the issue: https://github.com/readthedocs/sphinx_rtd_theme/pull/1369

**Comment by agjohnson** [comment]
Thanks for the fix, @dolfinus! It does seem to fix the bug you noticed. I've put out a bugfix release 1.1.1: https://pypi.org/project/sphinx-rtd-theme/1.1.1/

We can close this issue, but report back if your docs are still looking incorrect with the new release.

**Comment by dolfinus** [comment]
The issue is fixed after upgrading to 1.1.1, thanks!

**Comment by dolfinus** [comment]
Is it okay that 1.1.1 release is not in releases list on Github?

**Comment by agjohnson** [comment]
We don't use releases on GitHub, we only normally tag commits.

**Comment by benjaoming** [comment]
Out of habit, I used GitHub releases for 1.1.0 but I think @agjohnson prefers that we don't.. which is fine, all the info is on PyPi and we have a badge in the README :+1:
