### ISSUE TITLE
Properties of a class are visually mixed in sphinx 4+ version (html)

### ISSUE THREAD

**Issue by borodii** [readthedocs/sphinx_rtd_theme#1378]
Hi! I faced an annoying visual problem with sphinx-apidoc when generation html documentation with sphinx-rtd-theme

Starting from 4.0.0.b1 and later, it seems that sphinx is trying to fit as many items into the available body width as possible. It creates a visual noise (please see 400b1.png ![400b1](https://user-images.githubusercontent.com/95607630/201906760-47d8d641-8ae7-4d4c-9f30-240850136861.png))

in 3.5.4 it was OK, there is always 1 property in the row (please see 354.png ![354](https://user-images.githubusercontent.com/95607630/201906765-a1382db3-e0a9-4a1a-9fff-a677d648b1fb.png))

No local changes, it's definitely some changes done with default settings for 4.0.0 or for the sphinx-rtd-theme
Though I cannot find which one, despite studying the changelog or guessing.

Could anyone please help how can I restore the initial behavior to have 1 property in a row and don't let sphinx take all the "free" width with other properties?

**Comment by benjaoming** [comment]
What programming language is this?

I'm not seeing any issues with the theme's demo here: https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/api.html

Could you try a more recent version 5.x of Sphinx to see if this issue goes away?
