### ISSUE TITLE
sphinx_rdt_theme for hyperlink heading to act as drop down function

### ISSUE THREAD

**Issue by jayramr** [readthedocs/sphinx_rtd_theme#1382]
Hi,

I'm looking a way to display the text to appear down from a hyperlink. In the current page I need to include links to different pages, website links, link to text to same page once the link is clicked it will expand down.

I'm able to achieve the same using below code using sphinx-panels.

```
* `Web Interface <https://example.com>`__
.. dropdown:: * Software Stack

 Line1 
 Line2 
 .. code:: bash
    $ some commands  
```

Here I'm actually looking the hyperlink should be in same format. But in my code, you can the second one is a dropdown link. This looks my overall looks of that page is not perfect.

Please share your views how can i use the hyperlink to display the text down.

Thanks
Jay

**Comment by benjaoming** [comment]
@jayramr Hi Jay - can you be more precise about how this is a bug in the theme?

Otherwise, it sounds like you are asking for help to solve your problem, it's better to ask in StackOverflow. Tag your question with `sphinx`: https://stackoverflow.com/questions/tagged/sphinx

**Comment by jayramr** [comment]
Dear @benjaoming this is not a bug, actually I need a help to proceed. 
I already asked in stackoverflow [https://stackoverflow.com/questions/74407058/sphinx-to-display-text-when-click-on-hyperlink](url) , still no  help. 

Please advise
