### ISSUE TITLE
Missing style for :menuselection:

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/sphinx_rtd_theme#1392]
Good start: Use same style as for `:guilabel:`

Even better? Use a distinct but similar variation of `:guilabel:` so it's clear to the reader that they are not identical.

Ref: https://github.com/readthedocs/readthedocs.org/pull/9801#discussion_r1050224197

**Comment by ericholscher** [comment]
Added this to our Q1 roadmap, since it's something we are motivated to get working.
