### ISSUE TITLE
Dependency resolvement leads to wrong formatting of bullet lists

### ISSUE THREAD

**Issue by cissou8** [readthedocs/sphinx_rtd_theme#1398]
### Problem

Bullet lists do not render correctly on readthedocs site.
Problem appeared with Sphinx 6.0.0 release. Most probably same root cause as this one: https://github.com/readthedocs/sphinx_rtd_theme/issues/1396 
From readthedocs CI log, I get the installed versions are:
sphinx 6.0.0
sphinx-rtd-theme 0.5.1
on python 3.8

### Reproducible Project

You can see a bullet list not properly rendered at https://siril.readthedocs.io/en/latest/Sequences.html (list is supposed to be right after the first code block)
![image](https://user-images.githubusercontent.com/65344766/210180425-209d8f04-30f7-4f88-824a-d491484787e0.png)

I've made an experimental branch which pulls sphinx-rtd-theme master and then force reinstall sphinx 6.0.0, it works as expected:
https://siril.readthedocs.io/en/pin_sphinx/Sequences.html
![image](https://user-images.githubusercontent.com/65344766/210180412-bb8359db-78c0-4252-9144-fcdcb59ad26d.png)

The  requirements.txt that does this can be found there: https://gitlab.com/free-astro/siril-doc/-/blob/pin_sphinx/requirements.txt, copied here-below for future reference
```
myst-parser
sphinxcontrib-svg2pdfconverter
cairosvg
sphinx-copybutton
-e git+https://github.com/readthedocs/sphinx_rtd_theme.git#egg=sphinx_rtd_theme
sphinx==6.0.0
```

Forcing 1.2.0rc1 and installing sphinx 6.0.0 breaks the CI (https://readthedocs.org/projects/gess/builds/16095103/)
I believe from what I've read here that support for sphinx 6.0.0 will be added with 1.2.0 stable release, so probably just have to be patient :) . 
I'm just reporting this in case someone loses their bullet lists too and lands here.

### Environment Info

- Python Version: 3.8
- Sphinx Version: 6.0.0
- RTD Theme Version: 0.5.1 (as installed by rtd CI)

**Comment by benjaoming** [comment]
Hi @cissou8 ! I'm going to close this issue as it should be fixed now.

You can use sphinx-rtd-theme with Sphinx 6 by testing it out in this pre-release, feedback is most welcome (also just a quick "it worked :+1: ") as it can help us release the stable version faster. See: https://pypi.org/project/sphinx-rtd-theme/1.2.0rc2/

**Comment by cissou8** [comment]
Hi @benjaoming ,
pinned version to 1.2.0rc2 and got my bullets back, many thanks!
C.
