### ISSUE TITLE
Please add traditional chinese (zh_TW) translations

### ISSUE THREAD

**Issue by jazonshou** [readthedocs/sphinx_rtd_theme#1401]
Title

Thank you

**Comment by benjaoming** [comment]
Hi @jazonshou 

As far as I can tell, this language is already added but no one has translated anything yet:

https://www.transifex.com/readthedocs/sphinx-rtd-theme/language/zh_TW/

If you are a translator and speak traditional Chinese (don't you mean Taiwanese?), you can create an account on Transifex and translate the theme.
