### ISSUE TITLE
Bullets do not render in HTML with Sphinx >= 6.0.0

### ISSUE THREAD

**Issue by jsquyres** [readthedocs/sphinx_rtd_theme#1403]
### Problem

Starting with Sphinx 6.0.0 (up to and including 6.1.2), bullets do not render in HTML.  They render correctly with Sphinx 5.3.0.

### Reproducible Project

Here's a trivial example that shows the issue:

* `index.rst`:

```rst
Hello world
===========

* Bullet 1

* Bullet 2
```

* `conf.py`:

```python
import sphinx_rtd_theme
html_theme = 'sphinx_rtd_theme'
```

Build it with:

```
$ rm -rf _build
$ sphinx-build -M html . _build                                
Running Sphinx v6.1.2
making output directory... done
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                             
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                              
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
$ open _build/html/index.html
```

If you use Sphinx >= 6.0.0, you'll see that there are no bullets next to "Bullet 1" and "Bullet 2".

If you use Sphinx 5.3.0, the bullets render correctly.

#### Error Logs/Results

I'm not sure what files to include here; let me know anything you need me to upload.

#### Expected Results

I expect their to be bullets rendered in HTML for Sphinx >= 6.0.0.

### Environment Info

- Python Version: 3.9.16 (installed via Homebrew on MacOS Ventura 13.1)
- Sphinx Version: >= 6.0.0 (installed via pip)
- RTD Theme Version: 1.1.1 (installed via pip)

**Comment by benjaoming** [comment]
Hi @jsquyres :wave: 

This sounds similar to #1115 

You will need to use the pre-release, `sphinx-rtd-theme==1.2.0rc2`. It won't be chosen unless you explicitly put that version in the requirements.

Please let us know if you have any further issues with the pre-release. We're looking to promote it to a stable release as soon as possible.

**Comment by jsquyres** [comment]
@benjaoming Got it -- thanks!
