### ISSUE TITLE
Sphinx 6: Broken Logos and favicons

### ISSUE THREAD

**Issue by Blendify** [readthedocs/sphinx_rtd_theme#1404]
Sphinx 6 removes the `logo` and `favicon` html template variables.
These have been deprecated since sphinx 4 in favor of `logo_url` and `favicon_url`.

This will need to be resolved before the 1.2.0 release.

**Comment by benjaoming** [comment]
`logo_url` is fixed in https://github.com/readthedocs/sphinx_rtd_theme/pull/978/files

**Comment by benjaoming** [comment]
@Blendify did you ever see a deprecation warning about this change in your projects?

I'm wondering because it's reported that people haven't seen the deprecation warnings: https://github.com/sphinx-doc/sphinx/issues/11062

**Comment by Blendify** [comment]
> @Blendify did you ever see a deprecation warning about this change in your projects?
> 
> I'm wondering because it's reported that people haven't seen the deprecation warnings: [sphinx-doc/sphinx#11062](https://github.com/sphinx-doc/sphinx/issues/11062)

I have never seen any warnings. I only realized when doing some testing for my projects before we upgraded versions.

**Comment by benjaoming** [comment]
I agree btw that this is a high-priority for the 1.2.0 roadmap - stuff breaks if we don't fix it. There's no idea in shipping the theme if logos and favicons disappear.. can't make that a known issue :)
