### ISSUE TITLE
stickysidebar

### ISSUE THREAD

**Issue by gsagnol** [readthedocs/sphinx_rtd_theme#141]
Hi,
would this be possible to add a 'stickysidebar' option, as in the default theme of sphinx (http://sphinx-doc.org/theming.html#builtin-themes), so the sidebar always remains visible when we scroll down the documents ?

Thanks !
Guillaume.

**Comment by DrLulz** [comment]
New to sphinx (v1.3b2), and having some trouble getting this to work.

`html_theme_options = {'sticky_navigation' : True}`

doesn't seem to do it. advice?
