### ISSUE TITLE
navigation_depth in html_theme_options is ignored with Sphinx >=6.0

### ISSUE THREAD

**Issue by akiyks** [readthedocs/sphinx_rtd_theme#1418]
### Problem

I'm testing RTD theme v1.2.0rc3 with Sphinx 6.1.3.
In the sidebar, navigation depth becomes 2 regardless of the setting of navigation_depth in conf.py
I see the same issue with Sphinx >=6.0.0.

RTD theme v1.2.0rc3 with Sphinx 5.3.0 works as expected.

I can't tell whether this is regression in Sphinx >=6.0 or RTD theme needs some adjustment for Sphinx >=6.0.

Can you please look into this?

### Reproducible Project

sphinx_rtd_theme's docs/.

Run "make html" under docs/ and see sidebar's behavior in the generated html.

### Environment Info

- Python Version: Python 3.9.2
- Sphinx Version: 6.1.3 (since 6.0.0)
- RTD Theme Version: v1.2.0rc3

**Comment by akiyks** [comment]
RTD Theme v1.2.0rc4 has resolved this issue.
Closing now.

Thanks!

**Comment by benjaoming** [comment]
Thanks for confirming that it's fixed!

This sounds like a variation of a jQuery issue (#1420 ), whereby SNI blocked loading jQuery on local builds? Were you looking at `file://` in your browser?

**Comment by akiyks** [comment]
> Were you looking at file:// in your browser?

Yes, that's exactly what I was doing!

**Comment by benjaoming** [comment]
Got it! Thanks for helping to resolve the issue fully :100:
