### ISSUE TITLE
Bullet point issue on readthedocs build

### ISSUE THREAD

**Issue by robamu** [readthedocs/sphinx_rtd_theme#1419]
Hi!

### Problem

This might be a duplicate  of https://github.com/readthedocs/sphinx_rtd_theme/issues/1300 or an issue which is related
to how readthedocs.io builds documentation, I am not entirely sure yet.

I have also found  https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-file and https://github.com/readthedocs/sphinx_rtd_theme/issues/1115 but those are just quick guesses.

The readthedocs build of my repository currently has issue rendering bullet points.
The current latest docs can be found here: https://spacepackets.readthedocs.io/en/latest/

The project can be found here: https://github.com/us-irs/spacepackets-py

Building manually with `make html` inside the docs folder will render the bullet points properly.
I will try to find out whether this is a version issue, either with the Sphinx version or the
sphinx_rtd_theme version.

#### Expected Results

Please describe how this should work properly.

### Environment Info

- Python Version: On server: 3.8 , locally 3.10
- Sphinx Version: On server: 6.1.3, local: TBD
- RTD Theme Version: On server: 0.5.1 (but also downloads some older versions for some reason), local: TBD

UPDATE:

This is probably this issue: https://github.com/readthedocs/sphinx_rtd_theme/issues/1115#issuecomment-1373985356 which is explained there quite well for anyone who stumbles upon this.

**Comment by benjaoming** [comment]
You can try to pin something like `sphinx-rtd-theme>=1.2.0rc3,<1.3` - Sphinx 6 and docutils 0.18 is supported here and all known visual regressions have been addressed.

**Comment by benjaoming** [comment]
Thanks for opening and elaborating!

Please LMK if this is fixed through the upgrade :+1: Otherwise, I'll have a look. We're hoping to release 1.2.0 tomorrow, aligning the theme release with a related bug fix on the RTD platform.

**Comment by robamu** [comment]
Hi,

Thanks for the quick answer :+1: 
I actually was a bit impatient, a little bit of more reading and this issue would not have been required.

I solved the issue like you specified by pinning the `sphinx-rtd_theme` version to 1.2.0rc3.

More specifically, I have the following section in my `.readthedocs.yaml` now:

```yaml
python:
   version: 3.8
   install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .
```

and then I have a `docs/requirements.txt` file which simply contains `sphinx_rtd_theme==1.2.0rc3`. Now the bullet points render fine. This issue can be closed :-)

**Comment by benjaoming** [comment]
Thanks so much for the feedback @robamu - it's great to know that people are running the release candidate, makes it easier to ship the final release :+1:

**Comment by rhpvorderman** [comment]
Just reporting in. I had the same issue with the disappearing bullet points. Couldn't find the issue on the sphinx repo. Run the alabaster theme, that worked. The issue is with sphinx-rtd-theme 1.1.1. Using sphinx-rtd-theme>=1.2.0rc3,<1.3 solves the issue.
