### ISSUE TITLE
Unable to join project on Transifex

### ISSUE THREAD

**Issue by silopolis** [readthedocs/sphinx_rtd_theme#1422]
Hi,

I'm unable to join the project to complete the French translation because when I try, I'm systematically redirected to the readthedocs/readthedocs project, without any clue or error.

Thanks in advance for your support
TY
J

**Comment by benjaoming** [comment]
Hi!

I've approved the join request for `sphinx_rtd_theme`, thanks for joining the French team!

It sounds odd WRT the Transifex redirect... are you maybe already part of the `readthedocs` translation project?

**Comment by silopolis** [comment]
Le mer. 25 janv. 2023 à 12:26, Benjamin Balder Bach <
***@***.***> a écrit :

> I've approved the join request for sphinx_rtd_theme, thanks for joining
> the French team!
>
Thank you, my pleasure! :)

It sounds odd WRT the Transifex redirect... are you maybe already part of
> the readthedocs translation project?
>
Most probably as I just finished French translation of it ;)

TY
J
