### ISSUE TITLE
Improve styling and responsive design

### ISSUE THREAD

**Issue by GergelyKalmar** [readthedocs/sphinx_rtd_theme#1428]
### Problem

There are multiple issues with the current theme style file:

- The monospace font is specified as a list of system fonts, unlike the body text, where the fonts are bundled with the theme. It is possible to override this behavior via a custom Sphinx style file, but it is relatively complicated because the additional fonts also need to be installed and picked up during build time, also, a bunch of elements do not use the right font family by default (see an override here: https://github.com/logikal-io/logikal-docs/blob/main/logikal_docs/static/css/logikal_docs.css#L4-L35). Using something like Roboto Mono would go well with the current text fonts. Issue https://github.com/readthedocs/sphinx_rtd_theme/issues/1295 is also related to this point.
- Long monospace text snippets and class/function descriptions can make the page width go out of the viewport in mobile because the wrapping is wrongly configured (override here: https://github.com/logikal-io/logikal-docs/blob/main/logikal_docs/static/css/logikal_docs.css#L64-L71, example here: https://docs.logikal.io/stormware/1.0.0/auth.html and here: https://docs.logikal.io/stormware/1.0.0/connectors.html). Issue https://github.com/readthedocs/sphinx_rtd_theme/issues/1347 is also related ("content wider than screen" point).
- The default background is slightly off-white, which makes displaying plots with white backgrounds look odd. It is also difficult to override the background color in the theme (overrides here: https://github.com/logikal-io/logikal-docs/blob/main/logikal_docs/static/css/logikal_docs.css#L73-L85), it would be much better if we could just override a few CSS variables instead of the current fragile approach.
- The responsive design breakpoints are off, the sidebar covers a lot of space between 768px and 1100px. An improved approach can be seen here: https://github.com/logikal-io/logikal-docs/blob/main/logikal_docs/static/css/logikal_docs.css#L146-L194. This override makes the sidebar width more consistent and maximizes the space for the content, which is the most important part. This is especially important on modern high-DPI mobile screens. The issue can be reproduced on this page: https://docs.logikal.io/mindlab/1.0.0/ (try viewing it on mobile around 780px+).

### Reproducible Project

Many of the issues can be seen in the MindLab (https://docs.logikal.io/mindlab/1.0.0/) and Stormware (https://docs.logikal.io/stormware/1.0.0/) documentation pages. The patches/overrides are applied through https://github.com/logikal-io/logikal-docs, but this approach is quite fragile. It would be much better to incorporate the overrides upstream.

**Comment by benjaoming** [comment]
Hi @GergelyKalmar :wave: 

Thanks for describing your issues. To make each item actionable and to have a simpler communication, would you mind opening up one issue per item?

Also, in case you haven't seen - this project has a roadmap: https://sphinx-rtd-theme.readthedocs.io/en/stable/development.html#roadmap

**Comment by benjaoming** [comment]
Awesome, thanks :100:
