### ISSUE TITLE
[UI improvement] - Enable Dark theme toggle

### ISSUE THREAD

**Issue by swastkk** [readthedocs/sphinx_rtd_theme#1440]
It's the best theme for the documentation, but if we can include the dark theme in it too like having a toggle button for the theme change.
Signed-off-by- swastik <swastkk@gmail.com>

**Comment by benjaoming** [comment]
Thanks for taking the time to open an issue. It is - however - a duplicate of this issue: https://github.com/readthedocs/sphinx_rtd_theme/issues/224

So I'm going to close this one.
