### ISSUE TITLE
Recommended dependency version pinning should use strictly less-than not less-than-or-equal

### ISSUE THREAD

**Issue by markbourne** [readthedocs/sphinx_rtd_theme#1447]
In the "Roadmap" section of sphinx_rtd_theme/docs/development.rst, it is recommended that dependencies on sphinx_rtd_theme should be pinned to a version below the next major version, with the example given:
```console
$ pip install "sphinx_rtd_theme<=2.0.0"
```

This would allow version 2.0.0 to be installed, but that may contain breaking changes for a project currently using version 1.x.  I think this should use `<` rather than `<=`.

Even better may be e.g. `~=1.0` (or `~=1.2`), since earlier versions may not be compatible with code targetting 1.x either (while later minor versions should be OK).

**Comment by benjaoming** [comment]
That definitely sounds like a mistake. @markbourne thanks for flagging this. If you can fix it in a PR, that'd be great :+1:

**Comment by gangstaLok** [comment]
#@@

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by humitos** [comment]
This is done already, https://github.com/readthedocs/sphinx_rtd_theme/blob/main/docs/development.rst?plain=1#L100
