### ISSUE TITLE
jQuery not loaded automatically with sphinxcontrib-jquery 4.0.0

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/sphinx_rtd_theme#1452]
### Symptom

`Uncaught ReferenceError: jQuery is not defined`

### Issue

Sphinx signal `config-inited` has probably already been called when we try to add a hook.

### Fixed by

https://github.com/readthedocs/sphinx_rtd_theme/pull/1448

### Workaround

The current workaround is to add `sphinxcontrib.jquery` to `extensions` in `conf.py`

**Comment by stsewd** [comment]
A workaround is to add this in your conf.py file.

```python
extensions = [
    "sphinxcontrib.jquery",
]
```

And there is no need to install the dependency, since the theme already installs it.

**Comment by benjaoming** [comment]
@stsewd it was already there, so I was confused if you were writing it differently :)

**Comment by maxgerhardt** [comment]
Also just hit this error and https://github.com/readthedocs/sphinx_rtd_theme/issues/1452#issuecomment-1490504991 solved the issue.

**Comment by EwoutH** [comment]
With this issue fixed, could a new release be tagged to get it into production?

**Comment by benjaoming** [comment]
This should now be fixed, please upgrade to version 1.2.1 :rocket: 

Feedback appreciated :pray:

**Comment by richardsheridan** [comment]
@benjaoming I still needed the workaround even with 1.2.1: https://readthedocs.org/projects/trio-parallel/builds/20906394/. Is there a way to get RTD to serve old builds of pull requests so I can show you easily?

**Comment by benjaoming** [comment]
@richardsheridan could you try the old workaround of adding the theme to your `extensions` config value?

```
extensions = [
    # ...
    "sphinxcontrib.jquery",
]
```

Your Python dependencies look fine. I'm not quite sure what the issue could be.

**Comment by benjaoming** [comment]
Ah, maybe you need to remove this part from your conf.py:

```

# We have to set this ourselves, not only because it's useful for local
# testing, but also because if we don't then RTD will throw away our
# html_theme_options.
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
```

**Comment by mikemhenry** [comment]
@benjaoming this bit:

```
# We have to set this ourselves, not only because it's useful for local
# testing, but also because if we don't then RTD will throw away our
# html_theme_options.
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
```

Seems to be copy and pasted all over the place, can you comment on the ramifications of removing it?  I was able to fix this issue by adding 

```
extensions = [
    # ...
    "sphinxcontrib.jquery",
]
```

as you suggested, but it doesn't seem as clean is removing `html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]`

Thanks!
