### ISSUE TITLE
How can I get modal open for search in this theme.

### ISSUE THREAD

**Issue by rahulsrivastava1** [readthedocs/sphinx_rtd_theme#1460]
I have hosted my sphinx_rtd_theme on the Azure app service.

I am attaching the below picture for reference.

![image](https://user-images.githubusercontent.com/54400720/234823603-b583bf28-ea73-43d6-ada9-34f482b19109.png)

**Comment by benjaoming** [comment]
Hi @rahulsrivastava1 

I think you are asking for support. But your question should also be directed more broadly at documentation hosting. sphinx-rtd-theme is a theme for the Sphinx documentation tool, not a piece of software that can manage login flows.

The modal search you are looking at is made for Read the Docs. The whole search backend is hosted on Read the Docs. So there is unfortunately not a quick way to port it to another platform.
