### ISSUE TITLE
Theme error: UndefinedError("'style' is undefined")

### ISSUE THREAD

**Issue by kuripart** [readthedocs/sphinx_rtd_theme#1465]
### Problem

Getting following error when building  a Sphinx project:

```
#14 2.108 Theme error:
#14 2.108 An error happened in rendering the page about.
#14 2.108 Reason: UndefinedError("'style' is undefined")
```

`conf.py` includes the following:

```
# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
```
Setting `html_style` doesn't fix the issue as well.

### Reproducible Project

Please give a link to a public reproducible project or provide an example of the Restructured Text that gives an issue.

```rst
Place RST code here (if any).
```

#### Error Logs/Results

#14 2.108 Theme error:
#14 2.108 An error happened in rendering the page about.
#14 2.108 Reason: UndefinedError("'style' is undefined")

#### Expected Results

Setting any other `html_theme` eg: 'bizstyle' works as expected.

### Environment Info

- Python Version: 3.9
- Sphinx Version: 7.0.0
- RTD Theme Version: 1.2.0

Happy to share the Dockerfile and Pipifile setting if the info provided is not enough.

**Comment by dvzrv** [comment]
Hi! I am running into the same issue trying to build libcamera's documentation on Arch Linux.
This is with sphinx 7.0.0 and sphinx_rtd_theme 1.2.0 on Python 3.11.

**Comment by benjaoming** [comment]
Hi! Thanks for stopping by and reporting this!

Do you have an open source repo that produces this error?

There's no variables or properties in the theme's Python code called `style`, so I wondered if it could be related to Jinja2 template code and found this:

https://github.com/readthedocs/sphinx_rtd_theme/blob/03a86b803cf7cf281748ef94345ba7c35953952a/sphinx_rtd_theme/layout.html#L27-L30

As you can see, this code is guarded to only be used on old versions of Sphinx. But could the variable substitution still be causing the error?

**Comment by benjaoming** [comment]
Thanks! I'm wondering why some Sphinx 7 builds work fine. For instance, this build doesn't produce the error:

https://readthedocs.org/projects/test-builds/builds/20357244/

**Comment by dvzrv** [comment]
It turned out to be *not* sphinx_rtd_theme related (just the use of a removed keyword). Sorry for the noise!

**Comment by benjaoming** [comment]
Thanks for sharing @dvzrv :+1:

**Comment by ain-soph** [comment]
@benjaoming @dvzrv Hi, sorry for disturbing! I see there are still `style` (instead of `styles[-1]`) used in sphinx-rtd-theme `layout.html`. Is that still working for `sphinx>=7.0.0`?

https://github.com/readthedocs/sphinx_rtd_theme/blob/03a86b803cf7cf281748ef94345ba7c35953952a/sphinx_rtd_theme/layout.html#L28

**Comment by benjaoming** [comment]
@ain-soph most people who ran into this issue were running an old version of sphinx-rtd-theme.

**Comment by ain-soph** [comment]
> @ain-soph most people who ran into this issue were running an old version of sphinx-rtd-theme.

I agree. But it seems in the most up-to-date sphinx-rtd-theme `layout.html`, it's still using `style` variable, which is already deprecated in `sphinx>=7.0`. 

https://github.com/readthedocs/sphinx_rtd_theme/blob/03a86b803cf7cf281748ef94345ba7c35953952a/sphinx_rtd_theme/layout.html#L28

-------------------------------

https://www.sphinx-doc.org/en/master/changes.html

<img width="933" alt="image" src="https://github.com/readthedocs/sphinx_rtd_theme/assets/13214530/d93f7ba7-fc2a-4ee8-ab84-2371867e4f3c">

**Comment by benjaoming** [comment]
@ain-soph It seems to work fine with Sphinx 7, you can see the full context of the line you are quoting here:

https://github.com/readthedocs/sphinx_rtd_theme/issues/1465#issuecomment-1531262630

**Comment by ain-soph** [comment]
Oops... I didn't even notice this if condition. Quite silly I am! 😓 Thanks for your time!

**Comment by benjaoming** [comment]
No worries, these issues are pretty complex to juggle :+1:

**Comment by peterjc** [comment]
For anyone else hitting this after updating to Sphinx 7, make sure to also update the theme.

Working (old sphinx, old theme):

```
$ mamba list | grep sphinx
sphinx                    6.2.1              pyhd8ed1ab_0    conda-forge
sphinx_rtd_theme          0.4.3              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
```

Failing (new sphinx, old theme):

```
$ mamba list | grep sphinx
sphinx                    7.0.1              pyhd8ed1ab_0    conda-forge
sphinx_rtd_theme          0.4.3              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
```

Working (both sphinx and theme up to date):

```
$ mamba list | grep sphinx
sphinx                    6.2.1              pyhd8ed1ab_0    conda-forge
sphinx_rtd_theme          1.2.2              pyha770c72_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jquery      4.1                pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
```

**Comment by Kartstig** [comment]
I also encountered this as I didn't have some of my dependencies constrained and things upgraded into a failing state. I was able to use the last combination provided by @peterjc to get things working again.

Thanks!

**Comment by bartvstratum** [comment]
I'm  again running into this issue, with both `sphinx` and `sphinx-rtd-theme` up-to-date:

```
(venv) [bart@manjaro microhh_readthedocs]$ pip install --upgrade sphinx-rtd-theme sphinx
Requirement already satisfied: sphinx-rtd-theme in /home/bart/venv/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: sphinx in /home/bart/venv/lib/python3.12/site-packages (8.1.3)
```

**Comment by humitos** [comment]
I got the same error when using typlog theme in https://app.readthedocs.org/projects/test-builds/builds/26841733/

It seems this is not an error related with Read the Docs theme. Maybe it's related to a newer version of Sphinx? 🤔

**Comment by bartvstratum** [comment]
I had to downgrade to `sphinx==6.2.1` to get it working. Don't know sphinx or the theme well enough to judge where the problem is :-)
