### ISSUE TITLE
Menu sidebar not working properly

### ISSUE THREAD

**Issue by stammler** [readthedocs/sphinx_rtd_theme#1468]
We recently created a new project on Read the Docs:

[dustpylib.readthedocs.io](https://dustpylib.readthedocs.io/)

### Problem

On mobile the menu sidebar cannot be expanded. The menu icon is there in the upper left corner, but not working upon click.

On desktop the sidebar menu is there, but the lower section with the version selection and the PDF download cannot be expanded.  
We also noticed that the advertisements are not shown, which should be the case, since we are neither Gold member, nor do we have a business account.

### Reproducible Project

The project files are in this repository:  
[github.com/stammler/dustpylib](https://github.com/stammler/dustpylib/)

#### Error Logs/Results

The project build on Read the Docs passes without errors.

We have an earlier project from which we simply copied the relevant files and structure, which seems to be working fine. The only difference is the time of the last build. That is why we are not sure if it is a user error on our side or if something has changed in the meantime that is causing the problem.  
[simframe.readthedocs.io](https://simframe.readthedocs.io/)  
[github.com/stammler/simframe](https://github.com/stammler/simframe/)

**Comment by benjaoming** [comment]
Hi @stammler :wave: thanks for posting an issue!

It sounds like the original cause is found in #1452 - if you try the described workaround, jQuery should be loaded and your menus should work.

Let me know if that works?

**Comment by stammler** [comment]
Thank you!  
Works like a charm!

**Comment by benjaoming** [comment]
Awesome! We really need to get these bug fixes shipped @agjohnson :)
