### ISSUE TITLE
Decision: Add to 2.x milestone?

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/sphinx_rtd_theme#1470]
We have a lot of issues w/ PRs that represent a solid positive impact - I'd consider them worth releasing in bulk to optimize the number of Q&A iterations.

* #1463 
* #1452 (#1446 + #1448)
* #1426 
* #1450 
* #1417 
* #1375 
* #1336 

Also great candidates:

* #1410 
* #1445 
* #1407 

No PR but very important and low risk:

* #1469
* #1477

**Comment by humitos** [comment]
1.3.0 is already released, so this plan hasn't happened. However, I think there are good candidates to include in the followings 2.x that are coming.
