### ISSUE TITLE
Pls use translations

### ISSUE THREAD

**Issue by misibacsi** [readthedocs/sphinx_rtd_theme#1473]
### Problem

Some translations are 100% finished on Transifex, please use them.

#### Error Logs/Results

Image shows completed and usable translations on Transifex.

![2023-05-13 transifex sphinx-rtd-theme completed languages](https://github.com/readthedocs/sphinx_rtd_theme/assets/11352049/a232064c-a51b-4e80-a1c3-288196aac3a6)

**Comment by benjaoming** [comment]
Hi @misibacsi 

I think this is the same issue as is reported in https://github.com/readthedocs/sphinx_rtd_theme/issues/1469 ?

**Comment by misibacsi** [comment]
It seems yes, I just noticed it is the same topic. 
Can it be solved?

**Comment by benjaoming** [comment]
Yes, I outlined a solution in https://github.com/readthedocs/sphinx_rtd_theme/issues/1469 and mentioned it as a candidate for a new milestone release; but kind of depends on release prioritization (CC: @agjohnson )
