### ISSUE TITLE
Specifying pygments_style in conf.py doesn't work

### ISSUE THREAD

**Issue by rht** [readthedocs/sphinx_rtd_theme#1496]
### Problem

I tried to change the `pygments_style` in my project: https://github.com/projectmesa/mesa/pull/1719. I have waited for #1463 so that I can use Sphinx 7.

However, the build still uses the default `sphinx` `pygments_style`: https://mesa--1719.org.readthedocs.build/en/1719/useful-snippets/snippets.html.

Any idea what went wrong and how to fix it? The project has existed before 2019, and so https://blog.readthedocs.com/python-core-requirements-changed/ doesn't affect it.

**Comment by humitos** [comment]
I just checked this in our code at https://github.com/readthedocs/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/theme.conf#L4 and it seems we are defining it properly as it's said in the Sphinx's documentation at https://www.sphinx-doc.org/en/master/development/html_themes/index.html#theme-configuration-theme-conf

Are you still having this issue?

**Comment by rht** [comment]
Yes, the issue still exists. I have the gruvbox-dark in the config as per https://github.com/projectmesa/mesa/blob/c96ee458ca480c786802587fa4e8d0d997b4de95/docs/conf.py#L106, but the latest main still doesn't show a gruvbox-looking theme in the code: https://mesa.readthedocs.io/en/latest/howto.html.

**Comment by humitos** [comment]
The link you shared, https://mesa.readthedocs.io/en/latest/howto.html, is using PyData Theme, not Read the Docs Sphinx Theme. You can check the docs for PyData Theme at https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/styling.html#configure-pygments-theme

**Comment by rht** [comment]
I see, thank you for the lead. I will try right away.

**Comment by rht** [comment]
It worked! :tada:
