### ISSUE TITLE
Internal all lower-case layer leaks on searches

### ISSUE THREAD

**Issue by jidanni** [readthedocs/sphinx_rtd_theme#1499]
Visiting
https://docs.generic-mapping-tools.org/latest/search.html?q=basemap&check_keywords=yes&area=default#
gives
> -b
> define tick marks, annotations, and labels for basemaps and axes
>
> -j
> select a map projection or coordinate transformation
>
> -r
> define the extent of the map/plot region...

But the real page,
https://docs.generic-mapping-tools.org/latest/cookbook/options.html
shows the truth:
> -B
> Define tick marks, annotations, and labels for basemaps and axes
>
> -J
> Select a map projection or coordinate transformation
>
> -R
> Define the extent of the map/plot region

Indeed, there are also
> -b
> Select binary input and/or output

etc. on the page.

What apparently is happening is some internal all-lowercase comparison
layer, has inadvertently been leaked to public view.

Such internal layers, if any, should be well protected, and only
original-cased forms exposed.

Yes you might say, "What's the big deal? Afraid of a little lower case?"
(Let me know if this is intentional.)

Note that I am simply the lowest end user. All I used was my browser, like grandma clicking things, and never used a documentation package.

**Comment by humitos** [comment]
Is this still an issue? If so, feel free to re-open and expand on it. I'm not sure to understand what's happening and what's the expected behavior.
