### ISSUE TITLE
Inlcuding jquery.js in layout.html

### ISSUE THREAD

**Issue by kapooramit** [readthedocs/sphinx_rtd_theme#1501]
I am trying to follow the instruction to include jquery.js in the layout.html by adding the following lines to the layout.html in the `<head>`. 
````
{%- block scripts %}
    <script src="{{ pathto('_static/jquery.js', resource=True) }}"></script>
    <script src="{{ pathto('_static/underscore.js', resource=True) }}"></script>
    {{ super() }}
{%- endblock %}
````
[https://github.com/sphinx-doc/sphinx/issues/7405]

However, the above code causes the output HTML to throw the **double script block** error. If I remove {{super()}}, I get **$ is not defined**, followed by **jquery is not defined**. 

What am I doing wrong? I want to include jquery and underscore in my custom RTD theme.

**Comment by PhantomRwcwride2Zero** [comment]
Just want to let you know this will not be anymore because trouble found
them and they won't be able to do this ever again because of the bad they
was doing with this you should never take what is not yours because it will
catch up to you every time.

Randy

**Comment by kapooramit** [comment]
@nienn : Can you suggest?

**Comment by humitos** [comment]
> What am I doing wrong? I want to include jquery and underscore in my custom RTD theme.

Read the Docs theme already includes jQuery. You should only include underscore on yours.
