### ISSUE TITLE
Incompatibility with Sphinx 7.2

### ISSUE THREAD

**Issue by picnixz** [readthedocs/sphinx_rtd_theme#1502]
Since Sphinx 7.2, we changed the internal representation of Javascript and CSS files (see https://github.com/sphinx-doc/sphinx/commit/1db8cba3396cbb627d000e9d6ef497e70d769295). 

In particular, the following fails:

https://github.com/readthedocs/sphinx_rtd_theme/blob/b5833585b25358be94918f13c50530e3e9237e7e/sphinx_rtd_theme/layout.html#L35-L35

Note that the above line 

https://github.com/readthedocs/sphinx_rtd_theme/blob/b5833585b25358be94918f13c50530e3e9237e7e/sphinx_rtd_theme/layout.html#L33

works because it uses `css.filename` and not just `css` (which is no more treatable as a string).

(I don't know if other places need to be changed)

cc @humitos

**Comment by humitos** [comment]
Closed by https://github.com/readthedocs/sphinx_rtd_theme/pull/1519
