### ISSUE TITLE
Interaction between nbsphinx and sphinx_copybutton

### ISSUE THREAD

**Issue by neilz** [readthedocs/sphinx_rtd_theme#1553]
### Problem

The theme causes sphinx_copybutton to inject a copy button into the notebook prompt, causing display issues. See
* https://github.com/spatialaudio/nbsphinx/issues/333
* https://github.com/spatialaudio/nbsphinx/issues/376

#### Error Logs/Results

![image](https://github.com/readthedocs/sphinx_rtd_theme/assets/1383059/795876f8-8f05-4d16-b185-a6a4c49852df)

#### Expected Results

There should be no copy button for prompts

**Comment by NovaToro** [comment]
How do I fix it

**Comment by neilz** [comment]
Sorry for the confusion - I fixed this upgrading to the latest in all the extensions and themes
