### ISSUE TITLE
Support for docutils 0.21

### ISSUE THREAD

**Issue by wolfgangwalther** [readthedocs/sphinx_rtd_theme#1557]
Release notes: https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-21-2024-04-09

**Comment by humitos** [comment]
We released a new version [`3.0.0rc1`](https://pypi.org/project/sphinx-rtd-theme/3.0.0rc1/) that adds support for latest docutils versions. Please, give it a try and open an issue for any problem or feedback you want to share with us.
