### ISSUE TITLE
Enhance documentation with info about html_context

### ISSUE THREAD

**Issue by langner** [readthedocs/sphinx_rtd_theme#156]
Recently wanted to investigate the details about html_context for cclib/cclib.github.io#8 and could not find anything. It would be nice to have something in the docs.

**Comment by Blendify** [comment]
This is a duplicate of https://github.com/rtfd/sphinx_rtd_theme/issues/231

**Comment by jessetan** [comment]
This does not seem to be fully covered by #231. Only `:github_url:`, `:bitbucket_url:`, and `:gitlab_url:` are documented, no other options are, nor where to put them. Reopening.

**Comment by htgoebel** [comment]
Hmm, this was closed as duplicate, then reopend since it is not. Still the label "duplicate" is still present. Shouldn't this be removed?

**Comment by peterjc** [comment]
Note ``html_context`` can be used with the GitHub, Bitbucket etc links - see example here:

https://github.com/readthedocs/sphinx_rtd_theme/issues/465#issuecomment-521272830

**Comment by stsewd** [comment]
Closing in favor of https://github.com/readthedocs/sphinx_rtd_theme/issues/582
