### ISSUE TITLE
Language choice is too hidden

### ISSUE THREAD

**Issue by jidanni** [readthedocs/sphinx_rtd_theme#1568]
I find it very bad that the user who encounters the wrong language, needs to tap the three bar menu, and then way down at the bottom, tap the version number in order to see the language choices. https://github.com/qgis/QGIS-Documentation/issues/9149

**Comment by ericholscher** [comment]
This is definitely an issue, adding a language selector to the theme is the right solution, and covered in https://github.com/readthedocs/sphinx_rtd_theme/issues/1587 -- closing this, so we can track it there.
