### ISSUE TITLE
Outdated docutils dependendancy

### ISSUE THREAD

**Issue by sjfke** [readthedocs/sphinx_rtd_theme#1570]
### Problem

GitHub dependabot demands docutils==0.21.2 but 'sphinx' and 'sphinx-rtd-theme' require outdated versions.
Using docutils<=0.21.2 does not make dependabot happy.

Give details on your issue.

Can you update the docutils dependency to unravel this dependency issue?

### Reproducible Project

See https://github.com/sjfke/nonbleedingedge/  (https://nonbleedingedge.com/)

$ cat requirements.txt
alabaster==0.7.16
Babel==2.15.0
certifi==2024.7.4
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
docutils==0.21.2
idna==3.7
imagesize==1.4.1
importlib_metadata==8.0.0
Jinja2==3.1.4
MarkupSafe==2.1.5
packaging==24.1
Pygments==2.18.0
pyparsing==3.1.2
pytz==2024.1
requests==2.32.3
setuptools==70.3.0
snowballstemmer==2.2.0
Sphinx==7.3.7
sphinx-intl==2.2.0
sphinx-rtd-theme==2.0.0
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-serializinghtml==1.1.10
sphinxemoji==0.3.1
urllib3==2.2.2
zipp==3.19.2

$ pip install -r requirements.txt --upgrade

#### Error Logs/Results

The conflict is caused by:
    The user requested docutils==0.21.2
    sphinx 7.3.7 depends on docutils<0.22 and >=0.18.1
    sphinx-rtd-theme 2.0.0 depends on docutils<0.21
    The user requested docutils==0.21.2
    sphinx 7.3.7 depends on docutils<0.22 and >=0.18.1
    sphinx-rtd-theme 2.0.0 depends on docutils<0.21

#### Expected Results

No errors

### Environment Info

- Python Version: Python 3.12.4 (From Microsoft Store)
- Sphinx Version: 7.3.7
- RTD Theme Version: 2.0.0

**Comment by sjfke** [comment]
Hi Guys, I appreciate it is Summer Vacation time and the Olympics are on, but could you please acknowledge.
Who knows, you might be fixing upstream security issues by looking at this?

**Comment by humitos** [comment]
This is going to happen in 3.0, and it's tracked by https://github.com/readthedocs/sphinx_rtd_theme/pull/1576

**Comment by humitos** [comment]
We released a new version [`3.0.0rc1`](https://pypi.org/project/sphinx-rtd-theme/3.0.0rc1/) that adds support for latest docutils versions. Please, give it a try and open an issue for any problem or feedback you want to share with us.

**Comment by sjfke** [comment]
The following works but also updated sphinx and a few others...
FWIW: I am using PyCharm CE to determine what needs updating

$ cat requirements.txt
alabaster==1.0.0
Babel==2.16.0
certifi==2024.7.4
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
docutils==0.21.2
idna==3.7
imagesize==1.4.1
importlib_metadata==8.4.0
Jinja2==3.1.4
MarkupSafe==2.1.5
packaging==24.1
Pygments==2.18.0
pyparsing==3.1.2
pytz==2024.1
requests==2.32.3
setuptools==73.0.1
snowballstemmer==2.2.0
Sphinx==8.0.2
sphinx-intl==2.2.0
sphinx-rtd-theme==3.0.0rc1
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==1.1.10
sphinxemoji==0.3.1
urllib3==2.2.2
zipp==3.20.0

$ pip install -r requirements.txt --upgrade

Website builds with no errors and looks fine (don't have an automated testing setup)
