### ISSUE TITLE
Math using LaTex

### ISSUE THREAD

**Issue by mehta-pavan** [readthedocs/sphinx_rtd_theme#1594]
Some of my work is very mathematical / therotical, with pages long proof. As you see, rewriting in ".rst" or similar; not only is prone to many errors but also time consuming for doing the same thing!

Thus, I would like to render directly my LaTex files ".tex" to reproduce some theory using sphinx / pydata theme.

Unfortutely, I only see the other way; where you are able to generate PDF or ".tex" file - but, I would like the other way around.

Thanks in advance!

**Comment by humitos** [comment]
Thanks. This is out of the scope for a Sphinx theme: https://github.com/pydata/pydata-sphinx-theme/issues/1957#issuecomment-2295384895
