### ISSUE TITLE
Depencency conflicts for sphinx 8

### ISSUE THREAD

**Issue by docktermj** [readthedocs/sphinx_rtd_theme#1600]
### Problem

[sphinx] is currently at version 8.0.2, but [sphinx-rtd-theme] 2.0.0 depends on sphinx >= 5 and <8.   Other sphinx plugins are enabled for  sphinx 8 and above giving dependency conflicts.

### Reproducible Project

Run the following command in a [GitHub Action] on [development-requirements.txt]:

```console
python -m pip install --requirement development-requirements.txt
```
#### Error Logs/Results

```console
ERROR: Cannot install -r development-requirements.txt (line 14), -r development-requirements.txt (line 15), -r development-requirements.txt (line 17), -r development-requirements.txt (line 18) and sphinx==8.0.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested sphinx==8.0.2
    sphinx-autodoc-typehints 2.4.0 depends on sphinx>=8.0.2
    sphinx-gallery 0.17.1 depends on sphinx>=5
    sphinx-prompt 1.9.0 depends on Sphinx<9.0.0 and >=8.0.0
    sphinx-rtd-theme 2.0.0 depends on sphinx<8 and >=5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Error: Process completed with exit code 1.
```

[sphinx]: https://pypi.org/project/Sphinx/
[sphinx-rtd-theme]: https://pypi.org/project/sphinx-rtd-theme/
[GitHub Action]: https://github.com/senzing-garage/sz-sdk-python-grpc/blob/main/.github/workflows/check-development-dependencies.yaml
[development-requirements.txt]: https://github.com/senzing-garage/sz-sdk-python-grpc/blob/main/development-requirements.txt

**Comment by humitos** [comment]
Hi @docktermj. We've released https://pypi.org/project/sphinx-rtd-theme/3.0.0rc1/ with support for Sphinx 8. Would you mind trying that release candidate version in your project? Feel free to provide any feedback you may have. Thanks.

**Comment by docktermj** [comment]
Sure.

**Comment by docktermj** [comment]
@humitos  Works like a charm!   Thanks for the quickness of your help!   Much appreciated.   Keep up the good work on this theme!
