### ISSUE TITLE
latest release of sphinx_rtd_theme 3.0..0 doesn't work with sphinx 8.0.2

### ISSUE THREAD

**Issue by radhikamanihar** [readthedocs/sphinx_rtd_theme#1612]
We get this error : 
Command sphinx-build -j 4 docs/source docs/build/html failed with exit code 2

Sphinx build command is expected to run in proper way

- Python Version: 3.11.9
- Sphinx Version: 8.0.2
- RTD Theme Version: 3.0.0

**Comment by humitos** [comment]
Hi. Can you provide more detailed information? What's the exact error? How can we reproduce the issue?

**Comment by humitos** [comment]
I did a quick test locally and I'm able to build the docs using 3.0.0 and Sphinx 8.0.2. Feel free to re-open with more information.

**Comment by radhikamanihar** [comment]
okay it works now, it was some other errors that has to be adapted with latest sphinx version
