### ISSUE TITLE
The styles of version_selector and language_selector in `3.0.0` are not user-friendly.

### ISSUE THREAD

**Issue by eMUQI** [readthedocs/sphinx_rtd_theme#1614]
### Problem

The styles of version_selector and language_selector are not user-friendly.

https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-version_selector

### Reproducible Project

https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-version_selector

#### Error Logs/Results

Place any images or error logs that might be able to help solve the issue here.

https://github.com/user-attachments/assets/e476715f-d80e-4dc2-9be1-4b49693aefe6

#### Expected Results

It should be as @humitos mentioned when 3.0.0rc2 was released.

https://github.com/readthedocs/sphinx_rtd_theme/issues/1598#issuecomment-2367604615

### Environment Info

- Python Version: 3.11
- Sphinx Version: 7.3.7
- RTD Theme Version: 3.0.0

**Comment by eMUQI** [comment]
I initially wanted to share the project link, but due to poor display effects, I temporarily disabled the `version_selector` and `language_selector` in my project. This issue also appears in the official Sphinx RTD theme documentation.

https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-version_selector

![image](https://github.com/user-attachments/assets/58f3b437-67ff-4c60-9bea-37fbe08bfbd0)

**Comment by humitos** [comment]
I'm not able to reproduce the issue with Firefox 131.0 (64-bit). I tried with Chrome Version 129.0.6668.89 (Official Build) (64-bit) and I was able to reproduce it.

**Comment by eMUQI** [comment]
Reproduce the issue with Firefox 131.0 (64-bit)
![image](https://github.com/user-attachments/assets/7aa52410-857c-4ec9-ab19-aa1ab8ef47aa)
![image](https://github.com/user-attachments/assets/d5b05a1b-54d0-4717-bb7c-4cd87d23d3f0)

and Zen Browser (base on Firefox 131.0)
![image](https://github.com/user-attachments/assets/5821564a-8d63-4a0a-85e8-1854c0d7ac15)
![image](https://github.com/user-attachments/assets/2e2ada53-37ce-4ed4-b204-caf4677dc11c)

**Comment by humitos** [comment]
@eMUQI I just released 3.0.1 that has this issue fixed. Please, give it a try and provide feedback 🙏🏼

**Comment by eMUQI** [comment]
> @eMUQI I just released 3.0.1 that has this issue fixed. Please, give it a try and provide feedback 🙏🏼

It works great now. Thanks for your effort.
