### ISSUE TITLE
Nagivation menu has different behaviour when building sphinx docs on different platforms (Windows & RaspberryPi)

### ISSUE THREAD

**Issue by paaalm07** [readthedocs/sphinx_rtd_theme#1619]
Building the same sphinx docs with exactly the same config once on Windows and once on Raspberry has different output. The "toctree expand" button is missing at all on RPI build. Check the screenshot below:

![image](https://github.com/user-attachments/assets/3d79dbba-69ce-4fc3-9133-c1091817273e)

Not sure where to start debugging but having a quick check in some files shows that also _build/_static/css/theme.css was different.
For example the keyword "toctree" is **never** present in this file.

**Comment by humitos** [comment]
Hi! Are you using the exact same versions of the theme? 

Can you provide an easy/isolated easy to reproduce this issue?

**Comment by paaalm07** [comment]
Strange. In the productive project the issue is there, but in isolated dummy project with just dummy files it works.
I try now to copy more and more from the productive project to the dummy project to check when the issue arrives.

I will give an update once I know more.

**Comment by paaalm07** [comment]
Issue is not present anymore. No idea why.
Since I'm using [hatch ](https://hatch.pypa.io/) as python manager, on each hatch command (e.g. hatch run docs) the dependencies are checked and updated. Maybe something has been updated in the last hour?! I don't know - that would be the only reason I could explain. Even if I switch to older versions like sphinx<8 and sphinx_rtd_theme<3 the issue does not appear again, but I will keep an eye on it.

**Comment by paaalm07** [comment]
Issue is not present anymore. No idea why.
Since I'm using [hatch ](https://hatch.pypa.io/) as python manager, on each hatch command (e.g. hatch run docs) the dependencies are checked and updated. Maybe something has been updated in the last hour?! I don't know - that would be the only reason I could explain. Even if I switch to older versions like sphinx<8 and sphinx_rtd_theme<3 the issue does not appear again, but I will keep an eye on it.
