### ISSUE TITLE
Flyout language selector doesn't show current language after upgrading to RTD Theme 3.0.0

### ISSUE THREAD

**Issue by Hyrla** [readthedocs/sphinx_rtd_theme#1621]
### Problem

I am not sure if this issue is related to RTD Theme or new addon system. Right now, flyout language selector doesn't show current language. Before upgrading to 3.0.0 (I was using 2.0.0), all language choices were shown. 

### Reproducible Project

Project documentation: https://esieabot.readthedocs.io/en/latest/
Project documentation conf.py file: https://gitlab.esiea.fr/esieabot/esieabot-docs/rtd/-/blob/main/docs/source/conf.py

#### Error Logs/Results

![image](https://github.com/user-attachments/assets/364a69db-c062-4f59-ba25-61a20ca97bbe)

![image](https://github.com/user-attachments/assets/2c66ad31-929d-455b-ab95-cc5585d9cae8)

#### Expected Results

Is there a way to display all available languages (including the one that is currently used) like before? On my screenshots, I only see French option when I am reading in English. In French version, I can only see English version.

### Environment Info

- Python Version: 3.12
- Sphinx Version: 8.3.1
- RTD Theme Version: latest (3.0.1)

**Comment by humitos** [comment]
Thanks for reporting this. It seems a bug in this chunk of code: https://github.com/readthedocs/sphinx_rtd_theme/blob/7b894f5e7a5053dd35de406bc779020c229f20a9/sphinx_rtd_theme/static/js/versions.js_t#L6-L26

It should be injecting `this.config.projects.current`, similar to what CPython's code is doing: https://github.com/python/cpython/blob/67f6e08147bc005e460d82fcce85bf5d56009cf5/Doc/tools/static/rtd_switcher.js#L23-L25

I forgot to do that when I migrated that work here.

**Comment by humitos** [comment]
I just released v3.0.2 that includes this fix. Please let us know if it works as expected.

**Comment by Hyrla** [comment]
> I just released v3.0.2 that includes this fix. Please let us know if it works as expected.

Yes issue has been fixed, thank you very much!
