### ISSUE TITLE
Latest released version asserts "unsupported theme option 'display_version' given" Warning

### ISSUE THREAD

**Issue by stevenjorgensen67** [readthedocs/sphinx_rtd_theme#1623]
### Problem

My GitHub Action started failing with the following Sphinx Warning:
unsupported theme option 'display_version' given
Last Passing run was September 17
When I switch to version 2.0.0 It works.

### Reproducible Project

Please give a link to a public reproducible project or provide an example of the Restructured Text that gives an issue.

```rst
Place RST code here (if any).
```

#### Error Logs/Results

Place any images or error logs that might be able to help solve the issue here.

#### Expected Results

Please describe how this should work properly.

### Environment Info
Sphinx==7.1.2,sphinx-autobuild==2021.3.14,sphinx-notfound-page==1.0.4,sphinx-readable-theme==1.3.0,sphinx-rtd-theme==3.0.1,sphinxcontrib-applehelp==1.0.4,sphinxcontrib-devhelp==1.0.2,sphinxcontrib-htmlhelp==2.0.1,sphinxcontrib-jquery==4.1,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.3,sphinxcontrib-serializinghtml==1.1.5
- Python Version:
- Sphinx Version:
- RTD Theme Version:

**Comment by kevalmorabia97** [comment]
It would be great to be able to display version for v3.0. It seems it is deprecated

**Comment by humitos** [comment]
The `display_version` config was removed in 3.x, that's why you are receiving this warning.

There is plan to add the version displayed when there is only one version: https://github.com/readthedocs/sphinx_rtd_theme/issues/1613#issuecomment-2400134774

Please, subscribe to that issue to get updates.
