### ISSUE TITLE
Support for routing table generated by sphinxcontrib.httpdomain

### ISSUE THREAD

**Issue by sleongkoan** [readthedocs/sphinx_rtd_theme#165]
sphinxcontrib.httpdomain automatically generates a routing table which link appears on upper right and lower right of the page (http://pythonhosted.org/sphinxcontrib-httpdomain/)

![image](https://cloud.githubusercontent.com/assets/2048174/5541755/58dd12be-8aab-11e4-9413-52bbe00c26e0.png)

Can you add support for that feature in the rtd theme?

Thanks

**Comment by Blendify** [comment]
Currently, the them does not automatically link to the genindex or other such pages. The solution to this would be to link to http-routingtable from the index page.
