### ISSUE TITLE
Create a release process

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/sphinx_rtd_theme#234]
Currently we change things about the default theme rendering of RTD without notifying users. Especially since we try and make it so that users don't really have to interact with RTD, having changes break their stuff is a particularly bad thing to happen.
## Process

We aren't going to be able to avoid making changes to our theme and builder code. That said, we should be able to communicate these changes in a good way.

Django and other projects have these in releases with "Backwards Incompatible Changes" lists -- which doesn't make a lot of sense because we don't do formal releases.

I think the proper response is to have a "dev" mailing list where we publish possible breaking changes of the theme or website.
## First Steps

We should write up a first draft of documentation around the process that we will follow. After that we need to document where people should go to get notified. We could use our existing "readthedocs" google group.

**Comment by stsewd** [comment]
We have docs, and a changelog, not sure if we want to do more than that. Related to https://github.com/readthedocs/sphinx_rtd_theme/issues/379

**Comment by agjohnson** [comment]
I've expanded on this a little bit in several recent PRs and issues. The documentation in #1208 covers the information we want to communicate here. We are planning on a blog post and newsletter announcement. Seems this can be closed!
