### ISSUE TITLE
Definition lists display with same styling as method lists

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#278]
Normal definition lists should appear with alternate styling to the normal method listings, such as:

![screen shot 2016-02-09 at 9 28 43 am](https://cloud.githubusercontent.com/assets/1140183/12918878/8c631e68-cf0f-11e5-8440-1f641f710413.png)

instead of:

![screen shot 2016-02-09 at 9 14 16 am](https://cloud.githubusercontent.com/assets/1140183/12918550/b80c009a-cf0d-11e5-84b2-c93015c7fd55.png)

**Comment by jessetan** [comment]
@agjohnson is this still an issue? Do you have an example of the source that produces the second screenshot? The theme documentation contains a glossary which uses a definition list, but it looks OK
https://sphinx-rtd-theme.readthedocs.io/en/latest/demo/demo.html#glossary

**Comment by stsewd** [comment]
Yeah looks like this is fixed, or related to https://github.com/readthedocs/sphinx_rtd_theme/issues/979
