### ISSUE TITLE
License of layout_old and search templates

### ISSUE THREAD

**Issue by oorestisime** [readthedocs/sphinx_rtd_theme#283]
Heya,

Looking the license at {layout_old and search}.html templates it says BSD and more details should be found in the LICENSE file. Although that file says MIT. Was there a change of license? Are those still BSD?

Cheers,

Orestis

**Comment by Blendify** [comment]
I talked to @ericholscher a little on IRC and this is because originally the files were copied from sphinx's basic theme. I also think that layout_old.html is no longer used. SO the question is are we safe to remove the original copyright messages?

**Comment by ericholscher** [comment]
I believe we can the layout_old one.
