### ISSUE TITLE
Table cells with multiple paragraphs gets wrong formatting

### ISSUE THREAD

**Issue by pgerell** [readthedocs/sphinx_rtd_theme#289]
table/tr/td elements gets font-size:90%, /table/tr/td/p elements does not.

**Comment by pgerell** [comment]
$ pip list | grep -i sphinx
Sphinx (1.3.6)
sphinx-rtd-theme (0.1.9)

**Comment by pgerell** [comment]
I tried looking into this again without success. 
I am not sure whether this is problem in sphinx_rtd_theme, wyrm or maybe in sphinx itself.

I believe it would be better if the Sphinx html builder put single paragraph inside <p> tags? That way the themes would not have to handle that as a special case. 

Unfortunately that is not the case so the theme has to handle both cases. I could not find any sass rule that sets to font to 90% so I assume this is done in wyrm. Is this correct? 
As I find the 90% size look better in tables, I'm looking for a way to get that size also for the text within <p>.
As a complete sass novice I can not tell if this is possible to with sphinx_rtd_theme or if the change would have to be done in wyrm.

**Comment by Blendify** [comment]
Do you have a public example of this issue? or maybe simply add an image?

**Comment by pgerell** [comment]
I have no public example, but can try to create one if needed.
I start with a picture. 
As you can see the text is larger in the cells with multiple paragraphs.


![image](https://cloud.githubusercontent.com/assets/16148923/23816912/c49b7286-05ef-11e7-9f10-9766de17789d.png)

The source is:

```
Operator precedence
-------------------

.. |LR| replace:: Left-to-right
.. |RL| replace:: Right-to-left


==========  ==========   ============================== =============
Precedence  Operator     Description                    Associativity
==========  ==========   ============================== =============
1           \::          Scope resolution               |LR|
----------  ----------   ------------------------------ -------------
2           ( )          Function call                  |LR|

            [ ]          Subscript

            .            Member access

            .{ }         Bit-field concatenation
----------  ----------   ------------------------------ -------------
3           \+           Unary plus                     |RL|

            \-           Unary minus

            !            Logical not

            ~            Bitwise not

            (|type|)     Type cast

            & (unary)    Address-of

            sizeof       Size-of
----------  ----------   ------------------------------ -------------

```

**Comment by Blendify** [comment]
Thanks.

**Comment by pgerell** [comment]
Do you need a public example or was the screenshot sufficient?

**Comment by Blendify** [comment]
This is good I will add to our next milestone.

**Comment by prc018100** [comment]
Do you guys know of a css override I could use to work-around this issue?  I've setup my own override.css file but everything I've tried doesn't seem to set the paragraph inside the table to font-size 90% so it will match

**Comment by Tzaphkiel** [comment]
I also have the issus. Has this been fixed already ?

**Comment by Tzaphkiel** [comment]
After searching for way too long, I decided to fix the theme with a style overide.

@prc018100 here you go 
```css
/* fix paragraphs in grid tables getting a bigger fonts than regular cels */
table.docutils td p {
  font-size: inherit !important;
}
```

I also took the oportunity to fix the cell text wrapping:
```css
/* Fix the cell wrapping in the #@{ tables of the the readthedocs theme */
table.docutils td {
  white-space: normal;
}
```
