### ISSUE TITLE
Sidebar anchors double-click loose selection

### ISSUE THREAD

**Issue by m-messiah** [readthedocs/sphinx_rtd_theme#306]
In sidebar, when I click to endpoint once - it opens according page and scrolls to anchor as expected.

But when I click same endpoint second time - nothing happens with page (as expected), but endpoint in sidebar loose its selection (which is wrong).

Tested locally, on self-hosted docs, on readthedocs.io - same behavior.

**Comment by Blendify** [comment]
Please try with an updated theme. (0.2.4 is the current release)

**Comment by m-messiah** [comment]
Nothing changed:
I have checked on latest Sphinx==1.5.3 and sphinx-rtd-theme==0.2.4, but behavior still remains.

Some screenshots:

+ with first open page (you can see it at breadcumbs)
   ![with first open page (you can see it at breadcumbs)](https://cloud.githubusercontent.com/assets/2103030/23938241/809d34cc-096c-11e7-908e-1a4b01cb24c2.png)
+ and second click
   ![and second click](https://cloud.githubusercontent.com/assets/2103030/23938253/8ff39d30-096c-11e7-8909-89004467aabb.png)
