### ISSUE TITLE
Inline code literals have no wrapping

### ISSUE THREAD

**Issue by gappleto97** [readthedocs/sphinx_rtd_theme#321]
I'm trying to give examples of how an object is serialized. I need this to wrap properly.

When I use the default style, it looks like this:

![](http://i.imgur.com/oRaVFUu.png)

If I use the solution in [mkdocs/#709](https://github.com/mkdocs/mkdocs/issues/709), it looks like:

![](http://i.imgur.com/wkV13J8.png)

The first and last literal look fine, but the middle one is insanity. Can you help me fix/explain what's going on here? And if we arrive at a satisfactory solution, could this be integrated into the default theme?

**Comment by Blendify** [comment]
What do we want to do here? Add a scroll bar or wrap the text?

**Comment by jessetan** [comment]
I prefer scrolling. Opnions?

**Comment by stsewd** [comment]
+1 on wrapping, adding a scrollbar would make it more "big" or look weird being inside a paragraph
