### ISSUE TITLE
Sidebar does not reliably open from L3/L4 links

### ISSUE THREAD

**Issue by mattklein123** [readthedocs/sphinx_rtd_theme#397]
Possibly related to https://github.com/rtfd/sphinx_rtd_theme/issues/290

In the [Envoy docs](https://envoyproxy.github.io/envoy/index.html) if a user clicks on any :ref: links that point to L3 or L4 headings, the sidebar does not reliably open to the L3 or L4 heading.

Repro:
1) On this page: https://envoyproxy.github.io/envoy/intro/arch_overview/listeners.html
2) Click on "sniffing" link: https://envoyproxy.github.io/envoy/intro/arch_overview/mongo.html#arch-overview-mongo

Expected: Open left side sidebar down to MongoDB

Actual: Only opened to L2.

NOTE: This bug happens all over the documentation. Sources are here: https://github.com/envoyproxy/envoy

**Comment by petermd** [comment]
I think afaf0dc9bddf19e34658e661b3c3c2a7d4dfa265 adds a second way to search for the matching anchor, but these anchors (`arch-overview-mongo`) don't exist? 

even if the `link` array is still empty the code in `nav.reset` still removes the `current` style from L2/L3/L4 but never re-adds it (causing the side-bar to close)

only removing `current` if there is a link located _should_ fix the issue eg something like 42e90cdd64983633733eb6f636819992dee65e55

**Comment by mattklein123** [comment]
Thank you @petermd! Hero!

**Comment by mattklein123** [comment]
@petermd I tried out your commit here: https://github.com/envoyproxy/envoy/commit/1abdeb25081d1a5267482469ad422b5b8cd71c7e

And it still seems to be not working. Did I setup requirements.txt the right way? It seemed to clone your branch.

**Comment by petermd** [comment]
@mattklein123 right, so I think a full change needs a `grunt` run to create the static export, not sure what the process is for a PR (there are several re-generated files but only the `theme.js` is needed is this case)

I added 09da15bb9b0cf26543f789c0c661dce7924765b4 that you can use to test the fix from the envoy side.

**Comment by mattklein123** [comment]
@petermd just tried it and it definitely seems to fix our issue! 🎉 Thank you so much!

@Blendify any chance of getting this reviewed / merged? Otherwise I can setup a fork. Thank you!

**Comment by Blendify** [comment]
I can take a look Wednesday.

**Comment by mattklein123** [comment]
Awesome thank you @Blendify!

**Comment by mattklein123** [comment]
@Blendify friendly ping on the review here. If you don't think you can to it I understand, but LMK and we will fork. Thank you.

**Comment by Blendify** [comment]
I am sorry I should have replied sooner but was pressed for time. Please create a PR, there is no need to run `grunt`. I and or others can review it.

**Comment by stsewd** [comment]
Looks like this was fixed in https://github.com/readthedocs/sphinx_rtd_theme/pull/472. Feel free to ask to re-open if not
