### ISSUE TITLE
Add localization language support

### ISSUE THREAD

**Issue by macagua** [readthedocs/sphinx_rtd_theme#403]
Hi guys

Is possible to add localization language support? because the footer templates are in English, but my Sphinx project is about Spanish documentation

Here I see that the templates have i18n support, but it's don't have locales directory for localization, for example Spanish language 
https://github.com/rtfd/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/footer.html

Any idea ?

**Comment by ericholscher** [comment]
I'm not 100% sure how to actually translate Sphinx themes. I believe it should use the same i18n infrastructure as Sphinx itself, but haven't done the research on it. This would be a great place for contribution and having folks who care about keeping the theme translated as part of our core team, if you're curious of a good way to contribute!

**Comment by mitya57** [comment]
I can share the steps I was using in [our project](http://docs.istina.msu.ru/):

 *  Install [babel from PyPI](https://pypi.python.org/pypi/Babel).
 *  Create file `babel.cfg` (in this repository) with this content:
    ```ini
    # Extraction from Jinja2 HTML templates
    [jinja2: **/**.html]
    encoding = utf-8
    ignore_tags = script,style
    include_attrs = alt title summary
    ```
 *  Add this to `setup.cfg`:
    ```ini
    [extract_messages]
    mapping_file = babel.cfg
    output_file = sphinx-rtd-theme.pot
    keywords = _ l_ lazy_gettext
    ```
 *  Run `python setup.py extract_messages` to generate `sphinx-rtd-theme.pot`.
 *  Create the `.po` file for your language using `msgmerge` tool (I think you can use Babel if you prefer).
 *  Translate it using your favourite application (i.e. `gtranslator`).
 *  Place the translated `.po` file in your project as `locale/$LANG/LC_MESSAGES/sphinx.po`.
 *  Add `locale_dirs = ['locale/']` to your project’s `conf.py`.

**Comment by macagua** [comment]
@mitya57 you are the man really thanks! 🍺

**Comment by Blendify** [comment]
@macagua any update on this?

**Comment by macagua** [comment]
@Blendify yes, please check out https://github.com/rtfd/sphinx_rtd_theme/pull/405
