### ISSUE TITLE
Italian localization for RTD Theme

### ISSUE THREAD

**Issue by torre76** [readthedocs/sphinx_rtd_theme#458]
Following instruction taken from #403, I had built the Italian `po` file which I am currently using in an internal project.

Feel free to merge on #405.

Regards 

[Italian PO file for RTD download](https://github.com/rtfd/sphinx_rtd_theme/files/1277130/it.po.zip)

**Comment by Blendify** [comment]
Thank you!

**Comment by stsewd** [comment]
Thanks, translations are managed in transifex https://sphinx-rtd-theme.readthedocs.io/en/stable/contributing.html#translations.
