### ISSUE TITLE
Inconsistent application of `metatags` in HTML, RTD generation; cache-control

### ISSUE THREAD

**Issue by sirlensalot** [readthedocs/sphinx_rtd_theme#469]
(Reproduced both on a local rtd build as well as on RTD server, see http://pact-language.readthedocs.io/en/latest, github conf.py etc is at https://github.com/kadena-io/pact/tree/master/docs .)

I'm trying to use conf.py to set cache-control tags as follows:

```
html_context = {
    'metatags' : '<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" /><meta http-equiv="Pragma" content="no-cache" /><meta http-equiv="Expires" content="0" />'
}
```

Looking at layout.html, we see `{{metatags}}` here: https://github.com/rtfd/sphinx_rtd_theme/blob/d24f7ca6b57052eaf0843d56da46e1bfc71aa7f5/sphinx_rtd_theme/layout.html#L16 . So you would think this would show up on all generated pages.

Instead, my metatags only show up in `genindex.html` and `search.html`. `index.html` and my doc htmls (pact-reference.html) have nothing there.

I also tried setting metatags in the doc, as follows:

```
.. meta::
   :metatags: STUFF
```

This only gets inserted into my main doc file (pact-reference.html) but is missing everywhere else.

Is `metatags` being overwritten somewhere? I can't figure out why it shows up only on some pages and not others.

ALTERNATELY: is there any objection to simply adding the cache-control tags directly to the templates? It's really not ideal that RTD docs don't have them, and it means users end up inadvertently seeing old versions of the docs if they don't force-refresh their browser. If there is appetite for this I'm happy to provide a PR.

**Comment by Blendify** [comment]
https://github.com/rtfd/sphinx_rtd_theme/pull/467 might fix this.

**Comment by stsewd** [comment]
Hi, the metatags are injected by sphinx and expose it as `metatags` for templates https://www.sphinx-doc.org/en/master/templating.html#metatags

As the docs mention, to add custom metatags you need to use the meta directive

```rst
.. meta::
   :foo: bar
```

If you want to add some metatags to all pages, you can use https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_prolog.

Why it works with pages like search and genindex? Not sure, and looks like using `rst_prolog` doesn't work for the search page as well. But that's a sphinx problem, please report that problem upstream.
