### ISSUE TITLE
Decide on use of Modernizr

### ISSUE THREAD

**Issue by jessetan** [readthedocs/sphinx_rtd_theme#525]
In #518 the use of Modernizr for the theme was questioned. If we can remove this, it would make the build a bit simpler and the output a bit smaller.

- If the feature detection is not used by the theme, is it still needed to include Modernizr?
- If we do need Modernizr, do we need the kitchen sink build currently included?

**Comment by remyabel** [comment]
According to https://github.com/rtfd/sphinx_rtd_theme/pull/248, Modernizr was only included for old IE support. I've personally removed it from my project and haven't noticed any issues.

**Comment by Blendify** [comment]
I say remove it. But would let @agjohnson again have the final word.

**Comment by davidfischer** [comment]
Just to chime in with a bit of data, IE versions before 11.0 are less than 0.2% of traffic (Nov 1 through today) on readthedocs.io according to GA.

This might be a good time to formalize our browser support policy.

**Comment by Blendify** [comment]
Considering this only affects versions below ie9. It will affect a very low
number but I think yes we should come to a conclusion and document what
version we are willing to support.

**Comment by jessetan** [comment]
@davidfischer Is the 0.2% traffic for the documentation RTD itself or for all the documentation hosted by RTD?

We can keep IE<9 support for the HTML5 elems by just using the htmlshiv in the head and removing the rest of Modernizr. We do not use any of the feature detection stuff in Modernizr.

A formal browser support policy would help. Old IE support is already iffy because the theme uses jQuery which does not work on IE<9. I don't know how much more broken the theme would be if we would also remove the htmlshiv, but we can try to see what happens.

**Comment by davidfischer** [comment]
I missed this but the 0.2% is for all docs sites hosted by Read the Docs. Essentially nobody visiting RTD is using IE<11 now. IE11 is still close to 2%.

**Comment by Blendify** [comment]
I think it is safe to remove this now.

**Comment by davidfischer** [comment]
I we are just including it for IE<11, then it is safe to remove. Do we know precisely which detects we use if any?

**Comment by davidfischer** [comment]
Consider me +1 then. I'm fine dropping support for IE<11 as virtually no users use those old versions.

I do believe that dropping support should involve incrementing the version to 0.4.0 though. We also should be explicit in the docs about which browsers are supported.

**Comment by jessetan** [comment]
> We also should be explicit in the docs about which browsers are supported.

I agree, but such a statement for the theme depends on a statement for the entire RTD service (which I couldn't find, ping @ericholscher @agjohnson). We should not build a theme that only works on the latest browsers if the goal of RTD is to also support legacy browsers.

**Comment by agjohnson** [comment]
I don't have time at the moment to research some of the ramifications of dropping modernizer, but to put into perspective: even though `0.2%` sounds low, the real number behind this is 500k+ pageviews a year. This number is more significant than the portion of our traffic probably. I'd like to figure out what sort of experience those 500k+ pageviews would have before dropping support for them.

If no one gets to it before I do, I'm just going to test the theme via saucelabs and an ancient browser/os combo. I'm curious what the page and nav content will look like. If it's at least usable, I think we can sacrifice the dependency on modernizer.

**Comment by jessetan** [comment]
I've created a branch in #624 suitable for testing with older browsers.

**Comment by Blendify** [comment]
Eeek Modernizr was removed a long time ago, time to close this.
