### ISSUE TITLE
Bad selector for highlighted code.

### ISSUE THREAD

**Issue by chebee7i** [readthedocs/sphinx_rtd_theme#53]
A typical code block might appear as:

```
<div class="highlight-python">
```

which is handled by:

```
div[class^='highlight']
```

However, Sphinx sometimes represents code blocks as:

```
<div class="last highlight-python">
```

And these blocks are not highlighted by the above rule.

**Comment by hameno** [comment]
I think this is broken again - I have the same issue now on RTD

**Comment by Blendify** [comment]
@hameno can you reproduce locally?
