### ISSUE TITLE
Don't add elements with JavaScript, add with Sphinx writer

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#530]
We shouldn't be adding additional elements via JavaScript when we have access to running Sphinx extensions. An extension could output the additional elements around tables and citations that we use for styling.

**Comment by Blendify** [comment]
👍

**Comment by humitos** [comment]
Where are we adding these elements via JavaScript? Can you link to the code? Is this issue still valid?

**Comment by humitos** [comment]
OK. I think I found what this issue refers to, and it's dup of https://github.com/readthedocs/sphinx_rtd_theme/issues/783
