### ISSUE TITLE
rst-versions is not scrollable

### ISSUE THREAD

**Issue by Blendify** [readthedocs/sphinx_rtd_theme#575]
### Problem

rst-versions is not scrollable causing issues with large number of versions.

### Reproducible Project

http://kinto.readthedocs.io/en/latest/api/1.x/buckets.html#post--buckets

#### Error Logs/Results

See the side bar

#### Expected Results

There should be a way to see the full sidebar with scrolling

### Environment Info

- Python Version: 3.6
- Sphinx Version: 1.6.x
- RTD Theme Version: latest stable

**Comment by jessetan** [comment]
This had side-effects (see #626), fixes for this issue were reverted.

**Comment by stsewd** [comment]
One user proposed a solution from the rtd side at https://github.com/readthedocs/readthedocs.org/pull/7375/

**Comment by Blendify** [comment]
This has been fixed with 73d302993285eb29a5236da49255b621f337d228. There are possible improvements in #791
