### ISSUE TITLE
Option not to embed font files

### ISSUE THREAD

**Issue by trustin** [readthedocs/sphinx_rtd_theme#611]
### Problem

I prefer not to embed font files shipped by `sphinx_rtd_themes` but rather want to add an override CSS file and use the fonts I prefer, which could be shipped with my `_static` directory or sourced from Google Fonts.

#### Expected Results

It would be great if we have an option that generates `_static/css/theme.css` without any `@font-face` directives. It's OK to keep the `font-family` properties unchanged because a user can override them using an override CSS file easily.

### Environment Info

- Python Version: 3.6.5
- Sphinx Version: 1.7.2
- RTD Theme Version: 0.3.0

**Comment by davidfischer** [comment]
We are considering a switch to a native font stack (covered partially in #524) which might solve this.

**Comment by jessetan** [comment]
I'm -1 on adding an option to not include font files. This will create a possibility for misconfiguration: font files not included, but unchanged @font-face and font-family tries to load them.

If an author wants to override the fonts used by the theme, they can [supply some custom css](http://docs.readthedocs.io/en/latest/guides/adding-custom-css.html). The original theme font files will still exist on the server, but they will never be used. The disk space used is negligible.

**Comment by trustin** [comment]
Does adding a custom css stop a browser from loading the fonts imported from the RTD's bundled CSS? I guess it will load the font files since the bundled CSS file will be loaded anyway.

**Comment by jessetan** [comment]
A browser is expected to only download the font file in an `@font-face` if it is also used somewhere (through `font-family`). So if you override the `font-family` in your custom CSS, the browser should not download the font file.

**Comment by mrexodia** [comment]
With regards to the comment about the disk space usage being negligible. In my case I build a CHM file and the size increased from 1.2mb to 5.8mb, which is slightly unfortunate...

**Comment by jessetan** [comment]
@mrexodia if you have an automated build step that compiles the sphinx-generated HTML into CHM, you can insert a step to remove any files you don't need.
Apart from the font files, you might be able to remove `searchindex.js`, `objects.inv`, all of `_sources`, and some unused images in `_static`

**Comment by stsewd** [comment]
Looks like the original question was solved.
