### ISSUE TITLE
Missing style for ".literal-block"

### ISSUE THREAD

**Issue by tdruez** [readthedocs/sphinx_rtd_theme#65]
Great job on this new theme, it looks awesome!

I've noticed something wrong with the generated CSS for the pre.literal-block:
See in `sphinx_rtd_theme/static/css/theme.css`:

```
pre.literal-block{@extends .codeblock;}
```

As a result, the current `.. parsed-literal::` are not styled.

**Comment by yagebu** [comment]
@snide `parsed-literal` blocks don't have the same padding as other code block for me. Is this intentional or has this bug reoccured?
