### ISSUE TITLE
Missing spaces inside dt's

### ISSUE THREAD

**Issue by joshkel** [readthedocs/sphinx_rtd_theme#694]
### Problem

`dt`s that contain formatting lose the spaces between their formatting.

### Reproducible Project

The pybind11 project uses Breathe to include Doxygen-generated C++ information in its docs. This should have spaces between the keywords and identifiers (e.g., `iterator begin() const`). However, because the `dt` is set as `display: table`, any internal spaces are lost, and the text shows as `iteratorbegin()const`.

See https://pybind11.readthedocs.io/en/master/reference.html#_CPPv3NK10object_api5beginEv for an example.

This problem was apparently introduced with #384's change from `display: inline-block` to `display: table` (that was made to fix #90). If I undo the change from #384 (either by building the pybind11 docs with an older version of the theme or by using Chrome Dev Tools to change the style on the fly), the pybind11 docs look correct.

I tinkered with styles some and couldn't find a way to fix both this problem and the problem from #384 without changing the HTML. For what it's worth, I noticed that the sample document that demonstrated #90 had [updated its documentation style](https://github.com/giampaolo/psutil/commit/e4a41c162ea362277306c767222ca0c91bc4a6d2#diff-caf2a6b8f4947d018f68893c695b5202R1785) to no longer be affected by #90. I'm fairly new to RST, though, so I don't know which `.. data::` style is preferred.)

#### Error Logs/Results

Current (bad) pybind11:

![2018-10-30 22_55_58-reference pybind11 2 3 dev0 documentation](https://user-images.githubusercontent.com/476338/47763507-5fc94b00-dc97-11e8-8c01-349969a08586.png)

#### Expected Results

Building pybind11 with a `display: inline-block`:

![2018-10-30 22_59_45-reference pybind11 2 3 dev0 documentation](https://user-images.githubusercontent.com/476338/47763560-94d59d80-dc97-11e8-888e-31a8c7525fbd.png)

### Environment Info

Here's the information for locally building the pybind11 docs (which does NOT demonstrate thisbug).

- Python Version: 3.5.2
- Sphinx Version: 1.6.4
- RTD Theme Version: 0.2.4
- Breathe: 4.10.0

**Comment by breathe67** [comment]
I have just started using Sphinx & Breathe (version as of Jun 1, 2020) to convert my Doxygen docs to the RTD theme. I'm also having this problem, where my C++ types and other identifiers have no spaces between them.

**Comment by mbenlioglu** [comment]
Is there any progress on this one?

**Comment by Lucide** [comment]
I'm still having the issue with a C project **on Chrome** (incognito mode to exclude extensions interference):
![1](https://user-images.githubusercontent.com/33134209/98812138-3f096380-2422-11eb-926b-4ec258c79a5f.PNG)
![2](https://user-images.githubusercontent.com/33134209/98812145-416bbd80-2422-11eb-974e-e0ea5b45d529.PNG)
![3](https://user-images.githubusercontent.com/33134209/98812149-43358100-2422-11eb-98ac-65f9009758e6.PNG)
The issue doesn't seem to occur in Firefox, but there's still a lot of space after `const`.

**Comment by Blendify** [comment]
Hi, can you paste the RST code to generate the issue. It makes testing for us easier.

**Comment by Lucide** [comment]
I'm using breathe's directives:
```rst
.. doxygenfunction:: vtInitializeArray
```
Note that
> The issue doesn't seem to occur in Firefox, but there's still a lot of space after `const`.

**Comment by Andrei1Byte** [comment]
@Blendify / @stsewd  Do you know if is in plan to fix soon this Bug as is a very old one? Or if there are some workarounds for this?

**Comment by IvanoBilenchi** [comment]
I'm experiencing the same issue, using Breathe to bridge Doxygen's XML to Sphinx.

For those in need of a quick hack until this is fixed upstream: you can override the `display` property for `dt` by providing an additional CSS file to Sphinx via `conf.py`:

```python
def setup(app):
    app.add_css_file('path/to/style.css')
```

Then in `style.css`:

```css
dt {
    display: inline-block !important;
}
```

**Comment by Blendify** [comment]
I looked into this add found that fix however there are still some spacing issues because some elements manually add padding but its hard to make a CSS selector add padding to all the correct places, a bit more investigation is needed.

**Comment by jakobandersen** [comment]
For C and C++ declarations I believe the issue should be fixed from Sphinx v4, as the declarations are rendered using a new set of nodes. This includes all spaces being in spans instead of in the top-level dt (e.g., see https://github.com/michaeljones/breathe/issues/655#issuecomment-808387732).
See https://github.com/sphinx-doc/sphinx/pull/9023 for more on the new rendering scheme.

**Comment by Blendify** [comment]
Yes, this should now be fixed in newer sphinx versions. There are currently no intentions in fixing this for older versions so this issue can be closed.
