### ISSUE TITLE
vcs_pageview_mode template parameter is not recognised

### ISSUE THREAD

**Issue by munhitsu** [readthedocs/sphinx_rtd_theme#701]
### Problem

Since #617, vcs_pageview_mode template parameter is not recognised anymore.
For ``html_theme_options`` attribute to be passed to theme it needs to be registered in ``theme.conf``

### Reproducible Project

N/A

#### Error Logs/Results

``preparing documents... WARNING: unsupported theme option 'vcs_pageview_mode' given
done``

#### Expected Results

Please describe how this should work properly.

### Environment Info

- Python Version: 3.7.1
- Sphinx Version: 1.8.1
- RTD Theme Version: 0.4.2

**Comment by gaborbernat** [comment]
Ping 👍

**Comment by lmgeorge** [comment]
Found a workaround as of 0.5.0: set `theme_vcs_pageview_mode`[(source)](https://github.com/readthedocs/sphinx_rtd_theme/blob/38c30bf8ac99f648aef15907c623648739f373de/sphinx_rtd_theme/breadcrumbs.html#L45) in `html_context`:
```
html_context = {
    'theme_vcs_pageview_mode': 'edit'
}
```

**Comment by Limonkufu** [comment]
@lmgeorge thanks for pointing out the workaround I have been using it since August but didn't post it

> Found a workaround as of 0.5.0: set `theme_vcs_pageview_mode`[(source)](https://github.com/readthedocs/sphinx_rtd_theme/blob/38c30bf8ac99f648aef15907c623648739f373de/sphinx_rtd_theme/breadcrumbs.html#L45) in `html_context`:
> 
> ```
> html_context = {
>     'theme_vcs_pageview_mode': 'edit'
> }
> ```

**Comment by stsewd** [comment]
Sorry everyone! I have a fix for this https://github.com/readthedocs/sphinx_rtd_theme/pull/1010
