### ISSUE TITLE
getting error when try to load custom css

### ISSUE THREAD

**Issue by alexkoretzki** [readthedocs/sphinx_rtd_theme#714]
getting this error : 
Refused to apply style from 'http://localhost:1919/_static/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

when follow this instructions 
https://docs.readthedocs.io/en/latest/guides/adding-custom-css.html

**Comment by stsewd** [comment]
Yes, please use https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_css_files.
