### ISSUE TITLE
Literal/ref format is different when occuring in definition list

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#717]
### Problem

I noticed this using intersphinx links that 

### Reproducible Project

Our own docs, using my branch at #674 

#### Error Logs/Results

Note the formatting of the `toctree` literal link (this is to a :py:data: directive)

Outside of a definition list:

![image](https://user-images.githubusercontent.com/1140183/51569169-dae66b80-1e58-11e9-9bbd-3ec1fec41d31.png)

Inside:

![image](https://user-images.githubusercontent.com/1140183/51569224-01a4a200-1e59-11e9-9610-dc37b3a70bf4.png)

#### Expected Results

Link or literal should be the same. This might also affect literals nested in other types of lists.

**Comment by jessetan** [comment]
The comments in SASS describe this being used in Sphinx' autodoc output. It's used to make the classname render as bold.

Possible solution (all lines in https://github.com/rtfd/sphinx_rtd_theme/blob/0.4.2/sass/_theme_rst.sass):
- Move bold font weight from `.rst-content dl:not(.docutils) code` (L343) to `.rst-content dl:not(.docutils) code &.descname, &.descclassname` (L345)
- Remove duplicate bold font weight from `.rst-content dl:not(.docutils) code &.descname` (L350)
- Test if there is any other autodoc output unbolded by this when it shouldn't
