### ISSUE TITLE
Screen flashes on load

### ISSUE THREAD

**Issue by tvst** [readthedocs/sphinx_rtd_theme#724]
### Problem

When I go to any page using the RTD theme, my browser noticeably flashes white for a few dozen milliseconds before the page shows up. When I comment out `modernizr.min.js` from my HTML pages, the white flashes go away.

### Reproducible Project

I see this in every project that uses the RTD theme. Which means I can repro it here too: https://sphinx-rtd-theme.readthedocs.io/en/stable

Steps to repro:

1) Go to https://sphinx-rtd-theme.readthedocs.io/en/stable
(This already repros the bug, but it's not so easy to notice on first load. So let's go to step 2)

2) Click on "Configuration" on the left sidebar.
Expected: the Configuration page seamlessly loads
Actual: the screen flashes white _and then_ the Configuration page loads

3) You can repro this 100% of the time by clicking on **top level** links on the sidebar.

#### Error Logs/Results

There are no errors on the console.

### Environment Info

- Python Version: n/a
- Sphinx Version: 1.8.4
- RTD Theme Version: 0.4.3
- Browser: Chrome Version 72.0.3626.96 (Official Build) (64-bit)

**Comment by jessetan** [comment]
Modernizr causes 4 reflows on my test setup, possibility of removing it should get some renewed attention (#624)

**Comment by Blendify** [comment]
+1 for removal.
