### ISSUE TITLE
Footnotes not rendering like the demo in Sphinx 2.0

### ISSUE THREAD

**Issue by mr-ubik** [readthedocs/sphinx_rtd_theme#741]
### Problem

Footnotes do not render like they do in the demo.

### Reproducible Project

- I copied and pasted the RST from the demo itself.
- I am not running any custom CSS.
- I have enabled the following extension
	```python
	extensions = [
    	"sphinx.ext.autodoc",
    	"sphinx.ext.doctest",
    	"sphinx.ext.intersphinx",
    	"sphinx.ext.todo",
    	"sphinx.ext.coverage",
    	"sphinx.ext.mathjax",
    	"sphinx.ext.ifconfig",
    	"sphinx.ext.viewcode",
    	"sphinx.ext.githubpages",
    	"sphinx.ext.napoleon",
    	"sphinx.ext.autosummary",
    	"sphinx.ext.inheritance_diagram",
    	"sphinx.ext.graphviz",
	]
	```
- I have the following `sphinx_rtd_theme` configuration:
	```python
	html_theme_options = {
    	"display_version": True,
    	"sticky_navigation": True,
    	"collapse_navigation": False,
    	"navigation_depth": 4,
	}
	```
##### Note

This issue can be reproduced easily by using Cookiecutter with the "New Python Package" template, preparing a `virtualenv` with `sphinx` and `sphinx_rtd_theme`, changing the default to RTD and making the docs after copying the demo RST to one of the default .rst files that come with the template.

#### Error Logs/Results

![Erroneous Style](https://user-images.githubusercontent.com/16547060/55236761-f727cf80-5230-11e9-9853-4dd15a2354df.png)

#### Expected Results

Display footnotes as they do in the demo.

![aragraph Level Markup — Read the Docs Sphinx Theme 0.4.3 documentation](https://user-images.githubusercontent.com/16547060/55237374-56d2aa80-5232-11e9-818d-cf49ccec2dc1.png)

### Environment Info

- Python Version: 3.7.1
- Sphinx Version: 2.0.0
- RTD Theme Version: 0.4.3

**Comment by grissu** [comment]
I confirm, this happened to me after switching from Sphinx 1.8.3 to 2.0.0.

**Comment by idnsunset** [comment]
Same issue here, currently using Sphinx 2.0.1, footnotes are rendered as description list in html.

**Comment by iruletheworld** [comment]
I can confirm that this still exists in Sphinx 2.2

**Comment by MatinF** [comment]
Also encountering this issue
