### ISSUE TITLE
Classifier delimiter is not shown with Sphinx >=2.0.0

### ISSUE THREAD

**Issue by polyzen** [readthedocs/sphinx_rtd_theme#746]
### Problem

https://github.com/sphinx-doc/sphinx/pull/5976

Sphinx >=2.0.0 defaults to the HTML5 writer.

### Reproducible Project

https://gitlab.com/polyzen/wiki

#### Error Results

With 2.0.1:
https://5cae6f482f618700081c1c0e--polywiki.netlify.com/self-hosted_applications/

#### Expected Results

With 1.8.5:
https://5cae7189c3de3d0009d505a0--polywiki.netlify.com/self-hosted_applications/

### Environment Info

- Python Version: 3.7
- Sphinx Version: 2.0.1
- RTD Theme Version: 0.4.3

**Comment by Blendify** [comment]
I opened a PR that will fix this. #747
