### ISSUE TITLE
Cannot build docs TypeError("make_toctree() got an unexpected keyword argument 'titles_only'"

### ISSUE THREAD

**Issue by marskar** [readthedocs/sphinx_rtd_theme#749]
### Problem

When building docs, I got an error:
```
An error happened in rendering the page cli.
Reason: TypeError("make_toctree() got an unexpected keyword argument 'titles_only'")
```

I think it may be due to the fact that I am using the click based cli and building docs with the sphinx click extension.

https://github.com/click-contrib/sphinx-click

### Reproducible Project

https://github.com/marskar/nbless/

#### Expected Results

I want to use the rtd theme for the project above instead of the alabaster theme I have now:
https://marskar.github.io/nbless/

### Environment Info

- Python Version: 3.7.1
- Sphinx Version: 2.0.1
- RTD Theme Version: 0.4.3

**Comment by agjohnson** [comment]
This doesn't look like an error related to the theme.

> got an unexpected keyword argument 'titles_only'

Are you using `titles_only` as an option to `toctree` directive? `titlesonly` is the correct option name if so.

**Comment by agjohnson** [comment]
Closing due to lack of response.
