### ISSUE TITLE
Set github_url on a directory level

### ISSUE THREAD

**Issue by OskarPersson** [readthedocs/sphinx_rtd_theme#751]
I know that I can set the `github_url` on a project level using `html_context` and on a file level using [File-wide metadata](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html?highlight=metadata#file-wide-metadata).

Is there anyway to set the `github_url` on a directory level such that all files inside the directory uses the specified URL as a base?

**Comment by stsewd** [comment]
I don't think there is an easy way, maybe you can automize this with a script to modify all pages inside a directory or maybe with a custom extension.

**Comment by stsewd** [comment]
This isn't related to the theme itself, so closing
