### ISSUE TITLE
Definition lists look different with sphinx 2.0

### ISSUE THREAD

**Issue by lazka** [readthedocs/sphinx_rtd_theme#752]
Example rst:

```
Foo:
    Bar
Bla:
    Blub
```

Before (1.8.3):

![old](https://user-images.githubusercontent.com/991986/56432229-e10bad00-62cc-11e9-9852-08166af08eb0.png)

Now (2.0.1):

![new](https://user-images.githubusercontent.com/991986/56432271-039dc600-62cd-11e9-8ca2-756b53bb3698.png)

**Comment by janheindejong** [comment]
Had the same... See https://github.com/rtfd/sphinx_rtd_theme/issues/750

**Comment by bikeshedder** [comment]
Sphinx 2.0 also causes very ugly looking footnotes:

![Screenshot from 2019-04-26 13-57-48](https://user-images.githubusercontent.com/1112569/56806131-59252600-682b-11e9-8faf-3ee9ebc56cb1.png)

**Comment by idnsunset** [comment]
Sphinx 2.0 changes class attribute from `docutils` to `class` in `<dl>` tag, which has style rule `.rst-content dl:not(.docutils)` get matched.
