### ISSUE TITLE
Working hot-reload converted over to webpack with all dependencies managed by yarn

### ISSUE THREAD

**Issue by SimonBiggs** [readthedocs/sphinx_rtd_theme#757]
No need to take any action on this, but I thought it might be of interest.

I forked this library and I wanted to be able to use webpack and yarn. I have managed to get everything installing and up and running (including a very fast (a second or two) hot-reload).

If you want to see the changes I made see the following:

https://github.com/pymedphys/pymedphys/tree/5168a77b3068ea4b247e11c62b60d92229271cb7/packages/pymedphys_sphinxtheme

**Comment by SimonBiggs** [comment]
I'd be happy to make a pull request into this repo if there was interest.

**Comment by jessetan** [comment]
This looks promising, is there anything in the gulp/browserify workflow that you have left out?

**Comment by SimonBiggs** [comment]
I don't think so. I did have to bump a few of the versions of certain dependencies, I visually tested the impact on chrome and Firefox on Linux and windows and saw no issues. But it is something to be aware of.

I can make a pull request and we can begin iterating on it if you like until you're happy with it?

**Comment by jessetan** [comment]
The current theme toolchain is becoming outdated and shows deprecation warnings when run. I'm in favor of moving to the next hot thing (tm), but would like feedback if this is in line with plans by RTD as a whole. Any opinions @ericholscher @agjohnson @humitos ?

**Comment by ericholscher** [comment]
I definitely agree we should try and standardize this with however we end up doing things in RTD. I don't really know this stuff too well, but @davidfischer or @agjohnson probably know best. We're doing a design project over there, which might also address this.

**Comment by davidfischer** [comment]
We are moving to webpack over the next few months for https://github.com/readthedocs/readthedocs.org (long overdue) so this seems in line with what we are thinking.

**Comment by SimonBiggs** [comment]
Okay I'd be happy to get the ball rolling with a pull request with how I achieved it?

**Comment by Blendify** [comment]
Yes please!

**Comment by SimonBiggs** [comment]
@Blendify done :) see https://github.com/readthedocs/sphinx_rtd_theme/pull/771

**Comment by agjohnson** [comment]
Closing this, the webpack conversion seems to be humming along quite nicely! :tada:

**Comment by SimonBiggs** [comment]
Glad to hear it :)
