### ISSUE TITLE
Open a 0.4.x release tracking branch and start work on 0.5 in master branch

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/sphinx_rtd_theme#759]
### Problem

I have a suggestion...

Because there are lots of unmerged, stale PRs targeted for a future milestone 0.5 which hasn't started its life-cycle: It would be easier for maintainers to keep working on the 0.4.x series for bug fixing in a separate branch, suggesting `releases/0.4.x` as the branch.

PyPi supports releasing old version numbers, e.g. a 0.4.4 release, even though 0.5 is out. In the beginning stages, you can also release for instance `0.5a1` and people can install it with `pip install sphinx_rtd_theme --pre`.

Also, there's a bit of cleanup for other bug/feature branches in this main repo that would help the overview :)

### Reproducible Project

n/a

#### Error Logs/Results

n/a

#### Expected Results

n/a

### Environment Info

n/a

**Comment by agjohnson** [comment]
I don't think we're going to jump on any changes to our branching pattern, but we are aiming to release more often to pypi under alpha releases. Some big changes are going through, so this won't be immediate, but we're moving to streamline things a bit in #379. Feel free to follow along there.
