### ISSUE TITLE
Sphinx doesn't find the theme after being installed

### ISSUE THREAD

**Issue by adrix71** [readthedocs/sphinx_rtd_theme#769]
Download the theme via pip and following the docs proposal on:

https://pypi.org/project/sphinx-rtd-theme/
https://sphinx-rtd-theme.readthedocs.io/en/latest/installing.html

this is the result.

![Schermata del 2019-06-17 20-33-39](https://user-images.githubusercontent.com/14064365/59628149-3aaf1d00-9140-11e9-800e-35c4f5b0c349.png)

Little question: 
But I hadn't already installed it via pip ???

No doubt about it, hahahahahahaha works just fine.

**Comment by davidfischer** [comment]
There does seem to be some sort of problem with your setup. Even in your screenshot, it looks like Sphinx 1.8.5 is installed but when you run `make html` it is using Sphinx 1.6.7.

**Comment by adrix71** [comment]
In the screen I show you all the sphinx packages installed in my system with version numbers.

I have no idea where I can get that version 1.8.5 that does not exist in my system or in the LinuxMint repositories.

Okay thanks for the reply. I give up and look for another documentation generator.

![Schermata del 2019-06-18 14-23-30](https://user-images.githubusercontent.com/14064365/59681873-3bde5980-91d5-11e9-8122-480d49b3286a.png)

**Comment by stsewd** [comment]
@adrix71 you should use a virtual environment to install your dependencies https://docs.python.org/3/library/venv.html

**Comment by agjohnson** [comment]
This looks to be an issue with the path of the binary that you are running locally, and not an issue with the theme. Virtualenv installation is likely to solve this issue. We don't support or maintain versions of this theme that were packaged for distributions, package installation is the correct method of installation.

The fact that your `make html` pass references an old Sphinx version likely means that the system level `sphinx-build` is being used, and `sphinx_rtd_theme` is not installed as a system level dependency.

Closing this as it doesn't seem to be a bug with the theme.
