### ISSUE TITLE
Define browser support for the theme

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#786]
We don't explicitly define the theme supported browsers anywhere. RTD has been moving towards only supporting IE >= 11, and we haven't yet defined Android browser support.

We should communicate what we officially support, what the last version to support $BROWSER_VERSION was, and what we allow for degradation on unsupported browsers.

Unsupported browsers might include behaviors such as unsupported typefaces (minor), improper positioning of block level elements (medium impact), and I'm sure some old version have trouble display anything at all.

Changes that we've discussed in the past that would affect these browsers:

* woff/woff2 font files only are not supported by IE < 9 or 10 and Android < 4.x. Both are small amounts of RTD annual traffic
* Remove modernizer
* etc

**Comment by jessetan** [comment]
Modernizr can actually be removed for all browsers, since we do not use its feature detection. The only thing from Modernizr that is used by IE <11 is html5shiv. There is a PR that removes Modernizr but keeps html5shiv #756

**Comment by agjohnson** [comment]
We could also probably drop html5shiv if we want to limit our browser focus. If we want to remove html5shiv, we should discuss our position on supporting the older non IE browsers as well. Those versions are:

> html5shiv provides basic HTML5 styling for Internet Explorer 6-9, Safari 4.x (and iPhone 3.x), and Firefox 3.x

**Comment by jessetan** [comment]
html5shiv include is guarded by `<!--[if lt IE 9]>`, so it is not loaded for any other browser

**Comment by humitos** [comment]
We do have a list of supported browsers now at https://sphinx-rtd-theme.readthedocs.io/en/stable/development.html#supported-browsers
