### ISSUE TITLE
Plotly plots rendered by nbsphinx not showing in sphinx_rtd_theme

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/sphinx_rtd_theme#788]
Hi... sorry I'm the Plotly guy _again_ :pray: You may remember me from such issues as https://github.com/readthedocs/readthedocs.org/issues/4367 https://github.com/readthedocs/sphinx_rtd_theme/issues/328 and others.

### Problem

Plotly plots rendered by nbsphinx show (both locally and remotely) when using Alabaster just fine, but they don't show at all when using sphinx_rtd_theme.

### Reproducible Project

* Repository: https://github.com/Juanlu001/rtd-js-test
* Project: https://readthedocs.org/projects/rtd-js-test/
* OK rendering: https://rtd-js-test.readthedocs.io/en/alabaster/
* No rendering: https://rtd-js-test.readthedocs.io/en/latest/

#### Error Logs/Results

Interestingly, the web developer console shows nothing with Alabaster, but with rtd_sphinx_theme shows a bunch of errors:

![Screenshot from 2019-07-20 19-43-53](https://user-images.githubusercontent.com/316517/61582102-c4c71880-ab26-11e9-9ac0-eafdfa03d415.png)

#### Expected Results

Plots should show regardless of the theme.

### Environment Info

- Python Version: 3.7.4
- Sphinx Version: 2.1.2
- RTD Theme Version: 0.4.3

**Comment by Juanlu001** [comment]
Commenting out this line brings Plotly back to life:

https://github.com/readthedocs/sphinx_rtd_theme/blob/bad21120c8d12b4dd15c6b5383dd3fe5909def56/sphinx_rtd_theme/layout.html#L57

And, looking at `theme.js`, it seems that `require` is already defined there:

https://github.com/readthedocs/sphinx_rtd_theme/blob/bad21120c8d12b4dd15c6b5383dd3fe5909def56/sphinx_rtd_theme/static/js/theme.js#L3

Notice that Plotly needs `require.js`, but the `require` defined in the `sphinx_rtd_theme` seems to be not compatible with it. If I comment out the `require.js` import:

![Screenshot from 2019-07-21 01-40-02](https://user-images.githubusercontent.com/316517/61585307-7a5e8f80-ab58-11e9-9616-6081cebe1346.png)

Therefore I tried something crazy:

```
$ sed -i 's/require/require_rtd/g' _static/js/theme.js
```

And now everything works like a charm.

**Comment by humitos** [comment]
Using Google Chrome, one thing that I found is that `plotly.js` is giving 404 and that's why it does not render properly on `readthedocs theme`

But, if you look closer, `alabaster` version loads https://cdn.plot.ly/plotly-latest.min.js, but `readthedocs theme` _tries_ to load https://rtd-js-test.readthedocs.io/en/latest/plotly.js

Both themes load the same version of `require.js` from https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js so I don't this is the problem.

I'm not sure, but I think what it's overlapping here is `require` module from Browserify from the Read the Docs Sphinx Theme --used [here for example](https://github.com/readthedocs/sphinx_rtd_theme/blob/bad21120c8d12b4dd15c6b5383dd3fe5909def56/js/theme.js#L1)-- with `require` variable defined by `require.js`.

And... it seems to be a known issue: https://stackoverflow.com/a/25586213. They say that the solution could be to use `window.require` instead of `require` in the Javascript code from Read the Docs Theme.

There are more context about this on a issue on Browserify repo: https://github.com/browserify/browserify/issues/790

It _seems_ this is a potential good reason about why this is failing on Read the Docs Sphinx (BTW, alabaster does not include any JS at all).

**Comment by jessetan** [comment]
This is a good issue to revisit after #771 is merged which moves our build process to webpack, without browserify

**Comment by nvaytet** [comment]
Hi, we are also trying to use `plotly` on our documentation pages (https://scipp.readthedocs.io/en/latest/user-guide/plotting.html#Plotting-data-with-3-and-more-dimensions).
I see that #771 was merged in July. Does this mean that in principle `plotly` should now just work if the Pypi package gets updated? Or does it mean that more work is required to get this working?
Thanks!

**Comment by Juanlu001** [comment]
If anything, probably this issue is not blocked anymore?

**Comment by lpravda** [comment]
Hi all, is there any update on this? pypi has not been updated since last year, and if I clone the master branch and use this, it still exhibits the same issue.

Thank you :)!

**Comment by ociule** [comment]
Hi, it's a pity this hasn't been fixed yet.

What works for me is a variant of https://github.com/plotly/plotly.py/issues/1033#issuecomment-402894617

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js"></script>
<script>require=requirejs;</script>
```

I add this in my notebooks through a raw html include file directive.

Note that if your notebooks use plotly.graph_objects.FigureWidget instead of Figure, this bug is not an issue.

**Comment by jaladh-singhal** [comment]
Is there any progress on this issue?

**Comment by jaladh-singhal** [comment]
Thank you so much @ociule, after quite a lot of struggle, your workaround works like charm!

> <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js"></script>
> <script>require=requirejs;</script>
> I add this in my notebooks through a raw html include file directive.

For others who might be confused about how to insert this in a specific notebook (like I was), use `Raw NBConvert` cell - it doesn't get displayed & code inside it gets executed, when converted to HTML.

**Comment by jorgepiloto** [comment]
Hi all! Its Jorge, from the [poliastro](https://github.com/poliastro/poliastro) dev team (working with @astrojuanlu).

I saved a plotly figure in `html` format. Then, it is supposed this should be displayed if using:

```rst
.. raw:: html
    :file: path/to/file.html
```

However, once documentation is built, it only shows a white space were the figure should be displayed. I found that the following error was raised when inspecting that web element:

```
ReferenceError: Plotly is not defined
```

I am not an expert on Javascript or web development. After a little search on the web, found the following exaplantion, see [here](https://stackoverflow.com/questions/45868530/why-am-i-getting-an-uncaught-referenceerror-plotly-is-not-defined):

```
That can only mean that the event handler is executed before plotly is fully loaded.
```

**If adding `<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>` at the top of the index.html file the figure was finally properly rendered.**

Maybe people with more experience on Javascript could have a better understanding about what is going on with this. Just posted this so it might be helpful :sweat_smile:

**Comment by astrojuanlu** [comment]
Notice that my original issue uses nbsphinx (which I failed to mention in the description of this issue, I will change that accordingly) so @jorgepiloto case might be slightly different.

**Comment by astrojuanlu** [comment]
I just tested `sphinx_rtd_theme==0.5.0rc1` and the issue is fixed, along other minor annoyances! Thanks a lot for the RTD team for maintaining the best Sphinx theme out there :heart:

**Comment by jorgepiloto** [comment]
:tada:

**Comment by sandipde** [comment]
This indeed solved the issue of showing the plotly figures and everthing works ! However, it's quite weired that it still complains about missing  plotly.js .

**Comment by layne-sadler** [comment]
Browser inspect console errors
```
Failed to load resource: the server responded with a status of 404 ()

require.min.js:1 Uncaught Error: Script error for "plotly"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js:1)
    at HTMLScriptElement.onScriptError (require.min.js:1)
```
`docs/requirements.txt`
```
ipython==7.19.0
nbsphinx==0.8.0
sphinx_copybutton==0.3.1
sphinx_rtd_theme==0.5.0
sphinxext-opengraph==0.4.1
```

**Comment by layne-sadler** [comment]
Okay so this in conf.py gets me past the initial `require.min.js` error:
```
nbsphinx_requirejs_options = {
	"src": "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js",
	"integrity": "sha512-VCK7oF67GXNc+J7zsu5o57jtxhLA75nSMHGaq8Q8TCOxDj4nMDw5dhQZvm9Cd9RN+3zgcodqbKcRc9gyPP8a2w==",
	"crossorigin": "anonymous"
}
```

But then I get a new error that feels more specific to plotly. Obviously I don't have the raw js file in my `docs/_build/html/notebooks` folder 
```
VM58 require.min.js:34 GET file:///Users/layne/Desktop/aiqc/docs/_build/html/notebooks/plotly.js net::ERR_FILE_NOT_FOUND
h.load @ VM58 require.min.js:34
load @ VM58 require.min.js:29
load @ VM58 require.min.js:18
fetch @ VM58 require.min.js:17
check @ VM58 require.min.js:19
enable @ VM58 require.min.js:23
enable @ VM58 require.min.js:27
(anonymous) @ VM58 require.min.js:23
(anonymous) @ VM58 require.min.js:8
v @ VM58 require.min.js:7
enable @ VM58 require.min.js:22
init @ VM58 require.min.js:17
(anonymous) @ VM58 require.min.js:26
setTimeout (async)
h.nextTick @ VM58 require.min.js:32
g @ VM58 require.min.js:26
requirejs @ VM58 require.min.js:31
(anonymous) @ visualization.html:1001
VM58 require.min.js:8 Uncaught Error: Script error for: plotly
http://requirejs.org/docs/errors.html#scripterror
    at C (VM58 require.min.js:8)
    at HTMLScriptElement.onScriptError (VM58 require.min.js:29)
```

**Comment by miohtama** [comment]
Although this is a closed issue, it still popups, as require.js is somewhat difficult to work with. We had this is issue for both `sphinx_rtd_theme` and `furo` theme in 2022. Here is our solution:

* Server `require.js` locally from Sphinx `_static` folder
* Configure `require` by using custom.js

Example `conf.py`:

```python
html_js_files = [
    "require.min.js",  # Add to your _static
    "custom.js",
]

```

Example custom.js:

```javascript
requirejs.config({
    paths: {
        base: '/static/base',
        plotly: 'https://cdn.plot.ly/plotly-2.12.1.min.js?noext',
    },
});
```

This way

* Notebook correctly renders interactive diagrams when running in Jupyter
* Notebook correctly renders interactive diagrams when viewed as static HTML files
* Notebook correctly renders interactive diagrams when viewed on ReadTheDocs
