### ISSUE TITLE
jQuery version is vulnerable

### ISSUE THREAD

**Issue by RDIL** [readthedocs/sphinx_rtd_theme#789]
### Problem

jQuery needs to be updated so security vulnerabilities can be patched.

### Reproducible Project

filehandlers.readthedocs.io - lighthouse audit shows it is present

#### Error Logs/Results

https://snyk.io/vuln/npm:jquery?lh=3.2.1

**Comment by agjohnson** [comment]
This theme does not directly include JQuery, we treat it as an external include brought in via `window`/`global`. JQuery 3.2.1 is instead added with the base Sphinx theme: https://github.com/sphinx-doc/sphinx/blob/master/sphinx/themes/basic/static/jquery-3.2.1.js

It's probably best to follow up there.
