### ISSUE TITLE
can content of genindex be altered with this theme?

### ISSUE THREAD

**Issue by slestak** [readthedocs/sphinx_rtd_theme#792]
Wanted to change the results of the genindex page and wasnt sure if that was in scope for the theme.  I see one other theme in the builtins (basic) that appears to do this.

The change I was going to implement was displaying the index target description instead of the integer counter that appears now.

**Comment by agjohnson** [comment]
I don't think we've tried this at all, but I don't necessarily see something blocking.

If you'd like to take a swing at this, it would help to start by showing what we have now and what is likely to change. This theme supports a wide number of projects, so for a change to be accepted, it must work in the most general of cases. So, that is the main thing we'd be looking at with any major overhaul of a template page.

**Comment by slestak** [comment]
I think I know what might do it. Let me try this and I'll PR it and we can discuss if I'd something that can/should be done. I'm already looking at how it could be controlled by a config item so it would def be optional.

**Comment by slestak** [comment]
Mainly was just asking to see if i was missing something obvious that was already present.

**Comment by agjohnson** [comment]
Not that I know of, you should just be able to override the `genindex.html` file. We just don't have an override because we've never done anything with the file yet. Let us know what you come up with, we're open to additions here!

**Comment by agjohnson** [comment]
Going to close this for now. We can reopen if there is some movement on the feature addition.
