### ISSUE TITLE
The icon for note doesn't work (shows bad unicode char)

### ISSUE THREAD

**Issue by wraithan** [readthedocs/sphinx_rtd_theme#8]
![screen shot 2013-10-26 at 3 53 11 pm](https://f.cloud.github.com/assets/90898/1414560/76e6cc70-3e92-11e3-8bdb-cf421f394ca5.png)
Looking at 1 in the top left. I am on a pretty bare OSX Lion install using Firefox

**Comment by adrian5** [comment]
In case anyone presently runs into this issue reading offline documentation, I want to add that Firefox has a [security setting](https://developer.mozilla.org/en-US/docs/Same-origin_policy_for_file:_URIs) that can cause this. The setting can be disabled, as described in the article.
