### ISSUE TITLE
Definition list display different in Sphinx 2.1

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#800]
In Sphinx 1.8:
![image](https://user-images.githubusercontent.com/1140183/61916319-4b07a400-af05-11e9-908c-ceb4013baf4f.png)

In Sphinx 2.1, the domain styling leaks through:
![image](https://user-images.githubusercontent.com/1140183/61916352-6a9ecc80-af05-11e9-9e76-8ad243e1c846.png)

Also affects field lists in the same way:
![image](https://user-images.githubusercontent.com/1140183/61916487-f7498a80-af05-11e9-8d8e-b99a216bb012.png)

**Comment by zaneselvans** [comment]
Whew, running into the same issue. I was starting to think I was crazy.

**Comment by DrLuke** [comment]
Ran into same issue. In the meantime: Is there a suggested workaround for this?
