### ISSUE TITLE
Sidebars have extra spacing on the bottom margin in Sphinx 2.1

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#803]
Sphinx 1.8:
![image](https://user-images.githubusercontent.com/1140183/61916708-ca49a780-af06-11e9-8585-bc64828c56cc.png)

Sphinx 2.1:
![image](https://user-images.githubusercontent.com/1140183/61916686-b736d780-af06-11e9-944f-48301de7fcc6.png)

**Comment by return42** [comment]
My interim solution was adding a `theme_overrides.css`

```python
html_context  = { 'css_files': [ 'theme_overrides.css' ] }
```
and remove the bottom padding from class sidebar:

```CSS
.rst-content .sidebar {
    padding: 20px 20px 0px 24px;
}
```

Not perfect, but helps for the first.
