### ISSUE TITLE
A button for removing `highlight` content from the page

### ISSUE THREAD

**Issue by dojutsu-user** [readthedocs/sphinx_rtd_theme#816]
It would be nice to have a button or something else which removes the highlighted content from the page.

![63571884-243d9b80-c59f-11e9-9fbf-b0f34f6533c8](https://user-images.githubusercontent.com/29149191/64588323-bcb98580-d3bf-11e9-9f95-97dde25f0bc3.gif)
_(link: http://2.python-requests.org/en/master/user/quickstart/?highlight=payload#passing-parameters-in-urls)_

Ref: https://github.com/readthedocs/readthedocs.org/pull/6087

**Comment by agjohnson** [comment]
I missed the underlying change here. I'm -1 on this change and -1 on the underlying removal of the search highlighting. The link in this case is not easy to find for users, it is superfluous for most users, and there is better UX to display that we are showing search results. Additionally, search results should be able to highlight across themes in similar ways, so this is an RTD problem.

We need to revisit the search highlighting in RTD, there are better ways to accomplish whatever problem we were hitting with search. Going to close this as I don't think this is a good answer and would be a theme dependent fix to a platform problem.

**Comment by mgeier** [comment]
See #876 for a possible implementation.
