### ISSUE TITLE
Rendering definitions list in bold

### ISSUE THREAD

**Issue by pmantica1** [readthedocs/sphinx_rtd_theme#819]
How can I render definition list terms in bold as in https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/lists_tables.html#definition-lists ?

**Comment by agjohnson** [comment]
This question isn't clear, so I'm not sure the best way to guide you. Could you provide more information or and example?

**Comment by pmantica1** [comment]
It was because I was using version 2.0 of Sphinx.
