### ISSUE TITLE
Possible path error?

### ISSUE THREAD

**Issue by pedro-w** [readthedocs/sphinx_rtd_theme#831]
Not sure if this is intentional or not but in this line:
https://github.com/readthedocs/sphinx_rtd_theme/blob/ddf840cb7206d7c45270560f077b12daa147f915/docs/conf.py#L51
`html_theme_path` points to a directory outside the repo. So on my system when I build I get warnings like
```
WARNING: file 'imlv.zip' on theme path is not a valid zipfile or contains no theme
```
where `imlv.zip` just happens to be a zip file with the same parent directory as `sphinx_rtd_theme`.

**Comment by agjohnson** [comment]
You may be right, though I also think that option doesn't have any effect locally or on the RTD hosted version. Locally, we import the template after appending the local path to the theme (`../`) -- here: https://github.com/readthedocs/sphinx_rtd_theme/blob/ddf840cb7206d7c45270560f077b12daa147f915/docs/conf.py#L8

On RTD, the theme is installed from PyPI, and so the `html_theme_path` option isn't used there either.

Perhaps try removing the option and see if that breaks anything. My guess is it should work both locally and on RTD.

**Comment by agjohnson** [comment]
I ended up testing this in #838 and the line is removed there. Change looks good so far

**Comment by pedro-w** [comment]
Sorry I didn't get back to you on this. I did do some testing and as far as I could see it didn't cause any problems - but on the other hand I couldn't make it do anything terrible by having a wayward zip in the parent folder. Removing the line does stop that warning appearing though, so I think it's worth doing.
