### ISSUE TITLE
Duplicated fields in _theme_layout.sass

### ISSUE THREAD

**Issue by 1138-4EB** [readthedocs/sphinx_rtd_theme#837]
Some fields in `_theme_layout.sass` are duplicated. For example:

https://github.com/readthedocs/sphinx_rtd_theme/blob/db0f25787cefe0480b91db9b5346cf712d8a18c2/src/sass/_theme_layout.sass#L172-L175

https://github.com/readthedocs/sphinx_rtd_theme/blob/db0f25787cefe0480b91db9b5346cf712d8a18c2/src/sass/_theme_layout.sass#L179-L182

**Comment by agjohnson** [comment]
Besides `color`, those properties are duplicated needlessly, yeah.

**Comment by 1138-4EB** [comment]
Other duplicates/uneffective properties:

- https://github.com/readthedocs/sphinx_rtd_theme/blob/master/src/sass/_theme_layout.sass#L36
- https://github.com/readthedocs/sphinx_rtd_theme/blob/master/src/sass/_theme_layout.sass#L152
