### ISSUE TITLE
Latex translation of "continue on next page" not available in Chinese (zh_CN and zh_TW)

### ISSUE THREAD

**Issue by iruletheworld** [readthedocs/sphinx_rtd_theme#841]
### Problem

I have made two documents with Latex PDF using the RTD theme with zh_CN and zh_TW. When the code block is too large for the current page, it countines on to the next page. I would expect the "continue on next page" be translated into zh_CN and zh_TW, but it is not. Though the "continued from previous page" is translated correctly.

### Reproducible Project

Project on RTD : [latex2img](https://readthedocs.org/projects/latex2img/)

Project on GitHub : [latex2img](https://github.com/iruletheworld/latex2img)

#### Error Logs/Results

![Screenshot](https://3nmlaq.am.files.1drv.com/y4mPSq2zucDKmbNPcSHCRvQXhiW1tme4nShlaPWhBA-cVjfMBq3A_flx99OQNIkBThY65-k3ih6BC7wtnHs59JxxXWeSPZbJLaxDCGr65h0ygQiFGnHvF8-SOe29SXcQKXgfQ-8jgLyjiI2TXEftuPbmpTChhiilsg_GuMt7LgahTjbGTxMCWK4KsT25w4OaCOYlEhVeAeL5QR04CpgAO9-CQ?width=313&height=529&cropmode=none)

#### Expected Results

It should be translated as "繼續到下一頁 " for zh_TW and "继续到下一页" for zh_CN or similar.

### Environment Info

- Python Version: 3.7
- Sphinx Version: 1.8.5
- RTD Theme Version:  0.4.3

**Comment by jessetan** [comment]
This is an issue of Sphinx' LaTeX output and is addressed by https://github.com/sphinx-doc/sphinx/issues/3791. It's not an issue of this theme, which only influences styling of HTML output.
Closing this.
