### ISSUE TITLE
Code blocks are not rendered correctly

### ISSUE THREAD

**Issue by fladd** [readthedocs/sphinx_rtd_theme#850]
### Problem

Code blocks are not rendered as they used to. They now look like the default Sphinx theme (green background):

<img width="744" alt="image" src="https://user-images.githubusercontent.com/2971539/67680384-6ca47b80-f98b-11e9-9cc4-fccd37b6944c.png">

#### Expected Results

Should look like this:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/2971539/67680438-880f8680-f98b-11e9-901c-7bea2ea9859d.png">

### Environment Info

- Python Version: 3.7.4
- Sphinx Version: 2.2.0
- RTD Theme Version: 0.4.3

**Comment by agjohnson** [comment]
I don't see the same issue, either with master or #838. Can you confirm? We could use more information to track this down, so please include any links you have in your report.

**Comment by clefebvre** [comment]
It's happening for us as well. Here's an example: https://linuxmint-installation-guide.readthedocs.io/en/latest/verify.html

**Comment by stsewd** [comment]
The latest build from that project was a year ago https://readthedocs.org/projects/linuxmint-installation-guide/builds/

Code-blocks look fine with the latest version https://docs.readthedocs.io/en/stable/api/v3.html#projects
