### ISSUE TITLE
Permalink shown with two symbols

### ISSUE THREAD

**Issue by fladd** [readthedocs/sphinx_rtd_theme#851]
### Problem

The permalinks are shown with both the paragraph (default Sphinx theme) and the Github-style link symbol (RTD theme):

<img width="163" alt="image" src="https://user-images.githubusercontent.com/2971539/67891433-e175e200-fb52-11e9-8f74-b86e984be597.png">

#### Expected Results

Only Github-style link symbol.

### Environment Info

- Python Version: 3.7.5
- Sphinx Version: 2.2.1
- RTD Theme Version: 0.4.3

**Comment by polyzen** [comment]
This is already fixed in master.
