### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by wrong-about-everything** [readthedocs/sphinx_rtd_theme#854]
### Problem

It seems that my project [is not indexed by Google](https://www.google.ru/search?q=site%3Avalidol.readthedocs.io+validation), though quite a decent amount of time passed since I've first committed a meaningful piece of text.

### Reproducible Project

[Here it goes!](https://validol.readthedocs.io/en/latest/)

#### Expected Results

My project is searched.

### Environment Info

- Python Version: 2.7.15
- Sphinx Version: 1.8.5
- RTD Theme Version: 0.4.3

**Comment by alexsuter** [comment]
has nothing todo with the sphinx_rtd_theme

**Comment by stsewd** [comment]
Hi @wrong-about-everything, this isn't a issue with the theme. But you can check the rtd guide for SEO https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html

**Comment by wrong-about-everything** [comment]
Thanks!
