### ISSUE TITLE
How to - links to translations

### ISSUE THREAD

**Issue by pierreozoux** [readthedocs/sphinx_rtd_theme#857]
### Problem

As a user of rtd theme, how can we add a link to the translated versions?

ReadTheDocs takes the example of phpmyadmin for that, here is a screenshot of the feature.

![image](https://user-images.githubusercontent.com/1863453/68679530-55a38300-0560-11ea-9b9b-979ef6b1cc0d.png)

### Solution

Is it implemented here as well, or just on the hosted version? I searched issues, code and documentation, I didn't find this feature.

I'm asking to improve [Nextcloud documentantion](https://docs.nextcloud.com/server/17/user_manual/).

Thanks for your help!

**Comment by agjohnson** [comment]
This is only a feature of Read the Docs currently. We're discussing whether the flyout menu should be separate from the theme or not, as there is confusion here about where this is rendered right now.

You can manually manipulate a `_templates/versions.html` to accomplish what you're looking for either way though, but that is outside the scope of what core team supports.
