### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by xavfernandez** [readthedocs/sphinx_rtd_theme#859]
Hello and thanks for the project.

Is a new release planned in the near future ?
It will soon be 10 months since 0.4.3 was released and quite a few commits have been added: https://github.com/readthedocs/sphinx_rtd_theme/compare/0.4.3...master

Cheers :)

**Comment by agjohnson** [comment]
Already covered in a few places. Yes, but we are aiming to fix Sphinx 2/html 5 writer issues with the release.
