### ISSUE TITLE
Flash of unformatted text on offline documentation

### ISSUE THREAD

**Issue by MauroPfister** [readthedocs/sphinx_rtd_theme#861]
### Problem

I have created a very simple documentation that I view **offline** (by opening `index.html`). While loading a page (refresh or selecting a different page under content) the text on the page is quickly displayed in the standard (chrome) font and then changes to the RTD theme font.

When I remove all fonts from the `build/html/_static/css/fonts` folder, the flickering disappears but the page obviously does not look as nice as with the theme fonts. 

### Reproducible Project

I put a minimal example on my github: https://github.com/MauroPfister/rtd_test_doc/tree/master

It was created using `sphinx-quickstart` with default setting except separating source and build directories. I also placed the most recent RTD theme from github in a `_themes` folder because the pip version of RTD does not yet contain the fix #848.

#### Expected Results

Text should not be loaded with two different fonts (no flashing).

### Environment Info

- Python Version: Python 3.6.9
- Sphinx Version:  2.2.1
- RTD Theme Version: ab7d388448258a24f8f4fa96dccb69d24f571736

**Comment by Blendify** [comment]
Fixed in d8bd069e52890da56eeb9cc338b1ea72eb50f32a
