### ISSUE TITLE
Deploy the Sphinx RTD Theme with navigation outside of readthedocs

### ISSUE THREAD

**Issue by zonca** [readthedocs/sphinx_rtd_theme#868]
I would like to build the documentation on Travis and deploy on Github pages, so that I don't need to maintain the build environment also on readthedocs.

Is there a way to get the readthedocs navigation menu (see screenshot attached) with links to all the previous versions of the documentation? Would you have a pointer to a tutorial or docs about that?

Thanks!

![image](https://user-images.githubusercontent.com/383090/72464505-40c6b400-378a-11ea-80b3-ebd641c52e58.png)

**Comment by eine** [comment]
@zonca, see https://github.com/readthedocs/sphinx_rtd_theme/pull/574#issuecomment-368981832, https://github.com/readthedocs/sphinx_rtd_theme/pull/578#issuecomment-368992745 and https://github.com/readthedocs/readthedocs-build/issues/35#issuecomment-353999374.

**Comment by zonca** [comment]
thanks
