### ISSUE TITLE
Glossary visual style improvement & Highlight HTML target

### ISSUE THREAD

**Issue by exhuma** [readthedocs/sphinx_rtd_theme#877]
### Problem

When following the link to a glossary term, the term is not highlighted.

#### Expected Results

The term should be visually highlighted

### Environment Info

- Python Version: 3.5
- Sphinx Version: 2.3.1
- RTD Theme Version: 0.4.3

I have played around with the following [custom CSS](https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html) which yields results that I personally find very pleasing. I wanted to create a PR for this, but was unable to get it to work with the SASS source (I have zero experience with SASS). Unfortunately the `!important` modifiers were necessary to make this work with a custom style file.

```
DL.glossary DT:target + DD {
    border: 1px solid #d3d381;
    background: #ffc;
    padding: 1em;
}

DL.glossary DT {
    border: 0 !important;
    background: inherit !important;
    border-bottom: 1px solid #c3c0ee !important;
    display: block !important;
}
```

This gives a glossary like the following:

![Screenshot](https://i.imgur.com/BY8VYlS.png)

This might also be slightly related to #278

**Comment by stsewd** [comment]
This is currently displayed like:

[Uploading Screenshot_2020-10-07 3 Paragraph Level Markup — Read the Docs Sphinx Theme 0 5 0 documentation.png…]()

https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/demo.html#glossary

But, yeah, it has the problem described in https://github.com/readthedocs/sphinx_rtd_theme/issues/278

**Comment by exhuma** [comment]
I don't think this should have been closed. This is completely different from #278 

The issue I mentioned is that landing on a glossary page the targeted term (via the URL fragment) _is not highlighted_. It has nothing to do with the overall list-styling!

**Comment by stsewd** [comment]
I think you mean https://github.com/readthedocs/sphinx_rtd_theme/issues/869

**Comment by exhuma** [comment]
Well, you yourself added the link to #278 above :wink: 

But yes, you are correct, #869 is indeed a duplicate of this one.

Did you consider adding my proposed CSS change?

**Comment by stsewd** [comment]
Sorry, I misunderstood your description. I'm not that familiar with css, but I'll link your solution in the other issue.

**Comment by exhuma** [comment]
Thanks.
