### ISSUE TITLE
Problem with display of nav bar

### ISSUE THREAD

**Issue by mikehagerty** [readthedocs/sphinx_rtd_theme#879]
I want to have a navbar that drops down ~ 7 levels.

So I set the following in my conf.py
>  html_theme = 'sphinx_rtd_theme'
  html_theme_options = {
     'navigation_depth': -1,
 }

And then I styled my headers accordingly.
The navigation bar should look like:
><Preamble>
    <Network>
        <Station>
            <Channel>
                <Response>`

The result is after about level=Network, the navbar simply opens all lower levels and displays them flush left (see attached file).  The links to the section all operate correctly, but the navigation display is a mess.

![fig1](https://user-images.githubusercontent.com/2146498/74677794-52371d80-5187-11ea-862b-3d6f981600f1.png)

If I simply switch the html_theme to alabaster, it displays correctly.

![fig2](https://user-images.githubusercontent.com/2146498/74677836-6713b100-5187-11ea-91ec-3fac48cd795b.png)

I don't know if this is an issue in the theme itself or if I need
to do something else to get it to render correctly.
Any help would be greatly appreciated!

Name                    Version                   Build  Channel
sphinx                             2.3.0                    py_0
sphinx-rtd-theme          0.4.3                    pypi_0    pypi

**Comment by Blendify** [comment]
Fixed with ca015a57042713ebd7f39563cdb01fab5b604051

**Comment by mikehagerty** [comment]
Hi. Thanks for fixing the navbar issue. It works now, but not perfectly. 
For instance, I have a nav with 7 depths.  If I click on either the 6th element (which
contains 1 subelement) or the 7th (contains no subelements), it closes those
elements in the nav and the resulting nav bar shows only higher levels.
I expected that if I click on an element name in the nav bar, the focus in the main page would move to that element header in the page, which it does for some elements.

To be clear, I am clicking on the element name, not on the '+/-' to open/close the element.
