### ISSUE TITLE
Formatting problems with singlehtml output

### ISSUE THREAD

**Issue by JamesRandom** [readthedocs/sphinx_rtd_theme#881]
The formatting of HTML files generated using the singlehtml builder is different from that produced by the html builder.

The most obvious example is image captions, where the size is 16px in html but has 150% scaling applied in singlehtml (see images).

This seems to be because the content is wrrapped in a `div.toctree-wrapper`. I don't know what the purpose of that is, or why it only appears in the singlehtml output.

The caption is created in the usual way. The output was generated using a minimal `conf.py` and `Makefile` generated by `sphinx-quickstart`.

```rst
.. figure:: Untitled.png
    :align: center

    Caption: An example image
```

[rst-png-files.zip](https://github.com/readthedocs/sphinx_rtd_theme/files/4231188/rst-png-files.zip)

![html](https://user-images.githubusercontent.com/11873471/74943477-ba3e6b80-53f4-11ea-8b4e-dc9f26ac1d99.png)
![singlehtml](https://user-images.githubusercontent.com/11873471/74943480-bc082f00-53f4-11ea-8db1-72d06d1145f1.png)

#### Expected Results

The formatting in html and singlehtml output should be the same.

### Environment Info

- Python Version: 3.7.6
- Sphinx Version: 2.4.2
- RTD Theme Version: 0.4.3

MacOS Catalina

**Comment by Blendify** [comment]
Fixed in e873694
