### ISSUE TITLE
Inline Markup: Is resizing the window or zooming way out by design?

### ISSUE THREAD

**Issue by pzrq** [readthedocs/sphinx_rtd_theme#884]
### Problem

I need to make the browser window very wide and also zoom out from 100% to say 50% on some RTD sites to read all the inline markup.

### Reproducible Project

If I'm reading this correctly, the wording suggests this is by design, but I wanted to confirm before digging deeper, as it feels like a very poor user experience:

> Let’s test wrapping and whitespace significance in inline literals: 
> This is an example of --inline-literal --text, --including some-- strangely--hyphenated-words. Adjust-the-width-of-your-browser-window to see how the text is wrapped.  -- ---- --------  Now note    the spacing    between the    words of    this sentence    (words should    be grouped    in pairs).

https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/demo.html#inline-markup
https://runswift.readthedocs.io/en/latest/3d_simulation.html#running-the-visualiser-roboviz

#### Error Logs/Results

Place any images or error logs that might be able to help solve the issue here.

<img width="1329" alt="Screen Shot 2020-03-04 at 11 38 07 am" src="https://user-images.githubusercontent.com/1217010/75833627-b4da1b80-5e0d-11ea-832d-b0f109631af1.png">

#### Expected Results

Please describe how this should work properly.

Naively removing `whitespace: nowrap;` would allow the long inline text to remain readable without making the window wider and/or zooming out, e.g. in Firefox's debugger, before/after:

<img width="872" alt="Screen Shot 2020-03-04 at 11 49 57 am" src="https://user-images.githubusercontent.com/1217010/75833816-55304000-5e0e-11ea-93c5-62bcc42f3ed9.png">
<img width="870" alt="Screen Shot 2020-03-04 at 11 50 09 am" src="https://user-images.githubusercontent.com/1217010/75833819-56fa0380-5e0e-11ea-92e1-d455251afccc.png">

However that seems incomplete as it wouldn't keep the words grouped in pairs on window resize, as per the spec quoted above. I'm not sure if, and if so how to proceed - suggestions welcome.

### Environment Info

- Python Version: (not sure - hosted)
- Sphinx Version: (not sure - hosted)
- RTD Theme Version: (not sure - hosted)

**Comment by stsewd** [comment]
I think this is a bug, from the text it says `Adjust-the-width-of-your-browser-window to see how the text is wrapped` but the text isn't wrapped.

**Comment by Blendify** [comment]
This has been fixed with https://github.com/readthedocs/sphinx_rtd_theme/commit/d91d7e13b3283b76e49cc6dd23a2d2afbd64c577
