### ISSUE TITLE
Pull new translations from Transifex

### ISSUE THREAD

**Issue by akien-mga** [readthedocs/sphinx_rtd_theme#890]
### Problem

Transifex has 100% complete translations for some locales which have yet to be synced into this repository and deployed in a release:

- https://www.transifex.com/readthedocs/sphinx-rtd-theme/
- https://github.com/readthedocs/sphinx_rtd_theme/tree/master/sphinx_rtd_theme/locale

Missing locales from Tx seem to be:
- fr
- pt_BR
- tr
- zh_CN

If there's interest I can likely mobilize some translators to add other locales on Transifex too, at least the ones matching the most advanced locales from the Godot docs: https://hosted.weblate.org/projects/godot-engine/godot-docs/ (ja, ko, pl, uk)

**Comment by agjohnson** [comment]
Translations were not 100% complete, they lacked review. I updated everything in #909 and added the new translations
