### ISSUE TITLE
Add HTML to all pages

### ISSUE THREAD

**Issue by KoalaGeo** [readthedocs/sphinx_rtd_theme#894]
Hi, 

Please could you advise - how/where would I add the below snippits of HTML to each page when I build from .rst? 

I wan't a tracking pop up to appear using the below code. 

<head>
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
</head>

<body class="wy-body-for-nav">
<script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
<script>
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#000"
    },
    "button": {
      "background": "#f1d600"
    }
  },
  "content": {
    "href": "https://www.bgs.ac.uk/help/privacy.html"
  }
});
</script>
</body>
</html>

Thank you,

**Comment by agjohnson** [comment]
You can extend the layout.html. I'd suggest reading the docs on Sphinx templating for more information on how Sphinx themes work.
