### ISSUE TITLE
How to remove .html suffix from URL?

### ISSUE THREAD

**Issue by MatinF** [readthedocs/sphinx_rtd_theme#902]
### Problem

I'm using the `rtd_sphinx_theme` and would like to structure my project as follows:

```
index.rst
about-manual.rst
```
Inside my root `index.rst`, the toctree is as below:
```
===========================
Contents
===========================

.. toctree::

   about-manual

```
This results in the below links:

```
https://example.com/docs/                                --> https://example.com/docs/ (content of index.rst)
https://example.com/docs/about-manual         --> ERROR
https://example.com/docs/about-manual.html --> https://example.com/docs/about-manual.html (content of about-manual.rst)
```
I was hoping to be able to instead achieve the following logic

```
https://example.com/docs/                                --> https://example.com/docs/ (content of index.rst)
https://example.com/docs/about-manual         --> https://example.com/docs/about-manual (content of about-manual.rst)
https://example.com/docs/about-manual.html --> https://example.com/docs/about-manual (content of about-manual.rst)
```

I've tried using the `html_file_suffix` and `html_link_suffix`, but without luck. My problem with the default behavior is that a user would intuitively use a link style like `https://example.com/docs/about-manual`, which returns an error in this case.

Sorry if this is not `rtd_sphinx_theme` specific, I'm a bit unsure if this is related to the general Sphinx setup or the theme. I'm using Sphinx `1.8.5`.

**Comment by jessetan** [comment]
This is indeed not theme-specific. You can build with `sphinx-build -b dirhtml` (instead of `html`), see
https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.dirhtml.DirectoryHTMLBuilder

**Comment by MatinF** [comment]
Thanks for answering this anyway, it was immensely helpful!
