### ISSUE TITLE
Sphinx theme option "prev_next_buttons_location" does not work

### ISSUE THREAD

**Issue by gthvidsten** [readthedocs/sphinx_rtd_theme#903]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/cambion/

## Expected Result

`html_theme_options` in `conf.py` should be applied

## Actual Result

I added `html_theme_options` to my `conf.py` file as per the instruction for the RTD sphinx theme: https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html

```
html_theme_options = {
    'collapse_navigation': False,
    'prev_next_buttons_location': 'None'
}
```

This has no effect. I haven't come far enough in the documentation that I have enough levels to test the first option yet, but the second option, `prev_next_buttons_location`, should have removed the Next/Previous buttons from the generated documentation. These buttons are still there when the documentation is built.

**Comment by mondeja** [comment]
I can't reproduce this issue with Sphinx  `1.8.5` and sphinx_rtd_theme `0.4.3`. Have you added the line `html_theme = "sphinx_rtd_theme"` to your `conf.py` file?

**Comment by gthvidsten** [comment]
No, I haven't. I thought that was the default theme that didn't need to be inlucded.
Am I supposed to use that line even though it is the default to get `html_theme_options` to work?

**Comment by mondeja** [comment]
> No, I haven't. I thought that was the default theme that didn't need to be inlucded.
> Am I supposed to use that line even though it is the default to get `html_theme_options` to work?

Yes, you need to include it because the default theme for sphinx is [alabaster](https://alabaster.readthedocs.io/en/latest/).

**Comment by gthvidsten** [comment]
This is on ReadTheDocs, so I automatically get the RTD sphinx theme without specifying a theme.

**Comment by mondeja** [comment]
The default value if you don't set it explicitly is `"alabaster"` as you can see [here](http://www.sphinx-doc.org/es/stable/config.html#confval-html_theme). You can use this to make it work in ReadTheDocs:
```python
html_theme = "alabaster"
if 'READTHEDOCS' in os.environ:
    html_theme = "sphinx_rtd_theme"
```

**Comment by gthvidsten** [comment]
I've started a new build at ReadTheDocs with `html_theme`. Hopefully this is enough :)

I still think it shouldn't be necessary to _have_ to specify `html_theme` for `html_theme_options`, though, to make life just a little bit easier for users.

**Comment by mondeja** [comment]
It seems that an error with [readthedocs.org](https://github.com/readthedocs/readthedocs.org), because I can't reproduce it in local.

**Comment by gthvidsten** [comment]
I suspected as much, which is why I posted it in their issue list originally (but it got moved here). If someone can move it back it would be greatly appreciated :)

**Comment by stsewd** [comment]
@gthvidsten make sure you are using the same sphinx version locally and on rtd https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by gthvidsten** [comment]
I'm not doing any local documentation. I use readthedocs exclusively.

**Comment by stsewd** [comment]
@gthvidsten please check https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

**Comment by gthvidsten** [comment]
I'm not looking to run Sphinx locally. I just want to use the one on RTD... and that doesn't use any of the `html_theme_options` whether or not `html_theme` is set, and me running Sphinx locally will not change the RTD behavior.

**Comment by stsewd** [comment]
@gthvidsten looks like you have typo in https://github.com/whitestone-no/Cambion/blob/9c90ff07978b25b873bae781df69c1af1b716c59/docs/conf.py#L15

it should be `html_theme = 'sphinx_rtd_theme'`
