### ISSUE TITLE
Use unique identifier to avoid caching

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#910]
I enabled the RTD PR builder for this project, however CSS and JS get cached at the CDN now, making PR review of built documentation not very helpful -- these assets will get cached and any updates to CSS/JS on the PR won't show.

We can avoid this by using a query string to avoid the caching and would have a few things to decide on:

* What string to use? We surface `{{ commit }}` for most builds, we could conditionally add that on the end of js/css requests: `{% if commit %}?{{ commit }}{% endif %}`. Is there a better string?
* Is there a more generalized solution to this? Sphinx extension that does this for us?
* Do we want this on just development/PR builds? On the base theme `layout.html` and all projects that use our theme? Perhaps start by making this a configuration variable and work towards making it the default?

My vote is to use `commit`, and use a configuration variable to enable the addition to URLs.

**Comment by benjaoming** [comment]
@agjohnson I moved this to the 2.0 milestone, LMK if it's more urgent :+1:

**Comment by humitos** [comment]
I think this is already solved by Sphinx 7.x that adds `?v=` to all the assets files. On the other hand, Read the Docs purges the cache on every successful build, so that cache issue is not a problem anymore.

Feel free to re-open this issue if you still consider valid.
