### ISSUE TITLE
Margins are broken in bullet lists on 0.5.0rc1

### ISSUE THREAD

**Issue by jack1142** [readthedocs/sphinx_rtd_theme#916]
### Problem

Margins in bullet lists are extremely large on 0.5.0rc1
Happens on both Sphinx 2.4.4 and Sphinx 3.0.3

### Reproducible Project

RTD 0.4.3, Sphinx 2.4.4 (how it should look):
https://docs.discord.red/en/latest/guide_publish_cogs.html

RTD 0.5.0rc1, Sphinx 2.4.4 & 3.0.3 (broken margins):
https://jack1142-red-prs.readthedocs.io/en/v3-bump_deps/guide_publish_cogs.html

#### Error Logs/Results

RTD 0.5.0rc1, Sphinx 2.4.4 & 3.0.3 (broken margins):
![image](https://user-images.githubusercontent.com/6032823/81244766-86e2a480-9013-11ea-9970-aefa4cd8c03a.png)

#### Expected Results

RTD 0.4.3, Sphinx 2.4.4 (how it should look):
![image](https://user-images.githubusercontent.com/6032823/81244738-7a5e4c00-9013-11ea-9d75-2162ab352618.png)

### Environment Info

- Python Version: 3.8.0
- Sphinx Version: 2.4.4 & 3.0.3
- RTD Theme Version: 0.5.0rc1

**Comment by agjohnson** [comment]
Thanks for the report! You actually look to be using the html4 writer still, does the output improve with the html5 writer?

The bug here looks to be a nested `<p>` element and a selector adding margin to `:last-child`. This in theory shouldn't have changed, but likely there wasn't a test case with a `<ul><li><p>...` structure.

**Comment by jack1142** [comment]
@agjohnson That particular thing looks better on html5 writer, though it's not perfect - margins for the "tip box" are a little off:
![image](https://user-images.githubusercontent.com/6032823/81341951-b72d5000-90b2-11ea-82ea-06ed6a1267f6.png)

Link: https://jack1142-red-prs.readthedocs.io/en/v3-bump_deps_html5_writer/guide_publish_cogs.html

​

For now I just wanted to see if I can upgrade Sphinx without using new writer, I will move to it eventually, but there are still some problems with it like:

- small margins in lists for code blocks (actually not sure if there's an issue for it):
  - html4 writer (https://docs.discord.red/en/latest/update_red.html#linux-mac):
    ![image](https://user-images.githubusercontent.com/6032823/81342323-56524780-90b3-11ea-8cbb-84d81285ada4.png)
  - html5 writer (https://jack1142-red-prs.readthedocs.io/en/v3-bump_deps_html5_writer/update_red.html#linux-mac):
    ![image](https://user-images.githubusercontent.com/6032823/81342655-ded0e800-90b3-11ea-80f2-4af59caff65d.png)
- Parameters/Returns/Return Type/etc in functions/methods are unnaturally big (#766 maybe?):
  - html4 writer (https://docs.discord.red/en/latest/framework_bank.html#redbot.core.bank.set_balance):
    ![image](https://user-images.githubusercontent.com/6032823/81343169-c01f2100-90b4-11ea-854d-b43b80c91344.png)
  - html5 writer (https://jack1142-red-prs.readthedocs.io/en/v3-bump_deps_html5_writer/framework_bank.html#redbot.core.bank.set_balance):
    ![image](https://user-images.githubusercontent.com/6032823/81343106-a382e900-90b4-11ea-950a-08ec63418c17.png)
- This, not sure if it's wrong but looks weird in comparison to what was there before (hard to find an issue if you don't what to look for 😄)
  - html4 writer (https://docs.discord.red/en/latest/guide_cog_creation.html#getting-started):
    ![image](https://user-images.githubusercontent.com/6032823/81343558-7edb4100-90b5-11ea-832c-932605123731.png)
  - html5 writer (https://jack1142-red-prs.readthedocs.io/en/v3-bump_deps_html5_writer/guide_cog_creation.html#getting-started):
    ![image](https://user-images.githubusercontent.com/6032823/81343592-8c90c680-90b5-11ea-8390-146b95a0d7a5.png)

I can make issues for those, though I didn't plan to look into html5 writer just yet 😄

**Comment by agjohnson** [comment]
Great, that's all very helpful. Seems we need to get some more test cases into the demo docs.

That last one is a good example -- a definition list with multiple words (?) i believe gets a different class (`dl.simple`) than other definition lists. There is already a fix merged for that one at least, #914.

**Comment by jack1142** [comment]
I should probably make a separate issue for the second (or add a comment on some existing issue if you've got any pointers), the third one is already fixed in master as you said and first one might be related to this issue.

**Comment by agjohnson** [comment]
I've opened #939 to address the spacing issues.

I noticed in building a test case that your examples are rendering as blockquotes inside list elements, which will affect display a bit more than simply nesting. This is due to the spacing being different between the reST bullet list and the paragraph/admonition blocks that follow the initial list item text.

I made our test case use the list spacing, not blockquote spacing, but things look more consistent now. I didn't test how this might affect the blockquote usage nested in a list item.

I'm going to treat #939 as the fix to this issue, but perhaps if there is something to change after a 0.5.0rc2 we can decide if it needs to be a theme fix or not.

**Comment by jack1142** [comment]
@agjohnson I'm not entirely sure, is it intended that the margins here are now larger?

[0.5.0rc2](https://jack1142-red-prs.readthedocs.io/en/v3-bump_deps_html5_writer/update_red.html#linux-mac):
![image](https://user-images.githubusercontent.com/6032823/83917779-bf42e300-a777-11ea-80a9-d8d32cf3df12.png)

[0.4.3](https://docs.discord.red/en/latest/update_red.html#linux-mac):
![image](https://user-images.githubusercontent.com/6032823/83917794-c4a02d80-a777-11ea-9408-795a30759193.png)
