### ISSUE TITLE
Avoid caching of JS/CSS assets in theme/globally

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#924]
In #918 we are implementing a version of this to ensure fresh assets in PR builds for the theme, however we've often wanted this for both theme assets and for our RTD included JS (ensuring freshness of the included JS is a separate issue from this however).

Some options:

* Alter template `<script>`/`<link>` and include a SHA sum for the added JS/CSS in the URL -- ie

  ```<link href="{{ pathto('theme.css') }}?{{ md5sum 'theme.css' }}">```

* Use subresource integrity in a similar way, there are additional benefits to this method
* Fix this with an extension that patches `pathto`, similar to #918, and usable by all themes
* etc

**Comment by humitos** [comment]
Dup of https://github.com/readthedocs/sphinx_rtd_theme/issues/910
