### ISSUE TITLE
code blocks not rendered online when using code::

### ISSUE THREAD

**Issue by Yquetzal** [readthedocs/sphinx_rtd_theme#937]
I export .rst files from jupyter notebooks to create tutorials.
in this export, code blocks are encoded as:
`.. code:: ipython3` 

When I generate html with sphinx locally, the code blocks render correctly.
But on readthedocs, the blocs are invisible.

I checked that if I just change the line from:
`.. code:: ipython3` 
to
`.. code-block:: ipython3` 

Then it works both locally and online.

**Comment by stsewd** [comment]
Looks like a problem related to your build on read the docs, I'm guessing a mismatch of the sphinx version. You need to use a requirements file with the same sphinx version you are using locally https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html If your problem persists, please open an issue in https://github.com/readthedocs/readthedocs.org with a link to your project
