### ISSUE TITLE
Deprecate HTML4 writer

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx_rtd_theme#938]
The 0.5.0 release is dealing with a lot of incompatibility added by Sphinx switching the default html writer to HTML5. While we can continue supporting both the html4 and html5 writer in our stylesheets, we will be duplicating development efforts and QA on any stylesheet changes that touch list styles or other elements that were significantly altered with the switch to the HTML5 writer.

The issue that I'm seeing with supporting the html4 writer is that we'll have spread testing and QA of the theme pretty thin, as we already have to support 3 versions of Sphinx and multiple versions of Python. Adding on top of this testing of both html4 and html5 writer for at least multiple versions of Sphinx feels like a lot of testing for little benefit.

So: what are our feelings on the HTML4 writer? Is it important to support it? This is almost a conversation about which versions of Sphinx we want to support, as I think most users just use the default version of the writer.

I think what I'd propose is:

* Aim to support Sphinx 2.0 and 3.0 with a 1.0 release. Do we not support Sphinx 1.8 at all?
* Start throwing a soft deprecation warning about the html4 writer. Users using Sphinx<2.0 will likely see this warning. The deprecation warning will alert the user to switch to a newer release of Sphinx or the HTML5 writer
* In a following release, 2.0 perhaps, we throw a harder deprecation warning or error if using the HTML4 writer. In this release, I guess we remove the HTML4 writer specific CSS rules.

**Comment by Daltz333** [comment]
👎 to supporting Sphinx 1.8.
👍 for deprecating, I doubt it will effect the vast majority of users. However I believe this should be a harder warning especially if a stable release cycle isn't found (2.0 being in 3 years???)

**Comment by agjohnson** [comment]
version 1.0 and 2.0 would be dependent on backwards incompatible changes to our API, not based on time.

**Comment by Daltz333** [comment]
Ah, I understand. I had doubt based on the development momentum of this project as of recently (seems like there is a lot of "core" internal changes that had to be addressed). I'm fine with deprecating with semver.
