### ISSUE TITLE
Bottom margin of code block in bullet list is too small (regression from 0.5.0rc1)

### ISSUE THREAD

**Issue by jack1142** [readthedocs/sphinx_rtd_theme#943]
### Problem

Bottom margin of code block in ~~bullet~~ (apparently number list is affected as well, [link](https://jack1142-red-prs.readthedocs.io/en/v3-bump_deps_html5_writer/framework_config.html#tutorial)) list is too small in version 0.5.0rc2 (on both html writers)

### Reproducible Project

Links below.

#### Error Logs/Results

Version 0.5.0rc2 (on both html writers):
![image](https://user-images.githubusercontent.com/6032823/83917081-99690e80-a776-11ea-83a3-486ea4154484.png)
[Link (html4 writer)](https://jack1142-red-prs.readthedocs.io/en/v3-bump_deps/install_windows.html#installing-red)
[Link (html5 writer)](https://jack1142-red-prs.readthedocs.io/en/v3-bump_deps_html5_writer/install_windows.html#installing-red)

#### Expected Results

How it looked before (0.5.0rc1 and older):
![image](https://user-images.githubusercontent.com/6032823/83917145-b271bf80-a776-11ea-8ad3-fbc8c28c7119.png)
[Link](https://docs.discord.red/en/latest/install_windows.html#installing-red) (this one is on 0.4.3 as I don't have 0.5.0rc1 link handy but I did test locally that it looked the same on 0.5.0rc1)

### Environment Info

- Python Version: 3.8.3
- Sphinx Version: 3.0.3
- RTD Theme Version: 0.5.0rc2

**Comment by agjohnson** [comment]
Ah, this was a test case that might have been lost. 0.5.0rc2 fixes a lot of spacing inconsistencies in <=0.4.3.

Some notes here about the change in 0.5.0rc2:
https://github.com/readthedocs/sphinx_rtd_theme/pull/939#issuecomment-639126429

I have a tiny patch ready that makes *only* `<p>`, `<ul>`, and `<ol>` elements nested in the last child position in a list item have `margin-bottom: 0rem`. I'll get a PR up so we can get 0.5.0 shipped this week.

**Comment by agjohnson** [comment]
I've opened up #945, it should resolve your issue. It might be good to pull down that branch and test your docs to verify before release.

**Comment by jack1142** [comment]
I'll be sure to do that tomorrow :) If I want to install it, do I need to follow the instructions from [contributing docs](https://sphinx-rtd-theme.readthedocs.io/en/latest/contributing.html#set-up-your-environment)?

**Comment by jack1142** [comment]
I had some troubles getting this to work (the simple pip install didn't really work) and ended up just following the contributing docs and copying the built theme after.

The fix works fine, only two things left that might possibly be bugs is the changed margin size I mentioned [here](https://github.com/readthedocs/sphinx_rtd_theme/issues/916#issuecomment-639763927) and the weird spacing here (though this one is probably #705 which just makes that one margin under code block stand out even though it's more "correct" from the rest):
![image](https://user-images.githubusercontent.com/6032823/84454396-b7dd7700-ac5a-11ea-9c35-df0636120caf.png)

But I'm happy with all the stuff that's been fixed and it seems that I will probably be able to switch to Sphinx 3.0.3 and html5 writer when 0.5.0 gets released :)

**Comment by agjohnson** [comment]
Ah, so this provided a bit of context:
https://docutils.sourceforge.io/sandbox/html4strict/data/simple-lists.html

We weren't really doing this in 0.4.3, but the results were closer than what 0.5.0 has. I'll update #945

**Comment by jack1142** [comment]
@agjohnson let me know when you do and I'll be happy to test it again :) (though probably not before Thursday)

**Comment by agjohnson** [comment]
@jack1142 the change is pushed up to #945, it was a fairly minor update.

I pulled a couple source files from the discord red docs and generated locally, things seem to better:

![image](https://user-images.githubusercontent.com/1140183/84823176-2748c300-afdb-11ea-842c-3b072c6999c8.png)

**Comment by jack1142** [comment]
I'll probably still test out the merge branch of #945 with the whole Red-DiscordBot's docs to see if I missed anything else but it seems to look better now basing on the screenshot 👍

**Comment by agjohnson** [comment]
One issue that I do see is that your use case would look better with some spacing at the end, which is in line with what docutils was suggesting for spacing:

![image](https://user-images.githubusercontent.com/1140183/84829381-e190f800-afe4-11ea-99ea-fcaf39127c1c.png)

But with this change to css rules, the output looks considerably worse for basic complex lists (and i'm sure most authors are not aware of the difference between a simple and complex list):

![image](https://user-images.githubusercontent.com/1140183/84830043-046fdc00-afe6-11ea-84d2-27f3e1c70ce9.png)

**Comment by jack1142** [comment]
> One issue that I do see is that your use case would look better with some spacing at the end, which is in line with what docutils was suggesting for spacing:

I did notice it but I wasn't sure if it's not just because I'm actively looking for something to be wrong but if you also point it out, I probably don't.


> But with this change to css rules, the output looks considerably worse for basic complex lists (and i'm sure most authors are not aware of the difference between a simple and complex list):

That indeed looks quite bad. And sadly you're right that most authors are probably not aware of the difference (me included until now).
I do have a question though, wouldn't it be possible to differ the formatting based on whether the last child is first child as well (it seems like this is the reason why the margin there gets changed to 0)? Or would that cause even more problems?

**Comment by agjohnson** [comment]
I actually was just playing with this. I think it's a good compromise. Using `:only-child` the margin can be limited to list items with multiple paragraphs. It looks better on the red docs:

![image](https://user-images.githubusercontent.com/1140183/84833636-f6718980-afec-11ea-8424-1be95b279fb3.png)

and the demo docs:

![image](https://user-images.githubusercontent.com/1140183/84833616-ed80b800-afec-11ea-8e14-3b1ef69abb54.png)

**Comment by jack1142** [comment]
I don't know if there are any gotchas where this could result in badly styled output but I like how it looks :)

**Comment by jack1142** [comment]
@agjohnson The only difference that stood out for me is how the index list looks now:
[0.5.0](https://jack1142-red-prs.readthedocs.io/en/v3-bump_deps_html5_writer/):
![image](https://user-images.githubusercontent.com/6032823/84957074-bef10300-b0fa-11ea-8440-5c68edb83a81.png)
[0.4.3](https://docs.discord.red/en/latest/):
![image](https://user-images.githubusercontent.com/6032823/84957242-14c5ab00-b0fb-11ea-9a19-87ec42985a18.png)

That's not caused by the `:only-child` part of the change as far as I can tell but I'm guessing something else in #945 did change the styling of nested lists. It might be intended here, I just noticed it looks different than it did before.

**Comment by agjohnson** [comment]
This is a side effect of the ul.simple vs ul.complex listing style recommended by docutils. If it was going to be so opinionated about list spacing, docutils should probably have implemented a `ul.complex` class strictly for lists with nested paragraphs. :confused: 

In the 0.5.0 case above, the toc list is not output as a `ul.simple` and so it gets the extra margin on list items (it's considers a "complex" list). If you change the `<ul>` to `<ul class="simple">` it looks correct, like in 0.4.3.

We can add a selector to the existing `ul.simple` styles for `div.toctree-wrapper > ul:not(.simple)` perhaps, but hopefully this isn't the start of a long game of whack-a-mole.

I'll throw up a PR for 0.5.1 perhaps, it's a minor fix. Thanks for the additional report!
