### ISSUE TITLE
sphinx_rtd_theme extension does not declare if it is safe for parallel reading

### ISSUE THREAD

**Issue by Holzhaus** [readthedocs/sphinx_rtd_theme#944]
### Problem

The extension causes a warning when sphinx-build is used with `-j $(nproc)`.

#### Error Logs/Results

```
WARNING: the sphinx_rtd_theme extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```

#### Expected Results

Please fix the warning. This could also improve build times.

### Environment Info

- Python Version: 3.7
- Sphinx Version: 3.0.4
- RTD Theme Version: 0.4.3

**Comment by p12tic** [comment]
This has already been fixed in #874.

**Comment by Holzhaus** [comment]
On second thought, let's leave this open until 0.5.0 has been released.

**Comment by agjohnson** [comment]
0.5.0 is now out and it should have these declarations on the theme extension
