### ISSUE TITLE
Table of contents items not associated with their headers

### ISSUE THREAD

**Issue by jonels-msft** [readthedocs/sphinx_rtd_theme#957]
### Problem

Menu items in the toctree have no markup that associates them with non-link menu headers.
https://github.com/readthedocs/sphinx_rtd_theme/blob/a13a7b4b448b040ae0867d76fe71643bd83035b1/sphinx_rtd_theme/layout.html#L157

The menu headers are merely paragraphs with a class:
```html
<p class="caption"><span class="caption-text">Foo</span></p>
```

### Reproducible Project

https://docs.citusdata.com/en/v9.3/get_started/what_is_citus.html

#### Error Logs/Results

Here is a video demonstrating the problem: https://www.youtube.com/watch?v=BmeXqA3Bzt4

#### Expected Results

A screenreader should understand the relationship of links to headers, and be able to announce e.g. "Link, What is Citus, under Get Started."

See [WCAG 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html) for guidance.

### Environment Info

- Python Version: 3.7.7
- Sphinx Version: 1.4.9
- RTD Theme Version: 0.2.4

**Comment by Blendify** [comment]
I think you are better off reporting the bug to Sphinx, we have no control of the markup that comes from `toctree`. Since this is a markup issue derived from sphinx and not something we can fix I am going to close this.

**Comment by jonels-msft** [comment]
I think Github has a feature where you can "move" an issue between repos. Do you have access to move this one to the sphinx repo, @Blendify ?

**Comment by Blendify** [comment]
I do not
