### ISSUE TITLE
Paragraphs in search results are not identified as <p> in the markup

### ISSUE THREAD

**Issue by jonels-msft** [readthedocs/sphinx_rtd_theme#959]
### Problem

Paragraphs in search results are stored in divs rather than `<p>`. This withholds information from screenreaders which would help orient users.

### Reproducible Project

https://docs.citusdata.com/en/v9.3/search.html?q=azure&check_keywords=yes&area=default#

#### Error Logs/Results

![paragraphs - MAS 1 3 1-Paragraph content are programmatically not defined](https://user-images.githubusercontent.com/48225118/85646179-2958f480-b661-11ea-959d-996b639ac58c.jpg)

#### Expected Results

Use true paragraphs, as described in [WCAG 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html)

### Environment Info

- Python Version: 3.7.7
- Sphinx Version: 1.4.9
- RTD Theme Version: 0.2.4

**Comment by stsewd** [comment]
This one actually comes from sphinx itself https://github.com/sphinx-doc/sphinx/blob/275d93b5068a4b6af4c912d5bebb2df928416060/sphinx/themes/basic/static/searchtools.js#L505

**Comment by stsewd** [comment]
Please open this ticket in the sphinx repo https://github.com/sphinx-doc/sphinx.
