### ISSUE TITLE
Edit On Github control disappears at 400% zoom

### ISSUE THREAD

**Issue by jonels-msft** [readthedocs/sphinx_rtd_theme#964]
### Problem

Each page has a link to edit on github:
![Screen Shot 2020-06-25 at 10 46 51 PM](https://user-images.githubusercontent.com/48225118/85818237-c7b68a00-b735-11ea-90b0-21c659725667.png)
At 400% zoom it disappears, and I don't know another way to access that functionality at high zoom.

### Reproducible Project

https://sphinx-rtd-theme.readthedocs.io/en/stable/index.html

#### Error Logs/Results

![Screen Shot 2020-06-25 at 10 48 53 PM](https://user-images.githubusercontent.com/48225118/85818349-1106d980-b736-11ea-8fd5-8e9f1c83fdfe.png)

#### Expected Results

The edit on github functionality should be available to low-vision users, even if the link perhaps moves to a different location.

### Environment Info

(Probably the latest version since it's sphinx_rtd_theme's own docs page)

**Comment by Blendify** [comment]
This is intensional to save space when viewing on mobile devices, so I would not consider this a bug.

**Comment by jonels-msft** [comment]
Is there another place it could go, like inside the hamburger menu?

Because the current behavior disables functionality for low-vision users, it's a form of inaccessibility.

**Comment by Blendify** [comment]
![image](https://user-images.githubusercontent.com/15183467/110991503-b3a5cd80-8342-11eb-878f-6a70774bf8cd.png)
