### ISSUE TITLE
Adding a custom box to the navigation bar

### ISSUE THREAD

**Issue by JurajMa** [readthedocs/sphinx_rtd_theme#982]
### Problem

I need to import a custom box into the navigation bar. Basically, something like the _Support Read the Docs!_ box on the website (https://sphinx-rtd-theme.readthedocs.io/en/stable/index.html)

Does anyone know how to achieve this?

Any help would be greatly appreciated!

**Comment by stsewd** [comment]
The best way is to override one of the templates https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-templates_path 

https://github.com/readthedocs/sphinx_rtd_theme/blob/006cd2162aac1c3e4c00542a38c9e47e0524ca46/sphinx_rtd_theme/layout.html#L149-L170
