### ISSUE TITLE
Question: Switch-language

### ISSUE THREAD

**Issue by fiolj** [readthedocs/sphinx_rtd_theme#988]
### Problem

I want to include a "choose language" button, that may be located either in the navbar or in all pages?
There is a form to add that? or a recommended way?

**Comment by stsewd** [comment]
The best way is to override one of the templates https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-templates_path https://github.com/readthedocs/sphinx_rtd_theme/blob/include-preinstall/sphinx_rtd_theme/layout.html
