### ISSUE TITLE
Lots of Unreviewed PRs

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/sphinx_rtd_theme#997]
There seems to be lots of Unreviewed PRs and very intermittent review or none at all on this repository. Any chance some of the features could get looked at?

**Comment by stsewd** [comment]
First, thanks everyone who have sent a PR! Our team that has experience with css/jss/design is currently focussed in the redesign of readthedocs.org, so review may be a little slow here.

**Comment by stsewd** [comment]
Ok, I did my best to label/close/reply all open issues and a couple of reviews and fixes https://github.com/readthedocs/sphinx_rtd_theme/pulse/monthly. There are still PRs to review, but hopefully the team can get to that soon.
