### ISSUE TITLE
NOOB: Generate PDF and Display Versions in HTML

### ISSUE THREAD

**Issue by SysEngDan** [readthedocs/sphinx_rtd_theme#999]
I'm new to using sphinx_rtd_theme and can't quite figure out the differences between RTD (https://docs.readthedocs.io/en/stable/) and sphinx_rtd_theme. 

Am I able to:
- Display / generate PDF for download from within rendered HTML
- Display / change between versions of the docs?

Would you kindly provide me with any links that reference how to accomplish these, if they are possible?

**Comment by stsewd** [comment]
> Display / change between versions of the docs?

@SysEngDan that feature you mention is provided by Read the Docs, not the theme itself (the theme integrates with this in a better way than other themes).

> Display / generate PDF for download from within rendered HTML

You can use the pdf builder from sphinx, but IFAIK it doesn't use the theme to generate the pdf.

You can check the features that Read the Docs provides in https://docs.readthedocs.io/en/stable/features.html
And the configs from the theme at https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html
